### ISSUE TITLE
Add support for CacheControl extension

### ISSUE THREAD

**Issue by varunkumar** [graphql-java/graphql-java#1034]
[Apollo CacheControl extension](https://github.com/apollographql/apollo-cache-control) provides fine-grained cache control over server-side or client-side GraphQL caches. It describes a format for a GraphQL API to return information about cache expiration and scope, as well as controls that a client can use to override caching.

This will be a handy extension to manage cache efficiently. Let me know if this standard makes sense to be implemented in `graphql-java`. I can help with PR if you agree with the extension.

**Comment by bbakerman** [comment]
Yeah I am receptive to this.  We have some Apollo support for tracing already in graphql-java via `graphql.execution.instrumentation.tracing.TracingInstrumentation`

I think this caching control would need to be done via an `Instrumentation` so that consumers would opt into the behaviour by "adding the instrumentation" into the mix.

We would love to see a PR on how this might work.

The request format is intereting

```
"extensions": {
  "cacheControl": {
    "version": 1,
    "noCache": true
  }
}
```

how does a client specify that?  where?   in the variables map??  There are no "extensions" input that I know of??

**Comment by varunkumar** [comment]
My understanding is that the client doesn't need to specify anything in the request. Client can just use information like `maxAge` to manage its cache. Tools like Apollo engine can also use this information to manage its cache.

**Comment by bbakerman** [comment]
This is very viable - and the more that the Apollo spec / engine gains ground the more we need it.

We have "extensions" on the execution result today so one could could your own.

However we dont allow each individual data fetcher to "add" their own extension paths today.  We only allow it AFTER the query is done which is not powerful

Even SDL annotated cache control mechanisms would still need data fetcher result extensions.

I am thinking off hand there but I think `DataFetcherResult` would be the place for a DF to "return extension" data some how.  This could then be combined into the extensions map towards the end.
