### ISSUE TITLE
graphql can't support float.NaN

### ISSUE THREAD

**Issue by FutureElement** [graphql-java/graphql-java#1062]
Hi,this exception is 
```
Can't serialize value (/project/situation/healthSituation/pipelineSituation/sqaleDebtRatio) : Expected type 'Float' but was 'Float'
```
the java type is float , the value is float.NaN

**Comment by bbakerman** [comment]
NaN is not a valid float and the spec (and reference graphql-js implementation) require valid floats.

The error message could be improved I agree but it is invalid

**Comment by bbakerman** [comment]
here is the grapqhl-js reference implementation

```
function coerceFloat(value: mixed): ?number {
  if (value === '') {
    throw new TypeError(
      'Float cannot represent non numeric value: (empty string)',
    );
  }
  const num = Number(value);
  if (num === num) {
    return num;
  }
  throw new TypeError(
    'Float cannot represent non numeric value: ' + String(value),
  );
}
```

for the record

**Comment by FutureElement** [comment]
ok, thanks

**Comment by fedinskiy** [comment]
@bakert the latest GraphQL [specification](https://spec.graphql.org/June2018/#sec-Value-Completion) states, that NaNs should be transformed into nulls("If result is null (or another internal value similar to null such as undefined or NaN), return null.").
I propose reopening this issue, since right now jthe ava implementation is clearly breaking the specs.

**Comment by bakert** [comment]
A stray call for @bbakerman not @bakert  :)

**Comment by fedinskiy** [comment]
@bakert oops, my bad, thank you for pointing this :-)
