### ISSUE TITLE
Chained DataLoader in field

### ISSUE THREAD

**Issue by johnarne** [graphql-java/graphql-java#1078]
I have a use case where I need to do multiple loads from DataLoader to resolve a field. I'm currently using thenCompose to chain the load requests. When the DataLoader is dispatched, only the first request is fired, since the second isn't queued yet. There's no new dispatch, and so the CompletableFuture is never completed. See https://gist.github.com/johnarne/9c41611238c06d9e336adfd7e832317e for trivial example.

Is there another way of chaining DataLoader calls to have them all run when resolving field? Or will I have to stick to thenApply and manually calling dispatch after each subsequent load?

**Comment by bbakerman** [comment]
Can you better describe your data dependencies.  I can see in your trivial example that that is +1 to a numebr and then do it again.

But this is hard for me to get meaningful discussion on.

Do you have a situation where in order to create a FooBar object you first need to fetch the Foo and then once you have that you need to fetch the Bar for that Foo?

Cant you just do that in your batch loader (pseudo java code)

```
BatcherLoad<String,FooBar> batchloader = keys  -> {
    return CompletableFuture.supplyAsync(() ->  getAllFoos(keys))
      .thenApply( foos -> getAllBarsForTheseFoosAndTurnThemIntoFooBars(foos))
}
```

??

There is no way today to chain data loader calls since they are "batched" together as a batch loader function call.

**Comment by arlampin** [comment]
We have a similar situation (I think). We have a DataLoader `DataLoader<ID<Foo>, Bar>`, which is implemented by fetching a `Map<ID<Foo>, ID<Bar>>` from backend, then loading each individual Bar by its ID. The backend basically returns a Foo ->Bar map.

For various reasons, we can't return the full Bar instance in the initial query, but have to load them separately. Since we already have a DataLoader to fetch Bar instances by their ID, I though I could use that to `.loadMany` the IDs.

In our case, a large number of requested Bar instances are already loaded from backend within the same GraphQL query, so by re-using the same ID loader we save lots of backend queries due to DataLoader cache.

**Comment by bbakerman** [comment]
@arlampin - can you outline some pseudo code on how you chain the calls together to be efficient?

The challenge I can see is around when to dispatch the second load of `<Bar>` load calls

**Comment by arlampin** [comment]
@bbakerman sure. Something like this.

```
DataLoader<ID<Bar>, Bar> barIdLoader = ...;

DataLoader<ID<Foo>, Bar> fooBarLoader = new DataLoader<>(keys -> {
  CompletableFuture<Map<ID<Foo>, ID<Bar>>> query = backend.asyncGetFooBarMap(keys);
  query.thenCompose(map -> {
    List<ID<Bar>> barIds = new ArrayList<>(map.values());
    return barIdLoader.loadMany(barIds).thenApply(bars -> {
        Map<ID<Bar>, Bar> barIndex = bars.stream().collect(toMap(Bar::getId, Function.identity()));
        return keys.stream().map(map::get).map(barIndex::get).collect(toList());
    });
  });
});
```

Yeah, I'm not sure if there's any clean solution to automatically dispatch the call...

**Comment by bbakerman** [comment]
There really is no clean way to dispatch the calls for "maximum efficiency".  The graphql engine tracks "fields" and their completion as to when to call dispatch.

But you have introduced a new layer.

IF you are caching there is still benefit so I would call dispatch direct inside that code..

eg

```
DataLoader<ID<Bar>, Bar> barIdLoader = ...;

DataLoader<ID<Foo>, Bar> fooBarLoader = new DataLoader<>(keys -> {
  CompletableFuture<Map<ID<Foo>, ID<Bar>>> query = backend.asyncGetFooBarMap(keys);
  query.thenCompose(map -> {
    List<ID<Bar>> barIds = new ArrayList<>(map.values());
    CompleteableFuture<?> cf = barIdLoader.loadMany(barIds).thenApply(bars -> {
        Map<ID<Bar>, Bar> barIndex = bars.stream().collect(toMap(Bar::getId, Function.identity()));
        return keys.stream().map(map::get).map(barIndex::get).collect(toList());
    });
    barIdLoader.dispatch()
    return cf;
  });
});
```

**Comment by arlampin** [comment]
Yeah, thanks, that's what I thought. We are now doing the dispatch thing and it works well enough.

**Comment by johnarne** [comment]
Same here, doing manual dispatch. Seems like the JS implementation would handle this use case without manual dispatching, since dispatching would happen at next tick? But yeah, I see no good way of figuring out when dispatching is needed. Feel free to close this issue, thanks for the clarifications.

**Comment by bbakerman** [comment]
Yeah JS has the nextTick() which is really the JS runtime saying... "I have run out of code to run.  Run all the promises now" etc..  Java doesn't have this.  Of course is its a proper pre-emptive runtime so you avoid this : 

![nodecpu](https://user-images.githubusercontent.com/1661769/41568632-09dcfde6-73aa-11e8-9430-b720271a7182.gif)

**Comment by benmosher** [comment]
Does all this still hold true? 

I ask because I just chained a few data loaders with v11 / DataLoader v2.2.1 and it works. But maybe by luck and not design?

**Comment by benmosher** [comment]
Update: seems like it can still hang with chained loaders and I was just lucking out with the dispatch order until today.
