### ISSUE TITLE
antlr4-runtime not included but needed in maven pom

### ISSUE THREAD

**Issue by piotrblasiak** [graphql-java/graphql-java#1082]
Since version 8.0 I´ve needed to explicitly include antlr4-runtime in my POM to make graphql work. If I don´t I get:

java.lang.NoClassDefFoundError: org/antlr/v4/runtime/CharStreams
	at graphql.parser.Parser.parseDocument(Parser.java:28)

**Comment by andimarek** [comment]
can you provide some details:

this is our dependency:

```xml
<dependency>
<groupId>org.antlr</groupId>
<artifactId>antlr4-runtime</artifactId>
<version>4.7.1</version>
<scope>compile</scope>
```
so it should be fine imho.

thanks

**Comment by piotrblasiak** [comment]
Ok, you´re right - I tried it with a fresh project and then I saw the dependency in the tree, so must be some conflict in my project. Sorry for wasting your time.

**Comment by chen-ni-hotstar** [comment]
@piotrblasiak How did you solve it? I'm having exactly the same issue in my project.

**Comment by piotrblasiak** [comment]
@chen-ni-hotstar I'm afraid this was so long ago I can't remember. Try checking for version conflicts in the dependency tre.

**Comment by chen-ni-hotstar** [comment]
@piotrblasiak Yeah sure! Thanks Piotr!

**Comment by dondonz** [comment]
@chen-ni-hotstar which version of graphql-java are you using?

**Comment by chen-ni-hotstar** [comment]
Hi @dondonz! I'm using this version of [Netflix DGS framework](https://netflix.github.io/dgs/) which itself depends on `graphql-java` version `4.8`. The issue turned out to be that another dependency (Lucene) in my project depends on `graphql-java` version `4.5.1` and is closer in the dependency tree. So Maven chooses that version of `graphql-java` which doesn't have the `CharStreams` class that exists in `4.8`.

I ended up having to add `graphql-java` version `4.8` in my `pom.xml` so that Maven chooses this version :)
