### ISSUE TITLE
Field selection validation does not obey spec

### ISSUE THREAD

**Issue by samkline** [graphql-java/graphql-java#1086]
[Section 5.3.2 (field selection merging)](http://facebook.github.io/graphql/June2018/#sec-Field-Selection-Merging) of the June 2018 spec is not obeyed.

In particular, it should be possible to use fragments to select different fields from different types using the same alias, but the `OverlappingFieldsCanBeMerged` rule prevents this with a `FieldsConflict` validation error.

I will attach a failing unit test showing example number 111 from the spec. Unfortunately I don't have time to fix this at the moment.

**Comment by samkline** [comment]
Failing unit test, taken from example 111 in the spec: https://github.com/samkline/graphql-java/commit/65db95ebe1254bb52c4691c07ff285b29b5795a4

**Comment by bbakerman** [comment]
Thanks for that.  I am creating a PR of this test and then start to investigate this bug.

We had another report of something similar in Atlassian where I work as well

**Comment by bbakerman** [comment]
Ok looking into this I found a few problems.

There is a typo where this is done (`fieldAndType1` twice)

            if (!sameType(fieldAndType1.parentType, fieldAndType1.parentType) &&
                fieldAndType1.parentType instanceof GraphQLObjectType &&
                fieldAndType2.parentType instanceof GraphQLObjectType) {
            return null;
        }



But even with that fix its still broken because it has this "type" equality check

```
    private boolean sameType(GraphQLType type1, GraphQLType type2) {
        if (type1 == null || type2 == null) return true;
        return type1.equals(type2);
    }
```

The GraphqlType objects do NOT have an equals method defined.  The reason for that is many but because GraphqlFieldDefinitions contain data fetchers they can be easily compared as equals.

I think we need to do a bit more work here in terms of "type equality"

**Comment by bbakerman** [comment]
There is also some non null / list type handling missing as well according to the spec.  The PR has this in place

Thanks @samkline for the initial unit test - that helped bootstrap this work a lot

**Comment by samkline** [comment]
Thanks for getting a patch up so quicly @bbakerman !
