### ISSUE TITLE
KnownDirectives rule doesn't recognize SDL directive locations

### ISSUE THREAD

**Issue by jimkyndemeyer** [graphql-java/graphql-java#1087]
With SDL directive locations such as `FIELD_DEFINITION` added in 9.0, it appears the the `KnownDirectives` rule wasn't updated to recognize these new locations:

https://github.com/graphql-java/graphql-java/blob/1839f250efcb0e5b36ac2301170256cc623b8c10/src/main/java/graphql/validation/rules/KnownDirectives.java#L45-L60

I came across this while using graphql-java to validate graphql files in js-graphql-intellij-plugin:

![image](https://user-images.githubusercontent.com/15837712/41618268-f0b63b12-7402-11e8-8a26-3cde957ad128.png)

The change as I understand it appears to be minor, so I should be able to do a PR if the change is welcome.

**Comment by bbakerman** [comment]
`graphql.validation.rules.KnownDirectives` is only used to validate queries and not SDL documents.  

I am confused here as to who is running that code.  That is an IDEA plugin is some how running graphql-java code or not?

That plugin "js-graphql-intellij-plugin" is written in what?  Java-Script at a guess or is it actually graphql-java

The enforcement of directive locations is not done by the "query rules" but rather by `graphql.schema.idl.SchemaGeneratorDirectiveHelper` and other classes in that package

Can you please explain more about how this "problem" presents itself (as in what code is running.  I can visually see that IDEA plugin thinks its wrong and that it is getting it wrong)

**Comment by jimkyndemeyer** [comment]
A bit more context:
- I'm the core developer for https://github.com/jimkyndemeyer/js-graphql-intellij-plugin which is written in Java
- For the 2.0 release, `graphql-java` will be used to provide the validation rules and schema tools for GraphQL editing. Previously the Facebook `graphql-js` reference implementation was used by the plugin via a Node.js process.

It's a bit of a complication that both SDL and executable GraphQL exists within the same language and file type, so I had the same concerns that you raise.

As it stands, I'm ignoring the "executable graphql" validation rule in the GraphQL code editor as the developer is not attempting to execute. However, if the developer were to execute the document from the above shown screenshot against a `graphql-java` endpoint, it would return not only the expected "executable" error, but also include "Directive not allowed here" errors, which is misleading given that the locations are valid. I'm not decided either way, only that it's potentially misleading.

As for the plugin, the schema validation that you mention could also trigger errors in the code editor given that the plugin builds a schema. So If you prefer not to update the `KnownDirectives` rule, I could work around it by ignoring directive location errors reported inside type definitions.

**Comment by bbakerman** [comment]
>  However, if the developer were to execute the document from the above shown screenshot against a graphql-java endpoint

The thing is its not really a sensible thing to submit a SDL document against a graphql server.  A server endpoint is the "realisation" of the schema whereas a SDL document is the original description of a schema.  Its the egg before the chicken if you will.

I can see your challenge here because you are trying to get "validation" from the library on whether a particular SDL text it valid or not.

You best bet for that would be to use 

`graphql.schema.idl.SchemaParser#parse(java.io.Reader)` and 

`graphql.schema.idl.SchemaGenerator#makeExecutableSchema(graphql.schema.idl.SchemaGenerator.Options, graphql.schema.idl.TypeDefinitionRegistry, graphql.schema.idl.RuntimeWiring)` and catch SchemaProblems and map the errors it might contain to locations in the document.

If you looks at the code you will see that there is a LOT of code involved in validating that a schema follows all the rules.

We have tried to implement as many as we can but we havent designed it to be consumed programmatically - that is interpetted by an editor etc.. it will be interesting to see if you can do that

**Comment by jimkyndemeyer** [comment]
Thanks, makes sense.

I'm currently using `UnExecutableSchemaGenerator.makeUnExecutableSchema` which appears to run a lot of the schema validation.

I'll make sure to separate the "executable/runtime" validation from the schema validation. I have all the info I need from the plugin parse tree to differentiate between them inside the plugin.

**Comment by bbakerman** [comment]
Let us know if we need to tweak the errors that come out of parse / wire so that you can report the errors in terms of text / line numbers.
