### ISSUE TITLE
DataLoader batching seems not to work with ExecutorServiceExecutionStrategy

### ISSUE THREAD

**Issue by brockgibson** [graphql-java/graphql-java#1122]
I am observing that batch loading is not occurring for the ExecutorServiceExecutionStrategy. Instead, it is exhibiting (N + 1) behavior. If I change to AsyncExecutionStrategy the batching works as expected.

I am able to reproduce this using the [graphql-java-http-example](https://github.com/graphql-java/graphql-java-http-example) sample app by:

- Updating the graphql-java gradle dependency to version 9.1 (it's at 5 now).
- Using the following ExecutorServiceExecutionStrategy in HttpMain
```new ExecutorServiceExecutionStrategy(
                new ThreadPoolExecutor(5, 10, 1, TimeUnit.MINUTES,
                        new SynchronousQueue<>(), Thread::new,
                        new ThreadPoolExecutor.CallerRunsPolicy()))
```
- Update StarWarsData to add Vader as a friend to Han to demonstrate a batch load 
```
    static Human han = new Human(
            "1002",
            "Han Solo",
            asList("1000", "1001", "1003", "2001"),
            asList(4, 5, 6),
            null
    );
```
- Modify StarWarsWiring to print out the key list being passed to the character BatchLoader
```
    // a batch loader function that will be called with N or more keys for batch loading
    private static BatchLoader<String, Object> characterBatchLoader = keys -> {

        System.out.println("load");
        keys.forEach(System.out::println);

        //
        // we are using multi threading here.  Imagine if getCharacterDataViaBatchHTTPApi was
        // actually a HTTP call - its not here - but it could be done asynchronously as
        // a batch API call say
        //
        //
        // direct return of values
        //CompletableFuture.completedFuture(getCharacterDataViaBatchHTTPApi(keys))
        //
        // or
        //
        // async supply of values
        return CompletableFuture.supplyAsync(() -> getCharacterDataViaBatchHTTPApi(keys));
    };
```
Then, run the following query:
```
{
    hero {
        name
        friends {
            name
            friends {
               name
            }
        }
    }
}
```

The output with ExecutorServiceExecutionStrategy is:
load
2001
load
1000
1002
1003
load
2000
load
1001

The output with AsyncExecutionStrategy (which is correct) is:
load
2001
load
1000
1002
1003
load
2000
1001

Query result is:
```
  "data": {
    "hero": {
      "name": "R2-D2",
      "friends": [
        {
          "name": "Luke Skywalker",
          "friends": [
            {
              "name": "Han Solo"
            },
            {
              "name": "Leia Organa"
            },
            {
              "name": "C-3PO"
            },
            {
              "name": "R2-D2"
            }
          ]
        },
        {
          "name": "Han Solo",
          "friends": [
            {
              "name": "Luke Skywalker"
            },
            {
              "name": "Darth Vader"
            },
            {
              "name": "Leia Organa"
            },
            {
              "name": "R2-D2"
            }
          ]
        },
        {
          "name": "Leia Organa",
          "friends": [
            {
              "name": "Luke Skywalker"
            },
            {
              "name": "Han Solo"
            },
            {
              "name": "C-3PO"
            },
            {
              "name": "R2-D2"
            }
          ]
        }
      ]
    }
  }
```

Note that caching works as expected.

**Comment by bbakerman** [comment]
This is working as like this by design (which might not be your expectation)

The challenge for DataLoader and graphql-java is knowing when is the most optimal time to dispatch calls to the data loaders.  It does this by tracking fields and KNOWING when the execution strategy has reach the most exhaustive end of the available field values.

It can ONLY do this if you use AsyncExecutionStrategy which is the default.

It turns of data loader optimisation for all other execution strategies since it cant KNOW when to do an efficient batch and if it didnt it could "hang" the query.

I suggest you dont use `ExecutorServiceExecutionStrategy` - rather if you want to make your calls async on different threads then use a DataFetcher pattern that submits it to a CompleteableFuture pool

    DataFetcher df = environement -> {
           return CompleteableFuture.supplyAsync( codeToGetData)
    }

This has the same async multi threaded behaviour as `ExecutorServiceExecutionStrategy` but it can be efficient in data loader terms.  You can also use your own executor pool with `CompleteableFuture.supplyAsync` so you have full control

@andimarek - I think we should possibly deprecate `ExecutorServiceExecutionStrategy` and remove it at a later time.

**Comment by brockgibson** [comment]
Thank you @bbakerman, very helpful information.

We are moving towards using the AsyncExecutionStrategy and supplying an ExecutorService in the supplyAsync method as you mention above. In the meantime, it might help to call out in the graphql-java docs some of the information above.

We've had issues in the past with getting the ThreadPool setup correctly with the ExecutorServiceExecutionStrategy as well such that it didn't hang and didn't underutilize threads. So deprecating seems reasonable from our viewpoint.

Thanks again!

**Comment by bbakerman** [comment]
We have some doco on http://graphql-java.readthedocs.io/en/latest/batching.html

I will extend it to explicitly talk about other Execution Strategies

**Comment by bbakerman** [comment]
See #1173
