### ISSUE TITLE
Duplicate fields in DFE and ExecutionInfo

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1270]
`DateFetcherEnvironment` provides access to some data which can also be accessed through `ExecutionInfo`. We should clean it up and deprecate one of each duplicate.

Duplicates:
- field (DFE has also fields)
- fieldType in DFE vs field in EI
- fieldDefinition 
- arguments (DFE has also getArgument and containsArgument)

also parentType in DFE is the type of the parent field and in EI parentType is actually the parent EI

**Comment by bbakerman** [comment]
We need all those attributes in `ExectionInfo` because as we form the execution tree we need the parent previous values. 

So really the question is one of easy of use versus duplication.

If someone is writing a data fetcher I posit that its easier to write

    DataFetcher df =  environment -> {
         String cId =  environment.getArgument("customerID")
         int pgCount =  environment.getArgument("pageCount")
         return customerService.getCustomer(cID,pgCount);
    }

then it is to write

    DataFetcher df =  environment -> {
        String cId =  environment.getExecutionInfo().getArgument("customerID")
         int pgCount =  environment.getExecutionInfo().getArgument("pageCount")
         return customerService.getCustomer(cID,pgCount);
    }

I think the arguments should DEFINITELY be duplicated on the DataFetcherEnvironment.  I can see a lesser argument for GraphqlFieldDefinition and I would be happy for Field to drop down into `ExecutionInfo` only

**Comment by andimarek** [comment]
happy to duplicate it for ease of use. Just wanted to make sure we are doing it deliberately.
