### ISSUE TITLE
Fetching single fields

### ISSUE THREAD

**Issue by sra-013** [graphql-java/graphql-java#1328]
Hi,

How do I implement the following functionality in graphql-java:

I have an object with multiple fields. The main data fetcher that I call fills only some of those fields. I want to create separate data fetchers/resolvers for the remaining fields. How do I create this?
Examples would be appreciated.

This is an example of the case where getters in the POJO of the object are called at various different places depending on their resource.

**Comment by bbakerman** [comment]
Every field in graphql has a data fetcher - but default that is a PropertyDataFetcher that is a "field name -> POJO getter " look up.

However you can wire in as many data fetchers as you like

For example here is a hand built object type (from the graphql java introspection class)

```
 public static final GraphQLObjectType __InputValue = newObject()
            .name("__InputValue")
            .field(newFieldDefinition()
                    .name("name")
                    .type(nonNull(GraphQLString)))
            .field(newFieldDefinition()
                    .name("description")
                    .type(GraphQLString))
            .field(newFieldDefinition()
                    .name("type")
                    .type(nonNull(typeRef("__Type"))))
            .field(newFieldDefinition()
                    .name("defaultValue")
                    .type(GraphQLString)
                    .dataFetcher(environment -> {
                        if (environment.getSource() instanceof GraphQLArgument) {
                            GraphQLArgument inputField = environment.getSource();
                            return inputField.getDefaultValue() != null ? print(inputField.getDefaultValue(), inputField.getType()) : null;
                        } else if (environment.getSource() instanceof GraphQLInputObjectField) {
                            GraphQLInputObjectField inputField = environment.getSource();
                            return inputField.getDefaultValue() != null ? print(inputField.getDefaultValue(), inputField.getType()) : null;
                        }
                        return null;
                    }))
            .build();
```
Notice how some of the fields have no data fetcher named?  This means they rely on POJO field fetching and hence the `name` fields comes from looking up the source object for a `getName` method.

However the `defaultValue` field has a specific data fetcher since it has more logic on it.  It takes the parent "source" object and applies some logic to it to derive a meaningful value

The example above is hand build objects.

You can also use SDL and `RuntimeWiring` rather than hand built objects

See 

https://www.graphql-java.com/documentation/v11/data-fetching/

https://www.graphql-java.com/documentation/v11/schema/

**Comment by sra-013** [comment]
Thanks!
So, currently I am following the current piece of documentation because that is what suits best to my needs:

https://www.graphql-java.com/documentation/v11/data-mapping/

I want data from multiple sources to be unified. I have created separate getters for each field inside the 'get()' method. Now I do understand that the dataFetchingEnvironment variable holds details on the fields to be fetched and that each field is mapped to its POJO getter. 

My doubt is that after coming inside the get() method, how does my fetcher look at getters that I have created for my fields.

So, for example, let's take the case given in the above link and let's say that I want only the cost info and not the tax info so my query looks something like (but I still have the taxinfo mapping of course):

query ProductQuery {
        products(match : "Paper*")
        {
            id, name, cost
        }
    }

How does my fetcher know that it should not be fetching the tax info?

**Comment by bbakerman** [comment]
```
query ProductQuery {
    products(match : "Paper*")
    {
        id, name, cost
     }
}
```
> How does my fetcher know that it should not be fetching the tax info?

In this case your business logic fetcher should be behind the `products` field

If you want to optimise the fetch such that you build a POJO or map where it does NOT get the `tax` field then you need the data fetcher to "look ahead" at the "selection set" of sub fields.  It would there have to know what possible sub fields it can handle and hence only get `id, name, cost` and not `tax`

Typically you would not a POJO but rather a Map of results which PropertyDataFetcher can pull part

See `graphql.schema.DataFetchingEnvironment#getSelectionSet` for API support in looking ahead to the selection set of sub fields.

however OFTEN what happens is that you do indeed build a POJO that contains `tax` from the backend BUT since the query never asked for that field it is loaded (say from the database) but never used.  Sometimes code is like that.  Optimising to ONLY get certain fields might not be worth it depending on execution complexity.

**Comment by bbakerman** [comment]
The other thing to consider is that the graphql engine maps ONLY those fields "asked for in the query" to property gets.  So in your example above no one asked for the `tax` field and hence even if it was present in a POJO or Map structure - it would never be returned in that graphql query.  The order of execution is


 products(match : "Paper*")   # <--- this is the main business logic fetch returning POJO/Map
    {
        id,          # <- property fetch - pojo.getId() or dataMap.get('id')
        name,   # <- property fetch - pojo.getName() or dataMap.get('name')
        cost      # <- property fetch - pojo.getCost() or dataMap.get('cost')
     }
