### ISSUE TITLE
Large list of DTOs from data fetcher taking very long time to process

### ISSUE THREAD

**Issue by mrubin** [graphql-java/graphql-java#1358]
We are investigating a performance issue when we return a large list of DTOs from a data fetcher. We are using graphql-java 11.0 on java 8/linux.

The schema looks like this:

```
type User {
  userId: ID
  email: String
  userName: String
  displayName: String
  avatarUrl: String
  isAdmin: Boolean
  isLockedOut: Boolean
  creationDate: String
}

type AdminViewOfUser {
  user: User!
  accountNumber: String
}

extend type QueryRoot {
  allUsers: [AdminViewOfUser!]
}
```

When using a DTO class (`AdminViewOfUserDTO` which contains `UserDTO` and a `String`) to return ~40,000 users from a data fetcher as `Iterable[AdminViewOfUserDTO]`, it takes 1-2 seconds to generate the list in the data fetcher and return it to graphql, and then it takes graphql almost 2 minutes to process that list and return the final result.

We have tried switching away from the DTO and instead returning `Iterable[Map[String, Object]]` from the data fetcher. This takes significantly less time to process the same ~40,000 users.

We strongly prefer the DTO approach. Why does it take so long to process? Is there anything we can do to make it faster?

Thank you

**Comment by andimarek** [comment]
Hi,

this is very likely caused by the [PropertyDataFetcher](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/PropertyDataFetcher.java) .
Each field in your DTO is accessed through the PropertyDataFetcher by reflection.

As an alternative you can register specific DataFetchers for each field of `User` which takes advantage of knowing that it is actually a UserDTO.

It would look something like that:
```java
DataFetcher dfName = env -> {
  UserDTO userDTO = env.getSource();
  return userDTO.getName();
}
```
This should be even faster than the Map approach.

**Comment by mrubin** [comment]
@andimarek Thank you for the suggestion. This approach (wiring up a specific DataFetcher for each field of `User` and `AdminViewOfUser`) is slower than the `Map` approach.. not nearly as bad as the DTO approach without the specific data fetchers, but about 3x slower than Map.

For ~40,000 of the above objects, I would be creating roughly 400,000 DataFetchingEnvironmentImpl (with the specific data-fetcher approach). Or would a DataFetchingEnvironmentImpl be created per field even with the reflection approach?

**Comment by andimarek** [comment]
A DataFetchingEnvironmentImpl will always be created because each field will be fetched via a call to a `DataFetcher` instance. 

And yes: For every field you don't explicitly set a `PropertyDataFetcher` is used. 

I am not sure why the explicit `DataFetcher` approach is actually slower compared to a Map in you case: in case of a Map there is this code: 

https://github.com/graphql-java/graphql-java/blob/18a4425f2f0fca1a28c8fd28abc77c88025802e1/src/main/java/graphql/schema/PropertyDataFetcher.java#L143-L145
which still does an instance of check.

A custom `DataFetcher` as described above is even simpler.

Can you provide us with more details, for example some profiler results? thanks

**Comment by bbakerman** [comment]
`PropertyDataFetcher` does indeed use reflection but be careful in thinking that reflection is always slow.

Reflection in Java has gotten progressively faster over the years and also there is a method cache in `PropertyDataFetcher` such that once it has discovered a class / method to field it does not do it again.

Only a profiler will tell you what is happening but 40,000 items of anything is a lot to process in any computer system.  Its a lot of memory in one go and a lot of processing.  I would strongly suggest looking at some sort of paging in your system.

The fact that you are using DTO pattern probably means you have a object mapping framework like Jackson / Gson in play.  This takes a lot of processing at times.   At a guess this might explain why the Map approach is faster since it wont be doing as much work.

But as Andi says above, a profiler is really thew way to go to get insight on what is taking so long.

**Comment by andimarek** [comment]
@mrubin is it possible get some profiler results or maybe to get some example app up and running?

**Comment by mrubin** [comment]
We’re going to try to create a standalone example so that we can profile it.

**Comment by bbakerman** [comment]
As a quick start to look at relative timings, I created the following dirty test program

https://gist.github.com/bbakerman/855e9f2b76ce3642efebfd655e29efcd

It creates 40,000 friends to a hero using the starwars schema with no inner friends

`{ hero { name friends { name friends { name } } } }`

It as a rudimentary warm up and then some timings

```
graphql produced 40000 objects in 870 ms


Jackson write 40000 objects in 115 ms
```

Done on 

```
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Memory:	32 GB
```

I will have a look via profiler to see more detailed information

**Comment by mrubin** [comment]
This issue does not reproduce on Java (unless you find a collection that has an O(n) `size()`), but it reproduces easily on Scala, which is what we use for our graphql server.

Java's Collections appear to have an O(1) `size()` ([see this post](https://stackoverflow.com/a/863496/1011953)), even though the [documentation for LinkedList](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html) says, "All of the operations perform as could be expected for a doubly-linked list." What's expected of a linked list is O(n) complexity to determine length :)

Something in graphql-java (see below profile and code screenshot) is calling `size()` repeatedly. When given a collection with an O(1) `size()`, this is imperceivable. However, when given a collection with an O(n) `size()` - like a Scala collection we happened to be using - this results in a great deal of overhead for 40,000 elements (`size()` called on a linked list 40,000 times?). Once we were able to identify this issue, we can address it in a number of ways - switch to a collection with an O(1) `size()`, copy the data into an `ArrayList` prior to handing it off to graphql-java, etc. With one of these workarounds, the specific data fetcher approach is indeed equivalent to (or imperceptibly faster than) the `Map` approach and allows us to continue to use our DTOs.

Thank you for the help!

![seqwrapper](https://user-images.githubusercontent.com/271245/50710778-8f972500-1031-11e9-82dd-493021dc0a11.png)

![screen shot 2019-01-03 at 8 06 28 pm](https://user-images.githubusercontent.com/271245/50710821-b6555b80-1031-11e9-904f-f3956fac8e3b.png)

**Comment by roberAlbertGlobant** [comment]
> Hi,
> 
> this is very likely caused by the [PropertyDataFetcher](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/PropertyDataFetcher.java) .
> Each field in your DTO is accessed through the PropertyDataFetcher by reflection.
> 
> As an alternative you can register specific DataFetchers for each field of `User` which takes advantage of knowing that it is actually a UserDTO.
> 
> It would look something like that:
> 
> ```java
> DataFetcher dfName = env -> {
>   UserDTO userDTO = env.getSource();
>   return userDTO.getName();
> }
> ```
> 
> This should be even faster than the Map approach.

It's seems we have similar issues, where do you exactly add these DataFetchers? 
We are using DGS Framework from Netflix and we are passing a list of DTO's as result.
If you could point to an example it would be highly appreciated. Thanks
