### ISSUE TITLE
allow coercing's parseLiteral to return null 

### ISSUE THREAD

**Issue by HenryLauu** [graphql-java/graphql-java#1362]
I am implementing a custom scalar called LocalDateTime which parse a string input to java.time.LocalDateTime. when I accept a null or empty string, I want to interpret it as a null LocalDateTime, but Coercing interface doesn't allow me to return a null value.

a possible solution is to provide a config to ScalarType

**Comment by HenryLauu** [comment]
I am implementing a custom scalar called LocalDateTime which parse a string input to java.time.LocalDateTime.  when I accept a null or empty string, I want to interpret it as a null LocalDateTime, but Coercing interface doesn't allow me to return a null value.

a possible solution  is to provide a config to ScalarType

**Comment by andimarek** [comment]
I would need to check the spec again, but I am not sure this is allowed: you will not get null as argument in a scalar, because null means null and no coercing is needed. The question is now if you are allowed to return null, and I don't think so (but I maybe wrong): A non null scalar value must result in a non null coerced value.

**Comment by andimarek** [comment]
After looking more into this issues we agree: we should allow returning `null` values from a Scalar. 

graphql-js also added it explicitly: https://github.com/graphql/graphql-js/commit/daa7759770fbe9d880ac18757b7a825ada40978b

**Comment by andimarek** [comment]
@HenryLauu do you need it for `parserLiteral` or `serialize`?
