### ISSUE TITLE
Which version of the spec/graphql-js is supported?

### ISSUE THREAD

**Issue by Globegitter** [graphql-java/graphql-java#139]
Seeing as relay is on its way to upgrade to graphql-js `0.6.0` (https://github.com/facebook/relay/pull/1118), which itself is based on https://github.com/facebook/graphql/releases/tag/April2016, which has some breaking changes, so I would assume that the backend would need to support the spec to that level.

Which version of the spec/graphql-js is currently supported? It might also be nice to add this information to the README.

**Comment by aschrijver** [comment]
I had the same question and agree compatibility should be mentioned. I have created a PR for introspection that complies with `0.5.0`. Have a look at #132 , #136 and #138

**Comment by Globegitter** [comment]
Oh sweet. Also as an example of how the go library is handling it: https://github.com/graphql-go/graphql#origin-and-current-direction

Plus in the PRs they specifically tracks the graphql-js version. Graphql for python handles it similarly.

**Comment by aschrijver** [comment]
Since #144 is now done, spec should mostly comply to `0.5.0`. If you find points where it is not, then best file separate issues for them.

**Comment by andimarek** [comment]
Closing this issue, because it is more than a year old. 

But as a general info: we are supporting (or trying to do so) the latest graphql version (Oct 2016) and some additional features (IDL, subscriptions). 

But for example `null` literal support is currently still missing, which will be added soon and we can't  be 100% sure to support all aspects of the spec, because there are no automated spec tests. (It is a manual process to read the spec and make sure we support everything)

**Comment by Globegitter** [comment]
@andimarek Yeah that is understandable. There is one community project though that tries to help with that: https://github.com/graphql-cats/graphql-cats
