### ISSUE TITLE
GraphQLTypeReferences for queries/mutations

### ISSUE THREAD

**Issue by fforw** [graphql-java/graphql-java#1402]
I had a bug in my library that was very confusing and might be interesting to fix even if you don't consider the stuff I did something people should do. I implemented a new feature and later added another test for that feature with mutations and out of the blue, in code that works fine as query, I get a very odd error message
`Validation error of type VariableTypeMismatch: Variable type 'ComplexInput' doesn't match expected type 'ComplexInput' @ 'queryTypeB', locations=[...], description='Variable type 'ComplexInput' doesn't match expected type 'ComplexInput'
`
This error message seems very confusing and it comes into being because the second ComplexInput turned out to be a GraphQLTypeReference which of course wasn't instance equal to the actual type.

Happened because I was creating GraphQL queries/mutations with GraphQLTypeReferences. Is that something I shouldn't have been doing in the first place? 

**To Reproduce**

Isolating the issue might be a bit difficult. I created a branch on my project where I sabotaged my fix to reproduce the error. https://github.com/quinscape/domainql/tree/bug-noresolve

de.quinscape.domainql.DomainQLExecutionTest#testTypeParam2 is one of the failing tests on that branch showing the error above.

**Comment by bbakerman** [comment]
> Happened because I was creating GraphQL queries/mutations with GraphQLTypeReferences. Is that something I shouldn't have been doing in the first place?

This is the correct thing to be doing..  type references are replaced with ACTUAL references when the schema is built.

We had a bug that was recently fixed in master where type references to the same place did not get replaced properly.  

https://github.com/graphql-java/graphql-java/pull/1386

I suspect this might be your problem.

I had a quick look at https://github.com/quinscape/domainql/blob/bug-noresolve/src/test/java/de/quinscape/domainql/DomainQLExecutionTest.java#L980 but I cant undeerstand the logic enough to see if its indeed the mentioned problem.

**Comment by fforw** [comment]
I tested the branch with the current grade build from master and the bug does not longer occur, so I guess it's fixed by #1386
