### ISSUE TITLE
Toggle DataLoader statistics per-execution

### ISSUE THREAD

**Issue by jhaber** [graphql-java/graphql-java#1451]
It seems like the choice to include DataLoader statistics must be made globally (or least per-`GraphQL` instance), do you think it would make sense to allow this choice at per-execution granularity? For example, we normally don't want to return statistics because it bloats the response, but for debugging we want people to be able to opt-in to seeing the statistics (we're also considering including statistics by default if the query is coming from GraphiQL, etc.).

If you agree this is useful, maybe it should be an option on `ExecutionInput` similar to `DataLoaderRegistry`?

**Comment by bbakerman** [comment]
The `GraphQL` object is nominally global however its really cheap to create one. Its the GraphqlSchema that can be expensive because of SDL parsing and so on

So you can very cheaply create a new `Graphql` via transform, which is a copy method

```
             GraphQL perRequestGraphqlObject = graphQL.transform(builder -> builder.instrumentation(..));
```

You can do this per request where you respect some debugging flags.

**Comment by jhaber** [comment]
Sounds good to me, thanks for the suggestion
