### ISSUE TITLE
Supply GraphqlFieldVisibility via ExecutionInput

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#1488]
Would it be possible to provide `GraphqlFieldVisibility` via `ExecutionInput`, similar to how most dynamic stuff is done in recent versions?
As it stands, `GraphqlFieldVisibility` is the sole remaining reason for transforming the schema (and `GraphQL`) dynamically.

**Comment by bbakerman** [comment]
Do you want one that "overrides" the `GraphqlFieldVisibility` on the schema say OR do you want to move this that its never on the schema

We use it in a couple of places where there is no `ExecutionInput` like in SchemaPrinting / Schema Construction (although thats a symptom of being on the schema) and in ValuesResolver which does not always have access to the ExecutionInput and hence GraphqlFieldVisibility would need to propogated into a lot of places

The challenge is all the places where we access a schema without handy access to the execution input for that particular request.

I am sympathetic to this request however and so is @andimarek I think.

One idea I have is to use overriding.

That is the `GraphqlSchema` object is tranformed inside the GraphQl per request and then passed on from then.

However this idea breaks some assumptions that Spring / IoC people might make around being able to inject beans into dataFetchers say and use them direct instead of getting them from DataFetcherEnv etc...

**Comment by bbakerman** [comment]
A PR showing the "rolling impact" of sucha  change might help.  It does not need to compile all the way - but it will show the size of the challenge

**Comment by andimarek** [comment]
closing this issue: we will revisit visibility completely via #1592 and #1605
