### ISSUE TITLE
Schema directives do not support EnumValue arguments

### ISSUE THREAD

**Issue by lkorth** [graphql-java/graphql-java#1500]
Schema directives currently only support built in scalars, are there any plans to add support for enums or any reason I shouldn't take a crack at adding them?

https://github.com/graphql-java/graphql-java/blob/bd9240c15fbf2eb00b2ad92b08006772e93dc387/src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java#L155-L183

**Comment by andimarek** [comment]
I don't see a reason why this should be restricted ... but @bbakerman has the full context.

**Comment by AnkBurov** [comment]
+++
Is there really a reason for that?

**Comment by andimarek** [comment]
this is a bug we will fix: directives support enum args.

**Comment by andimarek** [comment]
Closing this because directives with enum args are supported.

See this test:

https://github.com/graphql-java/graphql-java/blob/master/src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy#L2029

The mentioned code snippet is not actually used when you declare a directive. This is some old code which will be deleted soon and was meant to deal with cased where you actually don't declare your directive at all (this was before SDL was part of the official spec)
