### ISSUE TITLE
GraphQLCodeRegistry -> getDataFetcher with string args

### ISSUE THREAD

**Issue by yarinvak** [graphql-java/graphql-java#1508]
Hey,
The method ``getDataFetcher`` in the ``GraphQLCodeRegistry`` class receives ``GraphQLFieldsContainer parentType, GraphQLFieldDefinition fieldDefinition``,
but it can potentially receive only the names of the parentType and the field,
is it possible to create a method that allows it?
I need it in my library, and i do not hold the parent type in a GraphQLFieldsContainer.

**Comment by bbakerman** [comment]
The problem is that we have an interface called `graphql.schema.DataFetcherFactory` which was meant as a way for one bit of code to give out more than one DataFetcher

It has this as input `graphql.schema.DataFetcherFactoryEnvironment` which is the really just the `GraphQLFieldDefinition` 

Now as it turns out with hindsight, I now think `graphql.schema.DataFetcherFactory` is not worth it now that we have the CodeRegistry

So I would like the deprecate `DataFetcherFactory` and hence it means you could use a "parent container name string " and field "string" aka `graphql.schema.FieldCoordinates`

Thoughts @andimarek 

This would be a breaking API change.

**Comment by andimarek** [comment]
@bbakerman yes, I think we should get away from DataFetcherFactory and rather offer a better functionality centered around `CodeRegistry`

**Comment by fvilla-amazon** [comment]
When moving to graphql-java 14, I've found that if I need to deal with the code registry in a place when I don't necessarily have a graphq.schema.FieldCoordinates, it's very confusing, like I need to know too much about the internal of how graphql-java is storing data fetcher, field and parenty field relationships.  In some places, like instrumentation, I can try and get access to ExecutionStepInfo in order to drill down to the parent level and either use that to produce a FieldCoordinate or something else that I can pass to the code registry getDataFetcher method.  Here is an example of what I mean.  Given a parent ExecutionStepInfo and a field definition, I could try and produce a FieldCoordinate as follows.  I have to do a lot of checking of GraphQLTypes and casting.  This seems like it's prone to be very brittle across versions should graphql-java decide to change how it stores data fetchers.

```
    public static FieldCoordinates getFieldCoordinates(final ExecutionStepInfo parentExecutionStepInfo, final GraphQLFieldDefinition fieldDef) {
        if (null == parentExecutionStepInfo) {
            throw new IllegalArgumentException("parentExecutionStepInfo must NOT be null!");
        }
        if (null == fieldDef) {
            throw new IllegalArgumentException("fieldDef must NOT be null!");
        }

        // Find the DataFetcher
        final GraphQLOutputType outParentType = parentExecutionStepInfo.getUnwrappedNonNullType();
        String parentTypeName = null;
        if (null == outParentType) {
            return null;
        } else if (outParentType instanceof GraphQLObjectType) {
            parentTypeName = ((GraphQLObjectType) outParentType).getName();
        } else if (outParentType instanceof GraphQLList) {
            return getFieldCoordinates(parentExecutionStepInfo.getParent(), fieldDef);
        } else if (outParentType instanceof GraphQLScalarType) {
            parentTypeName = ((GraphQLScalarType) outParentType).getName();
        } else if (outParentType instanceof GraphQLTypeReference) {
            parentTypeName = ((GraphQLTypeReference) outParentType).getName();
        } else if (outParentType instanceof GraphQLUnionType) {
            parentTypeName = ((GraphQLUnionType) outParentType).getName();
        } else if (outParentType instanceof GraphQLInterfaceType) {
            parentTypeName = ((GraphQLInterfaceType) outParentType).getName();
        } else if (outParentType instanceof GraphQLFieldsContainer) {
            parentTypeName = ((GraphQLFieldsContainer) outParentType).getName();
        } else if (outParentType instanceof GraphQLCompositeType) {
            parentTypeName = ((GraphQLCompositeType) outParentType).getName();
        } else if (outParentType instanceof GraphQLEnumType) {
            parentTypeName = ((GraphQLEnumType) outParentType).getName();
        } else if (outParentType instanceof GraphQLNamedOutputType) {
            parentTypeName = ((GraphQLNamedOutputType) outParentType).getName();
        } else {
            return null;
        }

        if (StringUtils.isBlank(parentTypeName)) {
            return null;
        }

        return FieldCoordinates.coordinates(parentTypeName, fieldDef.getName());
    }
```

**Comment by bbakerman** [comment]
See `graphql.schema.GraphQLNamedSchemaElement`

**Comment by fvilla-amazon** [comment]
Thanks, I was unaware of that interface.  With your suggestion, I was able to settle on using 
GraphQLNamedOutputType in order to simplify my code.  This lends to my point though about needing to know about the internals of GraphQL Java in order to do this.  In my case, I am making use of the method below in an Instrumentation class, specifically in the beginFieldX methods, to get access to a field's DataFetcher.  This method will return the FIeldCoordinate of a field and I use that along with the field definition in order to look up the DataFetcher.  Not sure if this is the best approach but it would be great if there was a helper method for doing this in order to abstract some of the internals.  Is this something that would be worth considering as a contribution to GraphQL Java?

```
    /**
     * A helper method for retrieving {@code FieldCoordinate}s given a parent's {@code ExecutionStepInfo} and a
     * {@code GraphQLFieldDefinition}.  These {@code FieldCoordinate}s can be used to retrieve the field's
     * {@code DataFetcher} from the {@code GraphQLCodeRegistry}.
     *
     * @param parentExecutionStepInfo  The parent {@code ExecutionStepInfo} to use to retrieve the {@code FieldCoordinates}
     * @param fieldDef The field's {@code GraphQLFieldDefinition}
     * @param useAncestors {@code true} if ancestor {@code ExecutionStepInfo} should be used when direct parent is not a named type and {@code false}
     * otherwise.
     * @return  The {@code FieldCoordinates} associated with the given field's parent {@code ExecutionStepInfo} and the field's
     * {@code GraphQLFieldDefinition}
     */
    public static FieldCoordinates getFieldCoordinates(final ExecutionStepInfo parentExecutionStepInfo, final GraphQLFieldDefinition fieldDef,
        boolean useAncestors) {
        if (null == parentExecutionStepInfo) {
            throw new IllegalArgumentException("parentExecutionStepInfo must NOT be null!");
        }
        if (null == fieldDef) {
            throw new IllegalArgumentException("fieldDef must NOT be null!");
        }

        // Find the DataFetcher
        final GraphQLOutputType outParentType = parentExecutionStepInfo.getUnwrappedNonNullType();
        String parentTypeName = null;
        if (null == outParentType) {
            return null;
        } else if (outParentType instanceof GraphQLNamedOutputType) {
            parentTypeName = ((GraphQLNamedOutputType) outParentType).getName();
        } else if (useAncestors && (null != parentExecutionStepInfo.getParent())) {
            // This type does not have a name, go up to it's parent to use it's name.
            return getFieldCoordinates(parentExecutionStepInfo.getParent(), fieldDef);
        } else {
            return null;
        }

        if (StringUtils.isBlank(parentTypeName)) {
            return null;
        }

        return FieldCoordinates.coordinates(parentTypeName, fieldDef.getName());
    }
```
