### ISSUE TITLE
Need a way to get the SourceLocations of type **names**, as opposed to type declarations

### ISSUE THREAD

**Issue by rsmckinney** [graphql-java/graphql-java#1516]
**Describe the bug**
A call to `Node#getSourceLocation()` on a type or operation returns the beginning of the **declaration**, which will be a keyword such as `type` or `query`.  Instead, it would be more useful for most tools to return the location of the **name**.

As a work around I parse the declaration myself.

**Comment by bbakerman** [comment]
in order to calculate line number a character, we just use ANTLER line/column numbers as reported to us by the parser.  We think it is the most stable behaviour.

So `type foo { field    (arg : String) : String }` the token for the field is the start of the field token as you know

however we now capture "ignored" tokens in the node.  So `type    fourSpaces` will have 4 spaces as ignored tokens.  This might help you in knowing where the "names" start etc.. more systematically.

graphql.language.Node#getIgnoredChars
graphql.language.IgnoredChars

**Comment by bbakerman** [comment]
Actually that wont work for you down to the name level.  We dont expose ALL of the ANTLER tokens back into the AST node tree.

In order to get ALL of the ANTLR tokens and their EXACT positions in terms of the source you would have to implement your own replacement for `graphql.parser.GraphqlAntlrToLanguage`

That is the code curently inside `graphql.parser.Parser`

```
GraphqlLexer lexer = new GraphqlLexer(charStream);

        CommonTokenStream tokens = new CommonTokenStream(lexer);

        GraphqlParser parser = new GraphqlParser(tokens);
        parser.removeErrorListeners();
        parser.getInterpreter().setPredictionMode(PredictionMode.SLL);

        ExtendedBailStrategy bailStrategy = new ExtendedBailStrategy(multiSourceReader);
        parser.setErrorHandler(bailStrategy);

        GraphqlAntlrToLanguage toLanguage = new GraphqlAntlrToLanguage(tokens, multiSourceReader);
```

The GraphqlAntlrToLanguage gets EVERY ANTLR token and builds the AST.  It collapses certain tokens such as name and does not record where they came from.

You could (if you are determined) create your own AST that had EVERY token stored.  

Can I ask what you are doing?  For example are you writing an IDE plugin of some sort where you want to highlight specific low level tokens?

**Comment by rsmckinney** [comment]
@bbakerman thanks for the info.  The graphql-java parser is good enough for my needs.  To get the name offsets I wrote a simple parser to find the name from the type declaration start symbol; not a big deal.  However, the graphql-java parser would probably more useful for tooling if name tokens were available as part of the Node API.

I'm building a GraphQL "type manifold" for the the [Manifold](https://github.com/manifold-systems/manifold) project. Essentially this amounts to direct, type-safe GraphQL access from Java. From the perspective of the Java developer the types defined in the graphql schema files are first-class types -- _no code generation step is involved in the build_.  

Regarding the type name offsets, there is a [Manifold IntelliJ plugin](https://plugins.jetbrains.com/plugin/10057-manifold) that makes IntelliJ Manifold-aware e.g., the GraphQL schema files are magically part of IntelliJ's type system without having to write an IntelliJ plugin specifically for GraphQL and without having to compile or build anything.  Save getting too deep in the details, the Java types projected from the GraphQL type manifold are decorated with annotations to enable tools to connect the features in the types with declared features in the schema files.  For instance, you can navigate (Ctrl+B) from a graphql query type usage in Java code directly to the declaration in the schema file.  But this requires name offsets in the annotations, hence my need for name tokens.

I've just completed a Manifold release with the new GraphQL framework enabled. I'm awaiting JetBrains plugin submission process (a day or two).  Have a look if you're interested, feedback on this is appreciated.  Cheers.

**Comment by bbakerman** [comment]
For the record - today we keep the comments of a node as a `Description` object and the IgnoredSpace so we have a precedent for having extra AST data in the nodes.

I am sympathetic to adding a `graphql.language.Name` node type that is the in addition to the `String name` we have today.  Such a node would off course have SourceLocation etc..

A PR from you would of course help, however I will say that GraphqlAntlrToLanguage is not for the faint hearted.  But if ANTR is your thing, it should be ok

@andimarek - thoughts?

**Comment by bbakerman** [comment]
After speaking to Andi, one of the challenges is all the other characters such as opening braces and colons and so on


type name {
    field : String
}

These can ONLY be accessed in the ANTLR token stream and if we put the  ANTLR token stream into the graphql AST then you might as well write it direct to ANTLR

**Comment by andimarek** [comment]
closing it because answered. @rsmckinney please reopen or create new issue if something is unclear
