### ISSUE TITLE
Enum values order

### ISSUE THREAD

**Issue by zenios** [graphql-java/graphql-java#1534]
Enum values are not kept in the order of insertion but based on their name.

We are using introspection in order to fetch the possible values of an enum and show it on a select field and these issue prevents us from showing them in the order required.

[This commit](https://github.com/graphql-java/graphql-java/commit/f35dd2f0d156d577e3f5317cab5167bb4ebbaf19#diff-2bc2f9de89d5f70f03bafcb1e8296a18) is responsible for that behaviour but i cannot understand the reason behind it.**Especially for Enums**

**Comment by bbakerman** [comment]
The reason for the "canonical" ordering of fields during Introspection was to give out a canonical response.

We had feedback from others in exactly the opposite direction wanting to have a predictable system.

That said I am sympathetic to "enums" having their declaration ordering as you have outlined

**Comment by bbakerman** [comment]
See (and others ) https://github.com/graphql-java/graphql-java/issues/1314 for the original reasons

**Comment by zenios** [comment]
I am not against that but for the same reasons i have mentioned above i
think Enum should be ordered based on their declaration.

**Comment by marceloverdijk** [comment]
Related to #1496

Lately I was also working on an POC of an auto-generated UI based on the introspection query result.
For that it was also painful that everything is name ordered; fields and enums.

**Comment by arlampin** [comment]
Note about #1314 (which I reported): What we wanted was a stable output, so that running the introspection multiple times would give the fields, types, values and everything else out in the same order, unless there were actual changes to the schema. Whether this is achieved by sorting everything or e.g. keeping track of insertion order is secondary.

But I'm not sure how hard it would be to actually support insertion order for fields and types, aren't most things tracked using LinkedHashMaps internally? I remember seeing that in graphql-java's code style guidelines even. So it might be just few places that would need to be changed.

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java/pull/1546

**Comment by realityforge** [comment]
I believe this issue can be closed as the associated PR has been merged
