### ISSUE TITLE
Cross execution dataloaders not batching

### ISSUE THREAD

**Issue by jmccaull** [graphql-java/graphql-java#1537]
We have been doing batched requests through aliasing and recently switched to instead do multiple single operations within the same request. We still have our dataloaders request scoped, and the same context is supplied for each of the individual operations. Under any load (more than two operations batched together) we immediately see a large performance hit versus aliasing. We realized that despite sharing dataloaders the executions are no longer batching any of their requests together while aliasing does an ok job of batching.
If I parallelize the execution of the operations I still would expect at least some of the operations to be batched together, but until I add a break point or something to slow down dispatching that is not the case. This leads me to believe that there is a race condition between load/dispatch and the way the instrumentation handles them.
I'm looking at adding another layer to the dispatch instrumentation and possibly a way to share some state across executions to allow dispatching of batched graphql requests to at least perform as well as aliased requests. Anyone have any thought, suggestions or concerns on how to best solve this? We want to eliminate aliasing for a number of reasons, including caching, and changing our schema isn't really an option.

**Comment by bbakerman** [comment]
> We have been doing batched requests through aliasing
>Under any load (more than two operations batched together) we immediately see a large performance hit versus aliasing. 
> while aliasing does an ok job of batching.

Can you explain more about what this is.  I have no idea on what this means at all.

> If I parallelize the execution of the operations I still would expect at least some of the operations to be batched together, 

The DataLoader dispatching algorithm in graphql is very specific. 

`graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach`

Its tracks field levels and waits for all fields on the same level to be fetched (but not resolved) before it calls dispatch().  We found this the best balance between under dispatching (where things would never resolve) and over dispatching (where you call dispatch to often)

Note: You MUST be using AsyncExecutionStrategy for aggressive batching (aka field tracking) to be in place.  Are you using AsyncExecutionStrategy as your execution? 



DataLoaders MUST only ever be request specific.   NEVER share the same DataLoader instances between requests otherwise request A can cause a dispatch on request B and worse request B might never finish because of A stole its dispatch call.

You can share state via say via a custom `org.dataloader.CacheMap` implementation (that is previously completed values) but you must NEVER share the data loaders themselves

**Comment by jmccaull** [comment]
> Can you explain more about what this is. I have no idea on what this means at all.

Sorry, which part? This about covers what I mean with batching vs aliasing: https://blog.apollographql.com/batching-client-graphql-queries-a685f5bcd41b
As far as the performance, I mean that the instrumentation is able to handle aliasing fairly well but does not seem to take into consideration the other form of batching. I'm not commenting about the actual batching algorithm, I think I have a pretty good grasp of it and the limitations involved, but I do believe the functionality should be extended to work with both forms. 

> Note: You MUST be using AsyncExecutionStrategy for aggressive batching (aka field tracking) to be in place. Are you using AsyncExecutionStrategy as your execution?

Yes, we are using the kickstarter projects. Everything is wired together in a Spring boot application, It does indeed work and I've gotten it to batch together load calls from from different executions within the same request by adding a delay to the dispatch call.

> DataLoaders MUST only ever be request specific. NEVER share the same DataLoader instances between requests otherwise request A can cause a dispatch on request B and worse request B might never finish because of A stole its dispatch call.

This is where I think the instrumentation falls short. I don't think a request always lines up to an execution, at least in the context of the earlier linked article. 

> You can share state via say via a custom `org.dataloader.CacheMap` implementation (that is previously completed values) but you must NEVER share the data loaders themselves

This isn't exactly the kind of state I mean. I'm working up a pr, but my approach is going to be to along the lines of: 
Make the TrackingApproach injectable within the instrumentation via the options, create a new 
RequestScopeApproach that maintains a set of call stacks, and add the ability to set the ExecutionId within the ExecutionInput, allowing the new approach to correlate call stacks to executions. 
My only concern is that the initial state for the instrumentation is no longer created by the framework. My intent is to create the state before any executions and have it essentially consumed, requiring a new GraphQl object for each request, which we already do. The only modification to non instrumented code is the ability to set the execution id with the input. 

Are there any topics that I should go into more depth on? Is there anything I'm missing regarding the batching? Finally, any suggestions/concerns on the approach?

Thanks!

**Comment by jmccaull** [comment]
As I write/think about this pr more it seems like adding the execution id to the execution input, along with creating it earlier in the execution life cycle would allow the create state function accesses as well, meaning that the instrumentation could create/maintain the state itself as new executions are called. This wouldn't be as efficient as the previously mentioned request scope would be, but it would solve hanging dispatches. Is there a good reason something like this hasn't been implemented yet?

**Comment by jmccaull** [comment]
I still need to add some decent test cases dedicated to this use case and clean up the code a little but this seems promising so far: https://github.com/graphql-java/graphql-java/pull/1539

**Comment by jmccaull** [comment]
@bbakerman I've added two working test cases, but I'm not completely happy with the way it has turned out. A cleaner solution would be along the lines of allowing multiple operations within the execution input or adding a way to submit multiple inputs at once.  That way a single request thread could process all the calls to load. Thoughts/would you be opposed to something like this? I'm not too familiar with javascript but I get the feeling the differences in threading models is making this harder. Thanks!

**Comment by bbakerman** [comment]
The idea of taking N "operations" in a document and running them has been considered.  Other graphql servers have extensions for this.

However as I understand it they run them one after the other and combine them into the a series of results. eg a map like

```
"operations" : {
    "opNameA" : {
          "data" : { .... normal graphql results }
          "errors : { ... normal errors }
    }
    "opNameB" : {
          "data" : { .... normal graphql results }
          "errors : { ... normal errors }
    }
}
```

You seem to be asking for more.  You seem to be asking for an execution model where fields are tracked across operations and dataloader dispatches are held until N operations worth of data are done (but I might have this wrong)


Can you please outline in more basic ways what you are trying to achieve.

For example could see present a sample query and then explain in terms of it how you would expect it to execute.

**Comment by jmccaull** [comment]
> However as I understand it they run them one after the other and combine them into the a series of results. eg a map like
This is similar to what aliasing does. Aliasing itself is not generally recommended practice for batching. One drawback for example is that you can no longer cache using the query as a key due to the names not being static. To be clear, this is already supported and each alias is treated as a level 1 field. Because they are within the same operation they will generally batch together, but due to level one being dispatched immediately, this is not as efficient as it could be. Taking the example from my pr, the alias query would look like:
```
{one:query(input:1) { a } two:query(input:2) { a }}
```
where the result would come back in a map, but the errors are not distinguishable by alias, they are all in the same error map of the response. The equivalent "batched" request would look like:
```
[{query(input:1) { a }}, {query(input:2) { a }}] 
```
This is the general batched format, both Apollo(through the link extension?) and the Java Kickstart Servlet support, the results are a list of responses in the order they were received in the request. Apollo allows use of the context to be configured on a per batch or a per query basis. The java graphql servlet by default shares the context on a batch basis. 
The important difference between the formats, at least from the java perspective, is that the dataloader calls for the alias version are batched together, where the "batched" version currently has no way to coordinate this. We quickly ran into scaling issues switching to the batch version: running out of connections to the databases, thread pools thrashing etc.
I'm in no way fluent in javascript, and not very familiar with exactly how Apollo handles this, but it seems to me that this problem simply does not exist in javascript due to them using the event loop to collect batches. 
> You seem to be asking for more. You seem to be asking for an execution model where fields are tracked across operations and dataloader dispatches are held until N operations worth of data are done (but I might have this wrong)
You are not wrong, what it more or less boils down to is exactly this. I was trying to solve the problem/achieve parity without any real modifications to the existing model, it feels like a work around and hence why I said I wasn't completely happy with out it turned out.
IMO taking in N operations is by far the better way to handle this situation, I just wasn't sure that was on the table. Implementing that would completely remove the need for these changes, though I think it would still be worthwhile to clean up the instrumentation classes and leave the tracking approach injectable/configurable. I'm going to work up a new PR, where the execution input can contain multiple operations and see how that shapes up.
I hope this adequately explains the situation, please let me know if there is anything I should go into more depth on or any suggestions, concerns, comments etc. Thanks.

**Comment by bbakerman** [comment]
So part of your challenge is that ava Kickstart Servlet support is offering to take multiple operations and executing them for you.  

However the currently  graphql engine very strongly follows the graphql spec which allows N operations on the query document BUT only 1 of them to be executed per invocation. 

Because of that our concepts like "executionInput.getDataLoader()" and "ExecutionIdProvider.getId()" etc... as well as the datalaoder field tracking code all take this central premise very strongly.

It would take a significant refactor to make the code base inherently KNOW that there can be N operations at once and they should ALL be considered the same execution path.

For exmple our Instrumentation code (of which we have many) assumes that the call stream is "parse/validate/execute op A/field/field/field/final result"

But with N operations allow at once it becomes sort of 

"parse/validate/execute op A/field/field/field/mid result execute op A/field/field/field/mid result / combine results / final result"

And if we have N operations are they sequential or parallel.

There has been the idea that operations should FEED into each other so one can do OpA and then address some aspect of it in OpB (it had a go at this once - its quasi possible but really messy and breaks spec badly)

To be honest I am hesitant to accept your PR mainly around allow a pluggable field tracking approach at all.  I think you would be better to make your own CrossOperationDataLoaderInstrumentation since its really specific to a use case we dont really go after today (eg multiple operations)

Your idea to allow the "executionId" to be specified on the ExecutionInput is not a bad idea.  We could default it if its not present.  This could be a seperate PR and hence and enabler for your custom CrossOperationDataLoaderInstrumentation say.

This I would be happy to accept.

@andimarek is a lead on this project so I want him to look at this proposal and see if I am understanding it or not so please dont take this as a final word.


> I'm in no way fluent in javascript, and not very familiar with exactly how Apollo handles this, but it seems to me that this problem simply does not exist in javascript due to them using the event loop to collect batches.

For the record the JS event loop does not inherently solve the problem.  It ALL depends on how they write their code so that they give back control at a certain time.  We have run tests on JS dataloader and it can dispatch more often than is optimal but generally it gets it mostly right.  I have no idea whether Apollo multi operation is written in such a way that the run N operations at the same time and does give back control to the event loop.

**Comment by jmccaull** [comment]
Sorry, I think we need to be more explicit here about operations as we are not necessarily talking about the same thing. I don't mean operations within a single document, I really mean N full documents executed with the same context, caching and batched together. 
The servlet and Apollo both offer this and it complies with the graphql spec(ie each request has the format [{query:String, operationName: String, variables:Map<String, String>}, {query:String, operationName: String, variables:Map<String, String>},...].
My goal is not to introduce any breaking changes either, I initially tried implementing this through the exeuction input, but that didn't work out too well. I was going to try the approach of adding a BatchExecutionInput object, adding an executeAsync(BatchedExecutionInput) method and refactoring just enough that they could both use more or less the same code/instrumentation, what would be your thoughts on this?
Otherwise I'm going to add a pr for the execution id, thanks!

**Comment by jmccaull** [comment]
Here is the pr to add the id to the input: https://github.com/graphql-java/graphql-java/pull/1550
I'm hesitant to spend much time working on a "batched" method without any indication that it would be acceptable. If either of you are open to the idea I will see what I can come up with.
Thanks

**Comment by dondonz** [comment]
Hello, closing this issue as PR https://github.com/graphql-java/graphql-java/pull/1550/files was merged.
