### ISSUE TITLE
Elegant sequential DataLoaders

### ISSUE THREAD

**Issue by robcolburn** [graphql-java/graphql-java#1547]
I'd like to figure out a nice way to sequentially compose data-loaders for a given data fetcher.

Blog/Post/Comment is the canonical example, so let's use that.
* Let's say that I want to Sort by Commenter
* Let's say my backing data-store is remote key-value, and cannot perform the given sort operation.

```graphql
type Post {
    title: String
    comments(orderBy: String): Comment
}
type Comment {
    ids: String
    author: User
    body: String
}
type User {
    name: String
}
```

SchemaProvider
```java
.type("Post", wire -> wire
    .dataFetcher("comments", new CommentsByIds(e -> e.<Post>getSource().getCommentIds()))

.type("Comment", wire -> wire
    .dataFetcher("author", new UserById(e -> e.<Comment>getSource().getAuthorId()))
```

DataFetcher
```java
CompletableFuture<List<Comment>> get(DFE env) {
    // 1. Get Base Data
    CompletableFuture<List<DBComment>> commentsFuture = getDLR(env).getDataLoader("Comment")
        .loadMany(getCommentIds.apply(env));
    // 2. Apply  request sorts... but now we need to go deeper
    if (env.getArgument("orderBy") == "authorName") {
        commentsFuture = deepSort(commentsFuture, env.getArgument("orderBy"));
    }
    // 3. Model and done
    return commentsFuture.thenApply(comments ->
        comments.stream().map(Comment::ofDB).collect(toList()));
}

CompletableFuture<List<DBComment>> deepSort(CompletableFuture<List<DBComment>> commentsFuture, String orderBy) {
    return commentsFuture.thenCompose(comments -> {
        // Uh-Oh, we are invoking DL, that will need a dispatch
        CompletableFuture<List<DBComment>> result = getDLR(env).getDataLoader("User")
           .loadMany(comments.stream().map(DBComment::getAuthorId).collect(toList()))
           .thenApply(users -> {
               return comments.stream().sorted(...you get the idea...).collect(toList());
           });
        // FIX: Manual Dispatch -- oh noes, async/batching
        getDLR(env).getDataLoader("User").dispatch();
        return result;
    });
}
```

I know there will be suggestions about better data-store modelling/storage, I get it. My actual is more complicated, but I'm just trying to keep to stick to an example domain we all know & understand.

I'm trying to understand, I need to do some sequential async fetching. The fetching is already nicely wired up to DL, and I'd like to use that batching. But, I'd like to not immediately dispatch, but instead schedule for the dispatch to happen at the next opportune time as usual.

**Comment by jmccaull** [comment]
Not sure if this will be helpful, but we had a number of chained calls to data loaders. The issue is that the dispatching instrumentation assumes one load per level of the field hierarchy and has no good way to tell when more need to be called. We managed to remove a lot of manual calls to dispatch by moving some of the load calls up a level in the hierarchy. I think in that example that would mean calling load for the user DL in the data fetcher for post. We also have one or two situations where that just isn't possible and are stuck manually dispatching as well. A really cool solution would look something like a customized future builder that can accrue calls to load/dispatch etc, but I think that would be a major refactor and require making data loader a first class citizen(which I've been told has been discussed?). Otherwise posts I've seen on here regarding it say we are just stuck manually dispatching.

**Comment by bbakerman** [comment]
The challenge we have is that we want things to be async AND we want them to run late and lazy AND we want to have a happens before relationship on async dataloaders so that loadB happens after loadA but in an async fashion

For example imagine this set of fields in a query

```
query {
    products { productId }
    sales { dollars, products { productId} }
}
```

Today we field track and hence `products` and `sales` are dispatched (in dataloader terms) at the same time.  They might not complete at the same time but they are dispatched as fields at the same time because the engine does field tracking.

We know they return 1 promise (completablefuture) and the engine waits on that promise

When we chain dataloader calls we create a promise thats chained HOWEVER we also want them to be lazy so they can batch together "like" calls in the name of efficiency.  Hence the promise of the 2nd data loader call needs a "dataLoader.dispatch()" to know

However these two requirements are competing with each other.  That is happens before AND lazy batch loading.

One idea we have toyed with (but ruled out of the graphql-java engine) is a 2nd thread that "ticks" say every 20ms and combines outstanding dataloader calls.  So all dataloader calls invoked within the time window would be dispatched.  So the batching would be efficient to within the time window say.

We rule this out of the engine because one of our principles is to NEVER get involved in threading.  We run async via CompletableFuture but we NEVER start a thread in graphql-java.  If we did we would wreck the ability to run the code in Reactor / Vertex and  places where the environment is carefully controlled.

That said we would love to see some investigations of the others peoples approach to an efficient batching loading that can chain together calls.

**Comment by robcolburn** [comment]
Ya, it's not so clean, but one solution is to "cheat" a bit and look ahead. From the Post fetcher, I could say grab the comments as well, and attach to the Post object. Then from the Comments fetcher I could see that the data the comments I need are already attached to the Post object, so then I could take the time to retrieve field data like Author Users.

**Comment by bbakerman** [comment]
Looking ahead is not cheating - its often the best to optimise since your code is able to KNOW that dependent objects will be needed by looking at the query.  Optimising performance is always a trade off between code complexity (eg the lookup ahead code+prefetch code) and faster response times

**Comment by kudrevatykh** [comment]
possible solution - replace simple `dispatchAll()` from [here](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java#L290) with
```java
while(dataLoaderRegistry.getDataLoaders().stream().map(DataLoader::dispatchDepth).filter(d->d>0).findAny().isPresent()) {
  dataLoaderRegistry.dispatchAll()
}
```

**Comment by jmccaull** [comment]
I don't think I see how that would help.
I think the ideal solution would be to somehow make the framework aware of the number of dispatches required, as with a wrapper, or have it simply be able to handle nested futures and either modify the execution path accordingly or decouple that execution depth from the others. To use the example from earlier, say the data fetcher for products required two consecutive load calls, then this:
```
query {
    products { productId }
    sales { dollars, products { productId} }
}
```
would change to something like this during execution:
```
query {
    products { "second load call from products" { { productId } }
    sales { dollars, products { "second load call from products" { productId} } }
}
```
This way, instead of the second load call on products being executed alone, it would be executed with dollars and the first load from the next call to products.
Ultimately though benefits from this, aside from cleaner code for users, are going to depend heavily on query structure, and I think it is probably debatable if the complexity is worth it.
