### ISSUE TITLE
Dependency graph design

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1566]
I want to capture here some thoughts about the Dependency graph (see #1409).

One of the main challenges is the dynamic aspects of a query (type conditions). 

For exampel for this schema:
```graphql
type Query{ 
    node: Node
}
interface Animal {
    name: String
    friends: [Friend]
}

union Pet = Dog | Cat

type Friend {
    name: String
    isBirdOwner: Bool
    isCatOwner: Bool
    pets: [Pet] 
}

type Bird implements Animal {
   name: String 
   friends: [Friend]
}

type Cat implements Animal{
   name: String 
   friends: [Friend]
   breed: CatBreed 
}

type Dog implements Animal{
   name: String 
   breed: DogBreed
   friends: [Friend]
}

scalar DogBreed
scalar CatBreed
```
one can imagine this query:

```graphql
{
  node
  ... on Cat {
    friends {
      isCatOwner
      name
      pets {
        name
        ... on Cat {
          breed
        }
      }
    }
  }
  ... on Bird {
    name
    friends {
      isBirdOwner
      name
      pets {
        name
        ... on Dog {
          breed
        }
      }
    }
  }
  ... on Dog {
    name
  }
}

```

The question is now how the dependency graph should capture these dynamic type conditions. 
One possible way could be this:
<img width="1041" alt="Screen Shot 2019-06-10 at 11 15 36 am" src="https://user-images.githubusercontent.com/1706744/59166846-1c11ba80-8b71-11e9-89cc-bf488405a91b.png">

But the value of this kind of dependency graph maybe limited because it doesn't uphold to one fundamental expectation that every field is only present once.
The `/node/friends/pets/name` field is duplicated because it will only be executed if we have a `Bird` or a `Cat`, but not for a `Dog`. 

Same is true for `/node/friends/pets` and `/node/friends/name`.

The alternative could maybe look like this:
<img width="890" alt="Screen Shot 2019-06-10 at 11 34 45 am" src="https://user-images.githubusercontent.com/1706744/59167289-cb4f9100-8b73-11e9-86da-3968f5e46639.png">

It doesn't duplicate any fields anymore but now there are complex conditions associated with some nodes. For example `/node/friends/pets/breed` will only be evaluated if the original node is a `Cat` and the pet is a `Dog`.

**Comment by andimarek** [comment]
@gkesler @exbe I would appreciate your thoughts ... thanks

**Comment by gkesler** [comment]
@andimarek 
Here is yet another alternative to executing query above.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/11729102/59224720-e3c7a780-8b83-11e9-972e-df954a1f63d2.png">

For the convenience I have color coded nodes that have some condition/predicate in yellow and the nodes without conditions in blue.

The only difference between them is how their *data* is used when resolving their dependents. When these nodes are resolved, i.e. when they have all their dependencies resolved and the node had been visited, the node's data is filtered using node's predicate to use as the source to resolve dependent nodes. From this standpoint, there is no real difference in how nodes are defined, the blue nodes have fixed predicate that always returns ```true```.

Topological ordering produces a sequence in which nodes need to be evaluated. 
Here is simplified pseudo-code. I've made it in 2 nested loops for simplicity. In reality there shall be a breadth-first walk over adjacency sets of source nodes (whose dependencies have been resolved) in order to achieve the most efficiency in the query execution.
 
```java
Set<N> unresolvedSet = shallow-copy-of-graph
Set<N> resolvedSet = new HashSet<>();
while (!unresolvedSet.isEmpty()) {
   // find nodes in the unresolved set that have all their dependencies 
   // in the resolved set
   Set<N> closure = new HashSet<>();
   for (N node: unresolvedSet) {
      if (resolvedSet.containsAll(node)) {
         // node's dependencies are resolved
         // now this node can be resolved
         closure.add(node);
      }
   }

   for (Node node: closure) {
         if (!autoResolve(node)) {
            resolve(node);
         } else {
            // node is resolved automatically,
            //  i.e. it has obtained its data from its dependencies
         }

         unresolvedSet.remove(node);
         resolvedSet.add(node);
   }
}
```

Let's see how topological sorting (that's why we need dependency graph here)
1. closure: ["/node"]
- "/node" is resolved to values: [Cat("Lola"), Bird("Coco"), Dog("Molly")]
2. closure: ["/node/on Cat", "/node/on Bird", "/node/on Dog"]
- "/node/on Cat" is auto resolved to value Cat("Lola") (predicate: ```isInstanceOf("Cat")``` on [Cat("Lola"), Bird("Coco"), Dog("Molly")])
- "/node/on Bird" is auto resolved to value Bird("Coco") (predicate: ```isInstanceOf("Bird")``` on [Cat("Lola"), Bird("Coco"), Dog("Molly")])
- "/node/on Dog" is auto resolved to value Dog("Molly") (predicate: ```isInstanceOf("Dog")``` on [Cat("Lola"), Bird("Coco"), Dog("Molly")])
3. closure: ["/node/on Cat/friends", "/node/on Bird/name", "/node/on Bird/friends", "/node/on Dog/name"]
- "/node/on Cat/friends" is resolved to [Friend("Andy")]
- "/node/on Bird/name" is resolved to "Coco"
- "/node/on Bird/friends" is resolved to [Friend("Greg")]
- "/node/on Dog/name" is resolved to "Molly"
4. closure: ["/node/on Cat/friends/isCatOwner", "/node/on cat/friends/name", "/node/on Cat/friends/pets", "/node/on Bird/friends/isBirdOwner", "/node/on Bird/friends/name", "/node/on Bird/friends/pets"]
- "/node/on Cat/friends/isCatOwner" is resolved to true
- "/node/on Cat/friends/name" is resolved to "Andy"
- "/node/on Cat/friends/pets" is resolved to [Cat("Lola"), Dog("Molly")]
- "/node/on Bird/friends/isBirdOwner" is resolved to false
- "/node/on Bird/friends/name" is resolved to "Greg"
- "/node/on Bird/friends/pets" is resolved to []
5. closure: ["/node/on Cat/friends/pets/on Cat", "/node/on Bird/friends/pets/on Dog"]
- "/node/on Cat/friends/pets/on Cat" is auto resolved to Cat("Lola") (predicate: ```isInstanceOf("Cat")``` on [Cat("Lola"), Dog("Molly")])
- "/node/on Bird/friends/pets/on Dog" is auto resolved to [] (predicate: ```isInstanceOf("Dog")``` on [])
6. closure: ["/node/on Cat/friends/pets/on Cat/breed", "/nodes/on Bird/friends/pets/on Dog/breed"]
- "/node/on Cat/friends/pets/on Cat/breed" is resolved to "persian"
- "/nodes/on Bird/friends/pets/on Dog/breed" is auto resolved to null or "", does not matter.

Auto resolve mechanism allows to obtain node's result without going after the associated resolver or data fetcher, directly from the data already resolved/cached in the graph.

**Comment by gkesler** [comment]
and ah, I've forgot to answer the question about field duplication. I think by including "conditional" nodes into the graph we disambiguate what seem to be field duplications.
I would argue that in your example with ```/node/friends/pets/name``` duplication, there is no duplication at all, since the paths are different:
- ```/node/on Cat/friends/pets/name```
- ```/node/on Bird/friends/pets/name```

**Comment by exbe** [comment]
@andimarek Do you have some particular resolvers on your mind for this example?

I might be overthinking, but dependency graph with resolvers for `Dog`, `Cat` and `Bird` might look different from dependency graph with just two resolvers. One for `Animal` and another one for `Animal` with breed. Yes, I am throwing in yet another use case about query optimization. I don't have a good answer whenever generating fully-blown super generic dependency graph (to serve ALL use cases) is better than generating specialized and reduced graph which would consider runtime/execution behaviour during resolution of a given request.

Also, pardon my knowledge for GraphQ SDL, but following schema looks slightly off ([spec](https://graphql.org/learn/schema/#interfaces)). Is it or it just my misunderstanding? 

```
type Dog implements Animal{
   name: String 
   breed: DogBreed
  ///  friends: [Friend]   /// <---- must be present, isn't it?
}

```

**Comment by gkesler** [comment]
I guess I have after all slightly modified the original requirement and provided solution to the query where `node` field is resolved to array of `Animals`:) 
That's how all 3 variants come together in 1 query.

**Comment by andimarek** [comment]
@exbe you are right about the Schema, I fixed it.

**Comment by andimarek** [comment]
After giving it some thought I think we have two different dependencies: one dependency is the `source` input which means another field/node is required to be resolved before and then we have another dependency `type` which acts as predicate (similar to the yellow nodes above).

The first dependency is something that can be optimized/changed by the engine. The second dependency can't be changed because it is an external observable property, which can't be changed.

Example:

schema:
```graphql
type Query {
	issues: [Issue]
	author: [User]
}

type Issue {
	id: ID
}
type User {
	name: String
	createdIssues: [Issue] @dependOn(sourceType: "Issue")
}
```

query:
```graphql
{ issues {
	author {
	   name
   		... on User {
   			createdIssues {
	   			id
				}	
		}
	}
}}
```
This modeling allows us to do the following optimization:

<img width="926" alt="Screen Shot 2019-06-29 at 11 07 01 pm" src="https://user-images.githubusercontent.com/1706744/60384564-ae4b1580-9ac2-11e9-94be-51bb65b887ad.png">

**Comment by gkesler** [comment]
I am with you on the optimization scenarios.
Not sure I yet follow the example, perhaps because the schema and the query do not match. `Issue` type needs to have a field `author : User`, doesn't it?

Could you please elaborate how have you come up with the `createdIssues` having happens-before (source) dependency on `issues`?

I've been also thinking that expressing dependencies between fields in a form of graph would allow not only the engine to perform optimizations, but also it will let the client to optimize the execution, if for instance the pre-built dependency graph is provided as an argument to the `Instrumentation` before the execution starts, the client can optimized it according to his or her knowledge of the schema semantics.

**Comment by andimarek** [comment]
@gkesler you are right: I fixed the schema. 

The reason why `createdIssues` could only depend on `issues` is: lets imagine you query all `issues` by making one external call (DB, service, whatever). You get back a list of `issues` with each Issue having an `authorId`. 
To get an actual `author` you need to make an extra call, but you could get the list of issues for an `author` before that because you only need the `authorId`, not the full `User` object. This is why you could indicate to the engine (in the example above via  directive in the schema) that `createdIssues` only need an `Issue` as input (because it contains the `authorId`, which is all you need). Does that makes sense?

**Comment by gkesler** [comment]
@andimarek yes, it does. I just think that this is exactly a semantic aspect of the schema, without client's help we won't be able to make this kind of optimizations. Directives will certainly help. The more scenarios like this we can think of and provide directions for, the more automatic optimizations we can make without the client to modify/optimize the graph manually.

Similar scenario would be this:

1. schema
```graphql
type Query {
   company (id: ID!) : Company
}
type Company {
   id : ID
   name: String
   invoices : [Invoice]
}
type Invoice {
   id : ID
   txnDate : DateTime
   amount: Float     
} @dependsOn (sourceType : "Company", field : "id")
```

2. query
```graphql
query {
   company (id: "1") {
      name
      invoices (first: 5) {
         id
         txnDate
         amount
      }
   }
}
```

Regular and optimized queries look this way:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11729102/60425512-884b7100-9ba7-11e9-94cb-ac6a28d99b1a.png">

The regular query causes 2 sequential remote calls:
1. fetch Company by id="1"
2. fetch 5 invoices for the source Company.

In order to fetch Invoices all we need to have is foreign key to the Company, which is actually provided as the `id` argument to the `company` field. Therefore we should be able to optimize overall query performance by making these 2 remote calls in parallel. 

"green" node represents a graph node created for the argument `id`. Field `company` certainly depends on it, that argument **must** be provided with the query. Since `invoices` depends on source `company` and in particular its field `id` (foreign key), `company` argument with matching name could be used to change dependency from `invoices` -> `company` to `invoices` -> `id=1`.

**Comment by andimarek** [comment]
After giving it some more thought and actually implementing it/spiking it, I come up with a design where each node represents always a field of an object type. Fragments/type condition/field on interfaces are all resolved to fields on object types. At execution time only object types matter and which interfaces/union is implemented by which object is statically known by the schema definition.

I created also a small interactive page to play around/visualize this: https://www.graphql-analyzer.com/

**Comment by gkesler** [comment]
@andimarek absolutely, thanks!

please, let me know if I can contribute to your PR.
Are you still waiting for the DependencyGraph itself?

**Comment by andimarek** [comment]
@gkesler maybe the explanation is not really clear, what I mean is:
Whether `Dog.name`, `Dog.dogFriends` or `Cat.name` will be resolved depends on the actual type returned by `Query.pets`. If `Query.pets` contains a `Dog` then `Dog.name` and `Dog.friends` will be resolved. If it contains a `Cat`, `Cat.name` will be resolved.

On the other hand we know that `Dog.dogFriends` always returns `Dog`, so `Dog.name` will always be resolved for that (except of course null values, which is not relevant regarding conditional or not).

**Comment by gkesler** [comment]
Thanks for the quick response, @andimarek 

I think checking conditions `Dog.name` or `Cat.name` depending on the returned pet type is quite redundant, especially if they are all checked at the runtime. Imagine there are more types that implement interface `Pet` and for each of them the similar condition is checked. I think this redundancy could be removed if instead of nodes `Dog.name` and `Cat.name` there was a node `Pet.name` that would be resolved if the source type is `Pet`, which is always true in this case.

This way node `Query.pets` could have **only** two dependents:
- `Pet.name` with `always true` predicate since the source is **always** instance of interface `Pet`
- `Dog.dogFriends` with predicate that returns `true` **only** if the source is instance of type `Dog`

**Comment by andimarek** [comment]
@gkesler I made the explicit decision to only represent fields object types in the dependency graph. 

For once because at the end you have to determine the type anyway: Even if you have an Interface like `Pet` you still need to determine the object at execution time to get the `DataFetcher` from the object type. 
Also because it is overall simpler to reason about. (for humans at least)

Not saying it is perfect or it must be alway this way. I am sure there are variations of the graph, maybe depending on the use case.

**Comment by andimarek** [comment]
@gkesler as another side note: I would suggest that we close this issue and continue on the PR https://github.com/graphql-java/graphql-java/pull/1594 once it progressed a bit. Because it is kinda hard to think about all the edge cases without actual code.

**Comment by gkesler** [comment]
@andimarek 

I have no objections, let's move on.

**Comment by andimarek** [comment]
closing this now ... thanks a lot @gkesler @exbe for the valuable discussion!
