### ISSUE TITLE
Instrumentations and subscriptions

### ISSUE THREAD

**Issue by brockgibson** [graphql-java/graphql-java#1568]
Hello!

We recently added subscription support and make use of `TracingInstrumentation`. We noticed that for subscription events, the `ExecutionResult` sent to the client does not contain any tracing information as you would see for queries/mutations. This appears to be a result of `TracingInstrumentation` using `instrumentExecutionResult` to add the tracing extensions which is only ever called for the initial setup of the subscription for the `Publisher` returned from the subscription `DataFetcher`.

While this might be expected behavior, I'm curious if there is an opportunity for revising the implementation since there are no field resolution metrics for the event data items currently. Or just any thoughts you may have about what an ideal approach might be.

**Comment by bbakerman** [comment]
I think this is an oversight in implementation (and might even predate our subscription support)

Ideally we would trace BOTH the initial subscription call and the Publisher updates.

That said the code is not set up to easily do this since we would need to start a "new tracing" stateful session per `Publisher` update.  So it will take some work.

PRs are always welcome

**Comment by brockgibson** [comment]
After experimenting with this a bit more, another issue to note is that the `instrumentExecutionResult` appears to only be called for the initial subscription call. Some of the `field` related `Instrumentation` methods *seem* inconsistently called as well.

We are looking at the `SubscriptionExecutionStrategy` to see how we might fix this and will look to create a PR.

I'll update this issue with a unit test to highlight what we're observing.

**Comment by dondonz** [comment]
Closed by #1804
