### ISSUE TITLE
No validation is done on variable values

### ISSUE THREAD

**Issue by trevor-morris** [graphql-java/graphql-java#162]
If you give a literal of the wrong type as an argument then you get a validation error explaining what's wrong.

If you use the same query but tweak it to pass a value of the wrong type as a variable then you typically just get "null" as the value of the argument.

It looks like there was some intention to check variable values, see this in ValuesResolver:

``` java
        if (!isValid(type, inputValue)) {
            throw new GraphQLException("Invalid value for type");
        }
```

However the implementation of "isValid" just returns true. Even if it did something it seems a little unfriendly to throw an exception in this case, might be nicer to collect any "invalid variable" errors and return them in an ExecutionResult, as we do for query validation errors.

getVariableValues is called from ExecutionContext.build. One possible solution would be to pass in an error list to getVariableValues and accumulate any errors of this type in the list. Then, if the error list is non empty, we could add them to the ExecutionContext. Then Execution could check for this case and return early, with an ExecutionResult containing the errors, if there were any errors validating the variable values.

**Comment by andimarek** [comment]
@trevor-morris Thank you for reporting. We will look at it.

**Comment by bbakerman** [comment]
Look at the spec we have this section 👍 

http://facebook.github.io/graphql/#sec-Coercing-Variable-Values

> If the operation has defined any variables, then the values for those variables need to be coerced using the input coercion rules of variable’s declared type.

>  If a query error is encountered during input coercion of variable values, then the operation fails **without execution**.

That list bit is interesting.  The current ValueResolver.isValid() doesnt pass spec muster because it executions as execution happens.

We would need to run a pre execution step for this to be spec compliant.

This would also be an opportunity for  a pluggable "input validation" mechanism.

For example $inputName might be valid in a type sense but the value might need to be less than 255 chars  say so the pluggable interface provided by consumers will allow them to input such rules and have graphql-java facilitate it.

**Comment by bbakerman** [comment]
Covered by pluggable field validation
