### ISSUE TITLE
GraphQLTypeUtil.unwrapAll assumes it can unwrap to a GraphQLUnmodifiedType

### ISSUE THREAD

**Issue by osi** [graphql-java/graphql-java#1634]
I am using `GraphQLTypeUtil.unwrapAll` inside of a `WiringFactory`.

When called with an input value of `new GraphQLList(new GraphQLTypeReference("foo"))` it fails with `java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLUnmodifiedType`

This is on v13.0

**Comment by bbakerman** [comment]
yeah thats a case we never thought about

A schema as two stages - before type references and after they are removed and replaced with actual types.

During schema build we use type references - once we build the schema we never do

You will need to write your own unwrap I am afraid because I am not sure we can "fix" this method since by design it returns GraphQLUnmodifiedType of which GraphQLTypeReference is not one

We would need some new unwrapWithTypRefs() method

**Comment by osi** [comment]
Understood. It confused me since `unwrapOne` takes and returns `GraphQLType` whereas`unwrapAll` make the assumption about `GraphQLUnmodifiedType` even though it is repeatedly calling `unwrapOne`. 

I wrote my own, so I'm good. I feel there's an opportunity for improving the API to be less confusing, but I don't know exactly how that could be done. I'm happy with a "won't fix" for now, with this report being a crumb for others that may stumble upon it.

**Comment by andimarek** [comment]
as explained above we will not fix this atm.
