### ISSUE TITLE
customizable coercion rules for built-in scalars

### ISSUE THREAD

**Issue by dimas-b** [graphql-java/graphql-java#1665]
This is related to #865 but with a slightly different perspective.

The GraphQL spec of `June2018`, section [3.5.3](https://graphql.github.io/graphql-spec/June2018/#sec-String) states that _input_ coercion for `String` values should allow only UTF‐8 strings.

However, contrary to that spec the GraphQL java library as of version `13.0` allows `Map` values and values of other complex types to be passed to input parameters defined as `String` (see below for test code).

Comments in #865 highlights that there may be contention related to strict enforcements of the string coercion spec. In fact, even in the GraphQL library there are test cases that rely on `.toString()` coercion of _output_ values defined as `GraphQL` `String`.

Nonetheless, considering that in java string representations of `Map`, `List`, etc,. as well as user-defined classes are not well defined, it probably makes sense to provide stricter coercion logic for _input_ values so as to ensure predictability of coercion results.

**To Reproduce**
```java
package test;

import graphql.ExecutionInput;
import graphql.ExecutionResult;
import graphql.GraphQL;
import graphql.schema.GraphQLSchema;
import graphql.schema.idl.RuntimeWiring;
import graphql.schema.idl.SchemaGenerator;
import graphql.schema.idl.SchemaParser;
import graphql.schema.idl.TypeDefinitionRegistry;

import java.util.Collections;

public class GraphQLTestCoercion {
    public static void main(String[] args) {
        SchemaParser parser = new SchemaParser();
        TypeDefinitionRegistry typeDefinitionRegistry = parser.parse("" +
                "type Query {\n" +
                "  test(str: String!): String!\n" +
                "}\n"
        );
        RuntimeWiring wiring = RuntimeWiring.newRuntimeWiring().type("Query", trw ->
                trw.dataFetcher("test", env -> {
                            Object arg = env.getArgument("str");
                            return arg.getClass().toString() + ", value: " + arg;
                        }
                )).build();
        GraphQLSchema schema = new SchemaGenerator().makeExecutableSchema(typeDefinitionRegistry, wiring);
        GraphQL graphQL = GraphQL.newGraphQL(schema).build();
        ExecutionInput input = ExecutionInput.newExecutionInput().query("" +
                "query testQuery($inStr: String!) {\n" +
                "  test(str: $inStr)\n" +
                "}\n" +
                "")
                // Note: a Map object is passed for the String query input parameter
                .variables(Collections.singletonMap("inStr", Collections.singletonMap("key", "value")))
                .build();
        ExecutionResult result = graphQL.execute(input);

        System.out.println("result: " + result.getData());
    }
}
```

Output:
```
result: {test=class java.lang.String, value: {key=value}}
```

**Comment by andimarek** [comment]
The wording of the spec is not perfectly clear and doesn't really differentiate between input coercion from Ast Literals and from Runtime values. The mentioned sections talks only about literal input coercion.

Our challenge is the following: Every scalar should support the appropriate Java object as input values which can be mapped in a straightforward way. In Java the most obvious way to map arbitrary Objects to Strings is `Object.toString()`. This is why it is implemented in this way.

The alternative would have been to only support `java.lang.String` but we favored convenience  over strictness: now you can provide for example  a`DateTime` as inputs which makes absolutely sense.

We don't have a good way to distinguish between "good" `.toString()` like `DateTime` and not so great ones like `Map` and we don't want to add an arbitrary callback from inside a coercion function to user land for validation.

I could imagine we allow overriding the built-in the custom scalars so that you can implement your own stricter coercion rules matching your domain.

**Comment by dimas-b** [comment]
> I could imagine we allow overriding the built-in the custom scalars so that you can implement your own stricter coercion rules matching your domain.

Yes, this is an option, but it comes with a degree of risk and inconvenience because the code interfacing with the GraphQL library would have to deal with rather low-level aspects of it (meaning using custom types in place of standard built-in types).

**Comment by andimarek** [comment]
I don't have a good answer to that at the moment.

I changed the title of the issue and we will keep it open for now.

**Comment by dimas-b** [comment]
Yes, "customizable coercion rules for built-in scalars" would be useful. Thanks! :)
