### ISSUE TITLE
Use Markdown syntax instead of number signs for descriptions in printed GraphQL schema

### ISSUE THREAD

**Issue by phibo22** [graphql-java/graphql-java#1677]
As far as I can see it's currently not possible to print the schema with descriptions in Markdown syntax instead of number signs.

I use the ApolloGateway to compose multiple GraphQL endpoints to one. However it seems to consider only Markdown descriptions and ignore comments with number signs resulting in missing descriptions in the gateway endpoint.

The Markdown syntax for descriptions would also align with the GraphQL specification (https://graphql.github.io/graphql-spec/June2018/#sec-Descriptions).

I found this pull request which might already cover this, however I'm not sure: https://github.com/graphql-java/graphql-java/pull/1609

**Comment by bbakerman** [comment]
Yeah the SDL printer code used '# comment' based lines because it preceded the Specs triple quoted strings

That unfinished PR is an attempt to have it use triple quoted comments by default

As for ApolloGateway I am not sure HOW it prints out a remote schema??  

It may just use Introspection and descriptions only.

**Comment by phibo22** [comment]
> As for ApolloGateway I am not sure HOW it prints out a remote schema??

I'm not sure either, but I would expect that the composed schema takes on the descriptions from the remote schema.

As far as I can see your PR will be included in the next release, right? Looking forward, Thank you for your work!
