### ISSUE TITLE
Can we please have an option to ignore extra fields?

### ISSUE THREAD

**Issue by dvasconcelos1** [graphql-java/graphql-java#1707]
Currently the `graphql.execution.ValuesResolver` class throws an exception when an extra field is sent in the variables if that field is not in the schema.
```
 if (!fieldNames.contains(inputFieldName)) {
      throw new InputMapDefinesTooManyFieldsException(inputObjectType, inputFieldName);
 }
```
Can we please have a way to just ignore those fields? The current behaviour makes it too strict, too hard to handle in the client side.
I'd be happy to do a pull request to make that the default behavior (ignore extra fields).
To add an option to do that I believe would require a bit more of change.
Please let me know your thoughts

**Comment by kaqqao** [comment]
I think GraphiQL also rejects this, so this behavior might be required by the spec.

**Comment by bbakerman** [comment]
Can you outline what you mean by extra variables?

The grpahql spec says that IF you define a variable in the query operation then you MUST use it.

However if the runtime variables map contains variables not referenced then the code does not care

```
    def "test 1707"() {
        def sdl = '''
            type Query {
                hello(name : String) : String
            }
        '''

        when:
        def schema = TestUtil.schema(sdl)
        def graphql = GraphQL.newGraphQL(schema).build()
        def ei = ExecutionInput.newExecutionInput().query('query q($var1 : String) { hello(name : $var1) }')
                .variables([var1: "Brad", var2: "Ted"]).build()
        def er = graphql.execute(ei)
        then:
        er.errors.isEmpty()
    }
```

This passes

However we wrote

`query q($var1 : String, var2 : String) { hello(name : $var1) }`

then this would be invalid since the spec says you MUST use all declared variables

**Comment by andimarek** [comment]
@dvasconcelos1 I am closing this issue now: please reopen if something is still unclear after @bbakerman answer above
