### ISSUE TITLE
Sorting or modifying result based on data in child structures

### ISSUE THREAD

**Issue by MarcBridner** [graphql-java/graphql-java#1713]
Hi

I'm trying to figure out if there's a way to sort (or modify) returned data based on a field in a child structure.

Example schema:
```
type Query {
  getNode(id: ID!, sortLocale: String) : Node
}

type Node {
  id: ID
  name: String!
  childNodes: [Node]
  translations [Translation]
}

type Translation {
   locale: String!
   name: String!
}

Example query:
{
   getNode(id: "123", sortLocale: "en_US") {
     id
     name
     childNodes {
       name
       translations {
          locale
          name
       }
   }
}
```

childNodes and translations are loaded from two different backend services using DataLoaders.

The entity that contains the information for childNodes has no information about translations so I can't use a thenApply() after the data loader for childNodes is done loading, and the actual translations will be loaded in the next dispatcher level anyway.

I want to sort childNodes based on childNodes/translations/name, where childNodes/translations/locale matches sortLocale.

Currently the two options I can come up with is

1.  Instrumentation that runs when the entire query is done
1.  Look ahead on the searched fields and modify the code that loads childNodes to also load translations. I don't want to do this because this is a simplified example and in my real world it would serialize the calls between the two services instead of parallelize them.

Are there any other options?

**Comment by bbakerman** [comment]
graphql fields can be thought of as functions.

They take arguments and parent objects as input and they output data structures.  This is repeated down the tree so that the output of a parent field is part of the input of a child field.

In a pure functional programming sense, people often want to keep each field data fetcher (the function code) independent.

However in your case you are wanting to make them co-dependent - which is fine - but means you now have code that needs to be aware of each other.

You fetch childNodes and translations where `translations` is functional dependent on `childNodes` yet you want to sort `childNodes` based on the inner `translations/name`.  This creates a circular dependency. 

This means they MUST be aware of each other during fetching.  There is no way around it.

I suggest you go with option 2)  You MUST look ahead and fetch `childNode` data and their `translations` at the same time if you want to be able to sort `childNode` by the child data.

Option 1 is very complicated and not what it is intended for.

> I don't want to do this because this is a simplified example and in my real world it would serialize the calls between the two services instead of parallelize them.

You dont have much choice.  If things can run in parallel it means that their data is mutually exclusive and the output of one does not feed into the input of another.  Yet you have exactly this requirement.

Also sorting is unique - in order to sort a data set properly, you need ALL of the data in memory to sort OR you go to a DB system and get all of the data in sort order and you get parent and child data in the DB so you can sort it

```
   select * from childNodes 
      join translations where childNodes.id == translations.childNodeId
     sort by translations.name
```

**Comment by bbakerman** [comment]
See https://www.graphql-java.com/documentation/v13/fieldselection/

**Comment by bbakerman** [comment]
I am going to close this issue for now.  feel free to repoen it if this is still a problem or try the graphql-java spectrum chat
