### ISSUE TITLE
Support GraphQL types which have fields that are list of non-primitive types

### ISSUE THREAD

**Issue by stengali** [graphql-java/graphql-java#1732]

**Comment by bbakerman** [comment]
Can you please explain this problem more.  Nominally this is already supported

```
type Foo {
   name : String
}


type Bar {
    listofFooField :  [Foo]
}

```

The above is a field that has a list of non primitive types.

is that what you mean?

if not can you please explain your problem better

**Comment by stengali** [comment]
@bbakerman This was exactly the problem. We have a use case of accepting a list of non-primitive types for a mutation. I will try this nesting and see if it works.

**Comment by xma000** [comment]
I believe this is a bug in schema-building rather than in execution.

https://bitbucket.org/atlassian/atlassian-graphql-java/pull-requests/107/do-not-merge-fix-input-type/diff

**Comment by bbakerman** [comment]
I am not sure what is happening here because the explanations are terse and lack details. 

However I can see your PR has " graphql.schema.GraphQLObjectType cannot be cast to graphql.schema.GraphQLInputType"

In graphql there is clear distinction between input types and output types.  The arguments of fields (mutation and query) can ONLY take input types.  

If you build a schema (perhaps by reflective magic) that tries to re-use and output type as an input type then you will get this error.

Can you please expand the bug report / feature request to more clearly explain your problem.

Remember this is an open source project and hence non Atlassian people would not be able to see your PR probably and hence it does not help them nor does it allow them to help you

**Comment by xma000** [comment]
Let's continue the discussion in [atlassian-graphql-java](https://bitbucket.org/atlassian/atlassian-graphql-java/pull-requests/107/do-not-merge-fix-input-type). That's where I believe the problem is.
