### ISSUE TITLE
Review implementation of #1681

### ISSUE THREAD

**Issue by dimdimych** [graphql-java/graphql-java#1768]
The change introduced by the issue #1681 was too radical for us. In our project contexts serve as a "scope" for a fetcher. I.e. there's a contract that global context is not null and prior to v14 the same statement was true for the local context too. Every data fetcher if required can localize its current context (i.e. get a copy with reference to the parent context) update it and pass it to it's children. Every datafetcher uses localContext only and can seamlessly access any attribute from the local context and its parents up to the global context. In version 14 this concept does not work because localContext can be null now.  

As a simple solution I suggest to allow setting value for the top level local context in the ExecutionInput.

**Comment by andimarek** [comment]
@bbakerman your thoughts?

**Comment by dimdimych** [comment]
@bbakerman we've already implemented a work around, but as I suggested we can allow definition of the top LocalContext in ExecutionInput.Builder

**Comment by bbakerman** [comment]
I am happy to have a specific "local context" starting value.  The previous situation where we moved the global context object to the local was a wrong decision and hence it was removed.

But a seperate value makes more sense so that we don't confuse the concepts (even though they are both context).
