### ISSUE TITLE
some issue about PropertyDataFetcher

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#1829]
### 1. default value of USE_NEGATIVE_CACHE
"true" may be not friendly when class info change dynamicly.
"false" is more safely but cost a lot,but i still think security is more important than performance.

is ok to add clearNegativeCache method.

### 2. take exception as flow control
most cpu time slice cost in "NoSuceMethodException" and "NoSuceFieldException" in PropertyDataFetcherHelper for my server.
"bool" seem faster than "exception" in flow control for PropertyDataFetcher.

**Comment by bbakerman** [comment]
> "true" may be not friendly when class info change dynamically.

Dynamically changing code is a case we have decidedly tried to avoid.  Thinking less about "dynamic java code" thing about it from an graphql API point of view.   A client does introspection to know the "types and their fields".  If this changes dynamically (and a lot) then how can a client know what to select?

And if it doesn't really change a LOT then why are we optimising for that case.

Also the negative cache was introduced to cater for when people got the field wiring wrong.  We have seen cases where people declare a `foo` field only to NOT have a backing `foo` POJO property.
if they get it wrong they are not likely to know to set a "negativecache=true" to fix it.

So every request for `foo` would do all the cpu intensive searching and always return nothing.

Our experience so far is that a stable graphql API (and hence stable backing Java POJOs) is the most common use case.  So we will not be changing this.

>"bool" seem faster than "exception" in flow control for PropertyDataFetcher.

This is true and I like the `stream.filter` approach in your PR.

However since we have caching of lookups this is really marginal returns.  I am not against incorporating this code but its not urgent, the FieldNotFoundException is amortised against all fields over time.

**Comment by dugenkui03** [comment]
> 
> 
> > "true" may be not friendly when class info change dynamically.
> 
> Dynamically changing code is a case we have decidedly tried to avoid. Thinking less about "dynamic java code" thing about it from an graphql API point of view. A client does introspection to know the "types and their fields". If this changes dynamically (and a lot) then how can a client know what to select?
> 
> And if it doesn't really change a LOT then why are we optimising for that case.
> 
> Also the negative cache was introduced to cater for when people got the field wiring wrong. We have seen cases where people declare a `foo` field only to NOT have a backing `foo` POJO property.
> if they get it wrong they are not likely to know to set a "negativecache=true" to fix it.
> 
> So every request for `foo` would do all the cpu intensive searching and always return nothing.
> 
> Our experience so far is that a stable graphql API (and hence stable backing Java POJOs) is the most common use case. So we will not be changing this.
> 
> > "bool" seem faster than "exception" in flow control for PropertyDataFetcher.
> 
> This is true and I like the `stream.filter` approach in your PR.
> 
> However since we have caching of lookups this is really marginal returns. I am not against incorporating this code but its not urgent, the FieldNotFoundException is amortised against all fields over time.

Thx for explain that the reason using 'true' for USE_NEGATIVE_CACHE.The pr has been fixed for default value of USE_NEGATIVE_CACHE.

If a field is cached by FIELD_CACHE,then NoSuchMethodException(ignored,ignored2) will always be threw. the pr can be closed if its not so urgent, or reviewed if the change is valuable.

**Comment by dugenkui03** [comment]
related PR have been changed:just leave "flow-control" code in PR,remove change about "USE_NEGATIVE_CACHE”
