### ISSUE TITLE
more RuntimeWiring

### ISSUE THREAD

**Issue by HelloJavaWorld123** [graphql-java/graphql-java#1872]
what shoud i do if i have more than one RuntimeWiring???? one project  can only one RuntimeWiring??

**Comment by bbakerman** [comment]
RuntimeWiring is a builder mechanism for building the one and only runtime wiring.

However you can pass the builder (Or the `graphql.schema.idl.TypeRuntimeWiring` builders) to common functions so that you can compose them together.

I think you need to restructure your common code so that they share builders OR contribute into parts of that builders such that N components can create 1 runtime wiring.

**Comment by bbakerman** [comment]
I am closing this issue as answered
