### ISSUE TITLE
Keep GraphQLScalarType Constructor

### ISSUE THREAD

**Issue by simon-the-canadian** [graphql-java/graphql-java#1918]
Hi, the constructor on `GraphQLScalarType` is marked as deprecated. I am currently extending the class so that I can have my own scalar type with additional fields. Then in my data fetcher I can get the scalar from the `DataFetchingEnvironment` and check if the scalar is an instance of my custom scalar. Then that gives me type safety to access those additional fields. 

I am wondering if it would be possible to remove the deprecation tag or to allow extra information to be stored in a scalar through the builder interface? Such as having a generic property on `GraphQLScalarType` that could reference an optional data class.

**Comment by bbakerman** [comment]
Since all types in graphql have unique names you can use the scalar name to identify the instance.  Its not only unique amongst scalars its unique amongst ALL types such as object or enums or interfaces etc...

We should never have allowed the constructors on much of the code in graphql-java to be public since it creates SPI that we have trouble extending.

Since you also have to provide the corecing functions `graphql.schema.GraphQLScalarType#getCoercing` which is an interface you could also create a custom implementation and "cast that" to behavior that is specific to your case.
