### ISSUE TITLE
Support Apollo's automatic persisted queries

### ISSUE THREAD

**Issue by vojtapol** [graphql-java/graphql-java#1972]
This powerful feature is described here:
https://www.apollographql.com/docs/apollo-server/performance/apq/

There is very little that needs to be done by `graphql-java` to support this. The `PreparsedDocumentProvider` currently is meant to use the whole query as the cache key for the preparsed document. The cache could however also use the persisted query hash as a key. The only problem is that there is currently no good field on the `ExecutionInput` to store the hash. 

**I propose that `hash` field is added to `ExecutionInput` and that `query` is allowed to be `null` if `hash` is not-`null`.**

## Workaround
I have implemented a workaround using the the context object which works well but would prefer official support:

1. Executing query:
```java
context.hash = queryHash;
ExecutionInput executionInput = ExecutionInput.newExecutionInput()
    .query(ofNullable(query).orElse("PERSISTED")) // query is not allowed to be null, so placeholder is needed
    .context(context)
    .build();
```

2. `PreparsedDocumentProvider::get`:
```java
public PreparsedDocumentEntry get(
    ExecutionInput executionInput,
    Function<ExecutionInput, PreparsedDocumentEntry> computeFunction
) {
    GraphQLContext context = (GraphQLContext) executionInput.getContext();
    String queryHash = context.hash; // hash stored in context, but it would be better if it could be on ExecutionInput

    if (queryHash != null) {
        return cache.get(queryHash, unused -> {
            // cache miss 
            if (executionInput.getQuery().equals("PERSISTED")) {
                // we must request the full query from the clientt
                throw new GraphQLPersistedQueryNotFoundException();
            }
            // we can now parse the query and store it as a value for the hash
            return computeFunction.apply(executionInput);
        });
    }

    // for clients that do not support automatic persisted queries
    return cache.get(executionInput.getQuery(), unused -> computeFunction.apply(executionInput));
}
```

**Comment by bbakerman** [comment]
I think this is a great idea.  The design question i have is whether we want to put in API mechanisms to do this or just explain more how its done and let people roll their own.  

Why do take this approach? Apollo Server is an opinionated solution that is web server and  library all wrapped up in one.  graphql-java aims to be a low dependency library.  These are different design goals.

Anyway looking in to the Apollo solution it sends this from their Apollo client

```
{
  "extensions":{
    "persistedQuery":{
      "version":1,
      "sha256Hash":"fcf31818e50ac3e818ca4bdbc433d6ab73176f0b9d5f9d5ad17e200cdab6fba4"
    }
  }
}
```

They have made up a nice looking (but not at all standard - but in their defense there is not graphql over http standard) structure to hold their hash.

In graphql-java we dont do HTTP but we ExecutionInput does take things that map to this like the quasi standard

```
{
 "query" : "query OpName { x }"
  "variables" : { "foo" : "bar" }
   "operation" : "OpName"
}
```

So one could imagine a `Map<String,Object> ext = executionInput.getExtensions()`  on input.  This could then be a transferred from your HTTP layer (spring controller or whatever) into the ExecutionInput in a semi standard way.

From what I can tell, the Apollo Solution relies on a middleware layer to swap out the persistent hash and replace it with a  query before the gql layer gets called.  (I could be wrong here).  if we do that we provide no real value in graphql-java.  But that is an option and one way to solve this.  

A more simple way would be add a `String hash = executionInput.getQueryHash()` mechanism.  I dont like this much because it has NO use unless the `PreparsedDocumentProvider` is used.  What use does it have for every one NOT doing persisted queries?  This is why I am attracted to the `extensions` on input.

Now one thing we have today is `Object executionInput.getContext()` - this could be a`Map<String,Object>` and could be used by the `PreparsedDocumentProvider` as is - no need for a new `extensions` input mechanism.  Thoughts @andimarek ?

We would need to relax the `query must be non null` to be clean 

```
this.query = assertNotNull(query, () -> "query can't be null");
```

of course this makes the system less precise (eg one less invariant) for all those not using persistent queries.


The other question is "when the persistent query is not present in cache" how to stop the query?  The above code makes a sensible choice of throwing an exception - Should this be defined by graphql java and sent back out as  graphql errors on the ExecutionResult and not exceptions to the outer layers.  My leaning is towards this.

Finally we could provide a bare bones `PersistentQueryPreparsedDocumentProvider` that did most of these semantics.   However we would never cache anything - we aim for zero dependencues in grpahql-java so we would not choose a cache implementation - this would need to be provided via some call back so `PersistentQueryPreparsedDocumentProvider` would not work out of the box per se.

One other design question I have is WOULD the persistent cache call back ask for a query String from a hash or a `PreparsedDocumentEntry` which is also preparsed?  I think this to be honest and this is what is above.  But I call it out as a design decision.

I think IF we go with a new `input extentions` on `ExecutionInput` then we would pass the whole `ExecutionInput` to the cache callback as is - we would not try to understand specific Apollo shapes - that would be the callbacks job.  The APollo shape is clever but not a standard.  if it was standard then perhaps we would interpret it.

**Comment by bbakerman** [comment]
I have also learnt about Relay persistent queries

https://relay.dev/docs/en/persisted-queries

It of course uses a different id parameter

```
{
  "documentId": "8772b34e3486517e3c6786dd356acf0d",
  "variables": {}
}
```

It would also seem to swap in the query in a middle ware layer before passing it on the graphql code and the query is already there by the time the graphql engine gets it
