### ISSUE TITLE
Drop items with nullability issue in a list, rather than failing the whole list.

### ISSUE THREAD

**Issue by alacoste** [graphql-java/graphql-java#1977]
I found myself needing an alternative behavior to the default one in graphql-java when resolution of non-nullable fields inside of lists fail.

I would like to drop the offending items from the list and still return the "good" ones, instead of trying to null-out the whole list field itself.

I think I know how I would go about implementing this behavior. However it seems reasonable that the default should remain and this should only be an optional behavior. And so I was wondering how I should go about cleanly implementing this kind of optional setting and hoping to find some pointers here!

---------- Concrete example below ----------

Schema & query:
```
type Query {
  items: [Item!]!
}

type Item {
  value: SomeComplicatedType!
}

query {
  items {
    value {
      ...
    }
  }
}
```

Let's say that in some rare error conditions, my datafetcher for `Item.value` will throw an error.

When that happens, I get a chance to log an error nicely via an ExceptionHandler, however there's no way I can generate a reasonable "default value" of SomeComplicatedType to use in that case.

Because Item.value is non-nullable, the whole query will end up failing, and the response will look like:
```
{
  "data": null,
  "errors": [
    {...}, // The original error
    {...} // An error added by graphql-java that says "sorry I can't return null for non-nullable field Item.value"
  ]
}
```

The behavior I would prefer here is to drop the offending item in the list, but still return all the others (alongside the errors ofc).

**Comment by dzhg** [comment]
It's more like a question than an issue in `graphql-java`.

Here are 3 options based on my experience:

1. You could make the field nullable. You can filter the null value on the client side.
2. You could add a special error value for `Item.value` field. For example, add a field `error` in the type `SomeComplicatedType` to indicate it's an invalid value with error.
3. Implement a data fetcher for `items` which will look ahead and fetch `Item.value` field if it's present in the query. Then, you will have the control to handle the exception and remove the `item` with error.

I personally prefer the 2nd option. One of the use cases is, a book must have an author (`author` is a non-null field in `Book`) but in some cases, the author may not known or simply missing in the application (maybe the code would throw a `AuthorNotFoundException`). Instead of removing the book from the result or fail the entire query, I could create a special `Author` object like `Unknown` in my `Book.author` data fetcher when it catches an `AuthorNotFoundException`.

**Comment by bbakerman** [comment]
> I would like to drop the offending items from the list and still return the "good" ones, instead of trying to null-out the whole list field itself.

Do that in the resolution of the `items` field - throw away list items that are not truly complete and have all non null values.  You CANT wait for the `item.value` data fetcher to execute  - its too late

See https://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability

**Comment by alacoste** [comment]
> > I would like to drop the offending items from the list and still return the "good" ones, instead of trying to null-out the whole list field itself.
> 
> Do that in the resolution of the `items` field - throw away list items that are not truly complete and have all non null values. You CANT wait for the `item.value` data fetcher to execute - its too late
> 
> See https://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability

Ah, I didn't know that GraphQL had a precise specification for these cases already. Indeed in that case my idea goes against the spec and I won't pursue it further.

As for my specific case, my example is a bit oversimplified: the error could happen in `item.subitem.value` or any one of many sub-fields. So it's not really feasible to look-ahead and filter all problematic items during the datafetcher of items.

Seems like the best way to handle this in my situation is to make the list items nullable, i.e. `items: [Item]!` instead of `items: [Item!]!`. This way graphql-java, following the spec, will leave a null entry in the list but not crash for the rest of the items.

Thanks a lot for the precise and to-the-point answer @bbakerman !
