### ISSUE TITLE
Float's coercion should be symmetric

### ISSUE THREAD

**Issue by juriad** [graphql-java/graphql-java#1998]
**Describe the bug**

Similar to https://github.com/graphql-java/graphql-java/issues/1062.

I encountered problems with large values such as `1.7976931348623157e+309` (+308 being `Double.MAX_VALUE`). This value is parsed via `parseLiteral` in `graphql.Scalars#GraphQLFloat` to `Double.POSITIVE_INFINITY`. I expect the same problem when the value is provided via variable.

However such value *cannot be serialized back*, which is a big problem in CRUD-style applications. It does not make sense to accept a number, store it and later refuse to provide it back. That is why I ask for symmetry: either do not accept values which are coerced to infinities, or allow serialization of infinities.

When I started to dig deeper to find out what is the correct behavior, I couldn't get to a conclusion. Maybe this is indeed an issue in the specification and the bug should be filed there. What is your stance on this issue?

---

The specification (http://spec.graphql.org/June2018/#sec-Float) does not mention which floats are *valid*. But it mentions that:
> If the integer input value represents a value not representable by IEEE 754, a query error should be raised.

Moreover it allows some variability:
> Since this coercion behavior is not observable to clients of the GraphQL server, the precise rules of coercion are left to the implementation.

I assume there are the following cases:

1) all floats defined by IEEE754 (including NaN and infinities)
2) only floats which are representable by IEEE754 and definition of FloatValue (http://spec.graphql.org/June2018/#sec-Float-Value)
3) only floats which are representable by IEEE754 and the response format (often JSON)

Case 2 and 3 seems to be the same unless we admit representation of infinities/NaN by other means than numbers, which the specification even suggests:
> All GraphQL scalars are representable as strings, though depending on the response format being used, there may be a more appropriate primitive for the given scalar type, and server should use those types when appropriate.

The specification talks about data loss in Result Coercion but not in Input Coercion:
> A GraphQL server, when preparing a field of a given scalar type, must uphold the contract the scalar type describes, either by coercing the value or producing a field error if a value cannot be coerced or if coercion may result in data loss.

**To Reproduce**

For example:
```
query {
floatEcho(floatValue: 1.7976931348623157e+309)
}
```

**Comment by bbakerman** [comment]
Looking quickly into this I see that the Float scale serialisation (and parseValue - aka from variables) calls use

```
private Double convertImpl(Object input) {
            if (isNumberIsh(input)) {
                BigDecimal value;
                try {
                    value = new BigDecimal(input.toString());
                } catch (NumberFormatException e) {
                    return null;
                }
                return value.doubleValue();
            } else {
                return null;
            }
        }
```

where as the parseLiteral uses

```
 if (input instanceof IntValue) {
                return ((IntValue) input).getValue().doubleValue();
            } else if (input instanceof FloatValue) {
                return ((FloatValue) input).getValue().doubleValue();
```

The float AST element is created via

```
FloatValue.Builder floatValue = FloatValue.newFloatValue().value(new BigDecimal(ctx.FloatValue().getText()));
```

So this is weird because both use standard Java `new BigDecimal(someStr)` syntax.

Both sets of code code then called `aBigDecimal.doubleValue()`

Hmmmm

I think we would have to dig deeper in the behavior of BigDecimal + doubles

On initial appearances it would appear to be symetric (All BigDecimal.doubleValue() calls) but number systems are weird right

**Comment by fedinskiy** [comment]
Hello! 
We encountered this(and #1062) issues while working on Vert.x(https://github.com/vert-x3/vertx-web/issues/1811).
Since Infinities and NaNs are valid values under the IEEE 754, I assume that GraphQL implementations should handle them without exception.

@bbakerman as a side note: BigDecimal cannot handle NaNs and Infinities(or at least, cannot parse Strings, that contain them), see "Note" in the end of the constructor documentation: https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#BigDecimal-java.lang.String-

**Comment by dondonz** [comment]
Closing this issue after the GraphQL spec was clarified by https://github.com/graphql/graphql-spec/issues/778

https://spec.graphql.org/draft/#sec-Float
