### ISSUE TITLE
rpc api support

### ISSUE THREAD

**Issue by juliuszhang** [graphql-java/graphql-java#2024]
graphql-java export a http api by default,but now i want to export a rpc api,i have no idea about how to do this. thanks to watch my issue

**Comment by bbakerman** [comment]
actually graphql-java does not export a HTTP API by default.  The base library has not networking code in it.  Are you thinking of another library or the spring boot wrapper?

Also what is an "rpc api"?  Do you mean g-rpc?  Something else?  Its unclear what this is

**Comment by juliuszhang** [comment]
thanks for you reply,
the rpc api is g-rpc ,but the [Getting started with GraphQL Java and Spring Boot] doc is export a http api
may be i need to read document carefully and learn how to use graphql work with the rpc framework

**Comment by bbakerman** [comment]
I am not sure graphql and g-rpc ate that well connected.

g-rpc typically works by having a very tightly defined set of Protobufs
defined.  You then send messages getween systems in terms of those
protobufs.

graphql also has a strong type system and the output is driven by the input
query - eg the query asks for certain fields and the output reflects that.
And open format like json or yaml works well because the query can be
dynamic.

Not it might be possible to run some sort of graphql schema - protobuf
converter that creates a protobuf of every possible combination of the
types but I am not sure you can and I dont know of any.

Things like field aliases would make this very difficult.

**Comment by dugenkui03** [comment]
hi @juliuszhang, maybe [rejoiner](https://github.com/google/rejoiner) will help you work better.
> Generates a unified GraphQL schema from gRPC microservices and other Protobuf sources.

This artical maybe could give you some inspiration:
- [reconciling-graphql-and-thrift-at-airbnb](https://medium.com/airbnb-engineering/reconciling-graphql-and-thrift-at-airbnb-a97e8d290712)
- [artical in Chinese version：GraphQL和Thrift在Airbnb架构中的配合使用](https://zhuanlan.zhihu.com/p/47532583)

**Comment by juliuszhang** [comment]
> hi @juliuszhang, maybe [rejoiner](https://github.com/google/rejoiner) will help you work better.
> 
> > Generates a unified GraphQL schema from gRPC microservices and other Protobuf sources.
> 
> This artical maybe could give you some inspiration:
> 
> * [reconciling-graphql-and-thrift-at-airbnb](https://medium.com/airbnb-engineering/reconciling-graphql-and-thrift-at-airbnb-a97e8d290712)
> * [artical in Chinese version：GraphQL和Thrift在Airbnb架构中的配合使用](https://zhuanlan.zhihu.com/p/47532583)

thanks for your help!!!
