### ISSUE TITLE
Make IntrospectionDataFetcher extends TrivialDataFetcher

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#2040]
In most case, I think that user won't want to know the performance informance  of introspection.

It seems that `IntrospectionDataFetcher` should extends `TrivialDataFetcher`.

**Comment by bbakerman** [comment]
I agree

**Comment by davidcurrie** [comment]
I was just about to raise the same issue! I've been digging into this because we're seeing a performance degradation when using the default Apollo Client because it injects `__typename` on every field and, with the Apollo Tracing instrumentation enabled, the resulting increase in the size of the response is significant.

**Comment by dugenkui03** [comment]
@bbakerman @davidcurrie .I submit a PR for this issue, it would be grateful if you could help me review whether it is a approprite way.
