### ISSUE TITLE
Support deferred fragments

### ISSUE THREAD

**Issue by edvinerikson** [graphql-java/graphql-java#2052]
Hi @andimarek and @bbakerman 

If we were to let's say implement support for deferred fragments as outlined in the [RFC](https://www.github.com/graphql/graphql-spec/tree/master/rfcs%2FDeferStream.md), what would need to change in the codebase to support it?

Would be great to get your opinion on how it should be done. 🙂

**Comment by bbakerman** [comment]
> as outlined in the RFC in the current codebase, 

Sorry where is this request for comment on our code base?  Or is this a new graphql spec RFC?  I see no links or doc to get a background to what you are asking for

**Comment by edvinerikson** [comment]
Sorry for the confusion, I refer to the RFC in the GraphQL spec repo.  https://www.github.com/graphql/graphql-spec/tree/master/rfcs%2FDeferStream.md

I am trying to understand how the graphql-java library need to change in order to support it.


My current lead is pointing at modifying the field collector slightly to differentiate between normal and deferred selections... but it would be very helpful to have your opinion on how it should be done.

**Comment by bbakerman** [comment]
I have not read the new specification on @defer.

However we had experimental support of this in the past


https://github.com/graphql-java/graphql-java/blob/9.x/src/main/java/graphql/execution/defer/DeferSupport.java

We took this out because while potentially useful, it was not standard so
client uptake was never great.

I think elements of any new support would be like this code


The key thing we did was return Publisher<ExecutionResult> representing the
set of deferred values that could turn up

I dont think just field collector would ever be enough.  But let me read
the spec and understand the new proposals better.

**Comment by edvinerikson** [comment]
I see, I did look at the old defer implementation to gets hint of how it was done. However my conclusion was that the new proposal can't be done the same way. Mainly because the new proposal is about deferred fragments (...FragmentA @defer)  and not specific fields. Somehow we need to defer all selections in a fragment and send them in a single payload...

As I understand, the execution strategy only get expanded fields and is never aware of the actual shape of the query.. so it can't differentiate between the origin of selections.

**Comment by bbakerman** [comment]
> the execution strategy only get expanded fields and is never aware of the
actual shape of the query.

Not quite true - the DataFetcher is passed the AST elements and can in
theory know about fragments.  It uses the field collector to collapse those
into "MergedField" because the same field should only be fetched once
regardless of how many AST declarations here are.

https://www.graphql-java.com/blog/deep-dive-merged-fields/

If @defer is only allowed on a fragment (as per this spec) then yes new
work will need to be done to find the fragments.  And there will be edge
cases now because its possible to have a deferred fragment (with field X)
and just field X - do we send both?  I am guessing yes but that spec does
not really say explicitly.  (or maybe thats implied by "all the fields not
in a deferred fragment are sent on the first request)

Anyway my point is its possible but yes we will have to change some of the
field collection code ALONG with code to "enqueue" each fragment ready for
execution and to get an Publisher of deferred results.

The old work did not do @Stream - that is something not previously attacked

**Comment by edvinerikson** [comment]
>Not quite true - the DataFetcher is passed the AST elements and can in
theory know about fragments.  It uses the field collector to collapse those
into "MergedField" because the same field should only be fetched once
regardless of how many AST declarations here are.

Ok, I don't know how the data fetcher work atm, I will need to check that. 


>possible to have a deferred fragment (with field X)
and just field X - do we send both?  I am guessing yes but that spec does
not really say explicitly.  (or maybe thats implied by "all the fields not
in a deferred fragment are sent on the first request)

Yes, as I understand, fields only present in a deferred fragment will be part of a subsequent payload. If the field is present in the first response, the server won't send that field in subsequent payloads. 

However, I don't know how it should treat two deferred fragments with overlapping fields... that would lead to over-fetching (in terms of payload size) if the server doesn't remove the field from one of the payloads. 

The [spec](https://github.com/graphql/graphql-spec/pull/742/files) here might provide a better understanding of all details. We can also look at the [graphql-js changes](https://github.com/graphql/graphql-js/pull/2319).

>Anyway my point is its possible but yes we will have to change some of the
field collection code ALONG with code to "enqueue" each fragment ready for
execution and to get an Publisher of deferred results.

Yep, I was a bit tunneled visioned on how to differentiate between selections so I didn't really think about how to dispatch subsequent payloads yet. I think graphql-js uses async iterators as the public API for this.  

> The old work did not do @stream - that is something not previously attacked

Yea I haven't focused on that atm, but that's something that should be implemented too I guess. It do sound a bit more straightforward compared to deferred fragments though.

**Comment by bbakerman** [comment]
> async iterators

In our Java implementation we have chose Publisher<ExecutionResult> as our
representation of that.  We do it for subscriptions and would for proper
@defer support as well

**Comment by edvinerikson** [comment]
Makes sense to use Publisher for this too. 👍🏼

How do you think we can let the execution strategy handle the execution of deferred selections/fragments?

**Comment by bbakerman** [comment]
I suspect most of the require logic was already in our original @defer
implementation.  It basically took deferred fields (not fragments but thats
a minor detail) and took them out of the original fetch path and then
"enqueued" that field into stack to be processed after the main result was
published.

Then it simply worked on the queue of deferred work until it was done.

The new spec might call for different logic (with its labels and so on - I
haven't thought about it enough) but I can imagine it would be very similar.

The other thing to note is - is this spec likely to be accepted.  We
prematurely build @defer support based on reversing engineering and then
later aping an Apollo implementation.  But we decided to take it out
because it was not spec.  I am loathe to prematurely put it back in.

If it becomes spec, we will.  But I am loathe to get ahead of the spec here
again.

**Comment by edvinerikson** [comment]
This would be an experimental feature, enabled only behind a flag. The spec is unlikely to change unless people actually start to test it out and provide feedback. The WG is in agreement on the spec as it is right now, but still waiting for feedback from early adopters. 

That said having the support for this would really benefit my company in testing this out, as we are using graphql-java and can't rewrite it to graphql-js in order to test it out.

**Comment by edvinerikson** [comment]
I did some work on this today, started out by reverting the removal of the old defer implementation. I managed to get it working, however I'm a bit unsure about the instrumentation part, should we still call beginDeferredField, or should it perhaps be replaced with something like beginDeferredFragment and call it when we start executing that fragment?

**Comment by whytspace** [comment]
@edvinerikson any update on this?
`@defer` and `@stream` sound very promising, but we couldn't get it to work 😢
we followed this post https://github.com/graphql-java-kickstart/graphql-java-tools/discussions/324#discussioncomment-229948

**Comment by edvinerikson** [comment]
Hi, 

No I haven't worked on this for a very long time. Atm you'll need to use graphql-js if you want defer/stream support.

**Comment by whytspace** [comment]
thanks @edvinerikson. although that's bad news for us it's good to have a definite response :)

**Comment by edvinerikson** [comment]
I doubt it is of any use, but here are my changes for defer/stream. https://github.com/edvinerikson/graphql-java/commit/f8579c30cb213ad83d1d97d5641f3754f85d6afa https://github.com/edvinerikson/graphql-java/commit/bc9a50e2eb779e8c99d72f1f229de299d598813c

**Comment by pkumartv** [comment]
Hi @andimarek and @bbakerman
Any plans for support for Defer on graphql-java

**Comment by rhino88** [comment]
Is anyone working on this currently?

**Comment by dondonz** [comment]
The GraphQL Working Group is still working on the stream and defer spec. I can see an agenda item for it in one of the meetings last month: https://github.com/graphql/graphql-wg/blob/main/agendas/2023/05-May/04-wg-primary.md

As @andimarek said previously in #1767, we won't be able to implement stream/defer until the spec is finalised.

**Comment by dondonz** [comment]
We changed our mind! `@defer` was included in GraphQL Java v22.0, although the formal specification has still not been finalised.

We may implement `@stream` in the future but this is not planned yet, if it's important to you then let us know!
