### ISSUE TITLE
MultiSourceLine.getSourceAndLineFromOverallLine() generates a lot of objects

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#2210]

**Comment by bbakerman** [comment]
It has to track three things - a column, and line number and the source name that the text came from

It allocates a `SourceAndLine sourceAndLine = new SourceAndLine();` and then a ` new SourceLocation(line, column, sourceAndLine.getSourceName());` for every AST node - so 2 per AST node

How would you do it otherwise?  Move the source and col and int INTO the AST nodes themselves

**Comment by bbakerman** [comment]
SourceAndLine should have a very short life span - SourceLocation lives as long as the AST node

**Comment by dondonz** [comment]
Hello as this issue is quite old and hasn't received any extra comments lately, I'll close this issue out.

If you'd like to make a new comment please do open a new issue, thanks!
