### ISSUE TITLE
Graphiql UI

### ISSUE THREAD

**Issue by arbitdudi** [graphql-java/graphql-java#223]
This is not exactly an issue but a doubt, Is there a working graphiql interface attached with this example? If there is one that would be great. And also if some one know other graphql examples  implemented  in java please share.

**Comment by dminkovsky** [comment]
Hi @avinashdudi. Yes, we definitely could better examples of this in the README. I worked through this recently, and it wasn't too bad. Basically, you need to

1. Set up a GraphQL server. An example of this can be found here https://github.com/graphql-java/todomvc-relay-java. That example uses Spring Boot, but you can use whatever HTTP server you like to get that going.
2. Set up the GraphiQL server. That is a bit beyond the scope of this project, but basically you need to get GraphiQL talking to the server in step 1 above. It will use introspection to load the schema. 

Please post if you have specific questions about 1 or 2, please post.

**Comment by okorz001** [comment]
If you are running GraphQL in a HTTP servlet, I found it very helpful to include a GraphiQL as a static asset. Then you just need a couple lines of javascript to configure its HTTP agent and to bind the react component to a full width div. If you are really lazy you can find the bundled GraphiQL on some javascript CDNs.

**Comment by bbakerman** [comment]
I have found that https://github.com/skevy/graphiql-app is a great way to run GraphiQL standalone without needing to bundle it in your server application.

Since graphql-java supports the full meta data, this tool will query in to get it and give you auto complete etc

**Comment by dpisarenko** [comment]
> Set up the GraphiQL server. 

Can you tell, where I can learn, how to do it?

**Comment by dminkovsky** [comment]
I would look for a Docker image, if you use docker. There must be some out there that make this easy.

Otherwise, if you want to learn a bit, basically GraphiQL is a React Component. So you need to get a webpack project going that serves a React website that renders the GraphiQL React Component. You can then use the webpack dev server to serve the GraphiQL. Or you can build it and serve it with something like nginx.

**Comment by dpisarenko** [comment]
Thanks for your answer.

> I would look for a Docker image, if you use docker. 

Something like [this](https://hub.docker.com/r/merapar/graphql-browser-docker/) ?

**Comment by dpisarenko** [comment]
You can ignore my last question. I tried it out and it seems to work. Many thanks!

**Comment by dminkovsky** [comment]
Cool thanks for updating with the result. Glad to hear.

ср, 11 янв. 2017 г. в 0:51, Dmitri Pisarenko <notifications@github.com>:

**Comment by dpisarenko** [comment]
@dminkovsky There is an cross-site scripting (XSS) problem, when I try to run this locally. I've described the problem on [StackOverflow](http://stackoverflow.com/questions/41589542/why-does-my-spring-controller-not-handle-an-options-request-sent-by-graphiql) -- you are welcome to answer it and get 200 StackOverflow points of reputation (bounty).

**Comment by dminkovsky** [comment]
I'm sorry if I didn't read carefully enough but from what I saw—isn't it
just CORS configuration? which is what your one existing answer on SO says
too, right?

пт, 13 янв. 2017 г. в 11:28, Dmitri Pisarenko <notifications@github.com>:

**Comment by dminkovsky** [comment]
Yeah I just looked at the screenshot in your SO question. Your GraphQL is
on a different host than your front end (the ports are different). You need
to set up a proper response to that OPTIONS request. It needs to return the
appropriate Allow- headers. Check out CORS.

пт, 13 янв. 2017 г. в 12:15, Dmitry Minkovsky <dminkovsky@gmail.com>:

**Comment by dminkovsky** [comment]
Oops I meant Access-Control- headers

пт, 13 янв. 2017 г. в 12:35, Dmitry Minkovsky <dminkovsky@gmail.com>:

**Comment by dpisarenko** [comment]
@dminkovsky It probably is CORS. I already configure it in my Java application, but there are probably errors. I've updated my SO question so that now it includes code fragments that show, how exactly I configure CORS.

**Comment by dminkovsky** [comment]
It's definitely CORS. But I'm sorry I don't know much about Spring.
Sometimes allowed origin can't be * but has to be a specific host. That
could be your problem but I'm just speculating.

Sorry you're spending so much time on CORS but it's everywhere you can't
get by without it.

сб, 14 янв. 2017 г. в 6:00, Dmitri Pisarenko <notifications@github.com>:

@dminkovsky <https://github.com/dminkovsky> It probably is CORS. I already
configure it in my Java application, but there are probably errors. I've
updated my SO question so that now it includes code fragments that show,
how exactly I configure CORS.




—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/graphql-java/graphql-java/issues/223#issuecomment-272617036>,
or mute the thread

**Comment by bbakerman** [comment]
This is not a capability that the core graphql-java library provides so I will close this issue
