### ISSUE TITLE
Store Arguments as a Map in Field instead of a List

### ISSUE THREAD

**Issue by metacosm** [graphql-java/graphql-java#226]
The spec explicitly state that arguments are named and order is irrelevant so it doesn't seem like there are any benefits to use a List to access a Field's Arguments instead of a Map. An added benefit would be to make it simpler to deal with Arguments in DataFetchers.

**Comment by dminkovsky** [comment]
Hi @metacosm. Thanks for posting this issue.

> The spec explicitly state that arguments are named and order is irrelevant so it doesn't seem like there are any benefits to use a List to access a Field's Arguments instead of a Map.

The spec is really important to us, but I don't think the spec is relevant to this implementation detail. What would be the benefits of using a `Map`?

> An added benefit would be to make it simpler to deal with Arguments in DataFetchers.

What could be simpler than what we already have, which is

    <T> T env.getArgument(String name)

You don't even have to cast :)

**Comment by metacosm** [comment]
Hi @dminkovsky,

Maybe I'm not using the API correctly but in my use case, I iterate over fields and retrieve arguments from the fields. In this case, the only way I have to retrieve the field's arguments is via `Field.getArguments()` which is not really helpful at all. It'd be useful to have the same `<T> T getArgument(String name)` method we have on DataFetchingEnvironment on Field as well.

**Comment by dminkovsky** [comment]
> I iterate over fields 

When do you iterate over fields? Inside a `DataFetcher`? If so, are you saying you look at the `List<Field>` that can be retrieved via `DataFetchingEnvironment#getFields()`? And then want to see that the argument values these fields have?

>  It'd be useful to have the same <T> T getArgument(String name) method we have on DataFetchingEnvironment on Field as well.

So a `Field` does not have proper runtime argument values in its own right. `Field` is an AST node, so it might have a literal argument value or a variable reference. When a particular field is being resolved during a query execution, its arguments are [normalized to an actual value](https://github.com/graphql-java/graphql-java/blob/v2.1.0/src/main/java/graphql/execution/ExecutionStrategy.java#L27). It is this value that you can retrieve from the `DataFetchingEnvrionment`. So if you are retrieving a list of fields using `DataFetchingEnvrionment#getFields()` as mentioned above, each of these fields' arguments must be normalized to get their actual useful runtime values.

**Comment by metacosm** [comment]
> When do you iterate over fields? Inside a DataFetcher? If so, are you saying you look at the List<Field> that can be retrieved via DataFetchingEnvironment#getFields()? And then want to see that the argument values these fields have?

Yes. In my code (which might be going about solving the issue I'm facing the wrong way), `DataFetchingEnvironment#getArguments` returns an empty Map while I do have Fields with arguments and associated values (which are what I expect them to be, maybe out of pure luck or because I'm dealing with Strings so far).

> When a particular field is being resolved during a query execution, its arguments are normalized to an actual value.

I may be missing something but the `ValuesResolver.getArgumentsValues` method is converting the arguments list into a Map (even a linked one, not sure why since order is not supposed to be significant for arguments) and it seemed to me that it was a common occurrence in the code that the arguments list was converted to a Map. My point is that I still don't understand why the arguments have to be stored as a List when they are more usefully manipulated as Map (as even the implementation seems to denote).

**Comment by dminkovsky** [comment]
> `DataFetchingEnvironment#getArguments` returns an empty Map while I do have Fields with arguments and associated values.

`DataFetchingEnvironment#getArguments()` returns resolved argument values for the field your data fetcher is currently handling. By "resolved argument values" I mean that before the data fetcher was executed, the `Field` AST node was examined and its argument values were parsed from either literal values in the AST node, OR from variable references in the AST node. Either way, the values returned by `#getArguments()` and related methods are parsed. 

In your code, however, you examine `List<Field>` and use the argument values directly from the `Field` AST node, like `StringValue`. You can do that, but that's not "correct" in the sense that you may have a variable reference. `StringValue`, like all AST value nodes, are "raw" and need to be resolved into runtime values. That is what the `ValueResolver` does.

> I still don't understand why the arguments have to be stored as a List when they are more usefully manipulated as Map

I can't emphasize enough that `List<Field>` is a list of GraphQL AST nodes, and its arguments are also a bare list of GraphQL AST nodes. These AST nodes are the result of parsing the query. The order of arguments in the `Field`'s arguments list is the order in which the parser saw them. But, as I've said a few times, these `Argument`s are not the arguments you should be using. As you've said, they are more useful as a map, which is what the `ValueResolver` does: it takes the raw AST nodes, the argument schemas, and variable values, and combines those three things into that useful Map.

**Comment by dminkovsky** [comment]
Let me summarize:

The `Argument` list in a `Field` is not mean to be used directly during execution. This argument list must first be processed. See `ValueResolver`. `StringValue`, for example, is a GraphQL query string value. It is not a `GraphQLString` or a Java `String`. Rather, a `StringValue` is parsed by a `GraphQLScalar`'s `Coercing` depending on the type of scalar. That scalar could be any type of scalar. It doesn't have to be a Java `String`.

So, do not use unresolved AST values as arguments. They are not a "useful" list because they are not meant to be used in that way. They are a list because they are the product of linear parsing.

**Comment by dminkovsky** [comment]
One more thing:

> returns an empty Map while I do have Fields with arguments and associated values

If `getArguments()` returns an empty map, then the arguments on the `Field`s in `List<Field>`s will be empty. Each `Field` in `List<Field`> will have the same arguments and values. The only difference might be their selection sets, which is why that list of fields is provided.

**Comment by metacosm** [comment]
OK, I think I understand more the issue now. Thank you.
One last question: why does `ValuesResolver` put the arguments in a `LinkedHashMap`, though? It would seem like this is unnecessary as the order of arguments is not meaningful.

**Comment by dminkovsky** [comment]
Hey you're welcome. I'm glad you got something out of it. I kept reading over my answer(s) and they were not great...

> why does ValuesResolver put the arguments in a LinkedHashMap, though?

That I am not sure about. I didn't write that detail in the implementation. The spec does say that ["arguments are unordered"](http://facebook.github.io/graphql/#sec-Language.Arguments). However, while I am no JVM expert, I doubt this adds much overhead, so I would not prioritize changing it to `HashMap`. Right now our biggest performance issue is probably [input validation](https://github.com/graphql-java/graphql-java/issues/170).


---

I know you didn't ask about this, but if I may offer some more unsolicited insight as an attempt to re-phrase my answers above:

(1) Regarding `List<Field>` as available from `DataFetchingEnvironment#getFields()`:

This list is the ordered set of `Field` ASTs for the `Field` that is currently being fetched. It is a `List` because a field may be repeated in a selection set, and a field that is defined as an object may be repeated with different selection sets.

I believe the main reason `List<Field>` is exposed in the `DataFetchingEnvironment` is to allow you to optimize remote data fetching. For example, suppose you have a table `People` in some remote SQL database and the following query:

```
query {
  person(id: "1") {
    name
    address
    phone
  }
  person(id: "1") {
    age
  }
}
```

When you are fetching data for field `person(id: "1")`, you may not want to retrieve the entire row for that entity but only the fields requested in the GraphQL query. So in the data fetcher for `person(id: "1")`, you iterate over each `Field` in `List<Field>`. There will be two `Field`s in this list: one for the first `person(id: "1")` field, and one for the second `person(id: "1")` field. Each of these will have its own selection set (the first will include "name", "address" and "phone"; the second will include "age"). So then in your data fetcher you can request `SELECT name, address, phone, age FROM People where id=1` instead of `SELECT * FROM ...`.

By the way, the equivalent in the JS implementation is called [fieldASTs](https://github.com/graphql/graphql-js/blob/v0.7.2/src/type/definition.js#L491).

---

(2) The GraphQL **query** language only defines several scalar literal types that might exist in a query: `Int`, `Float`, `Boolean`, `String`. These 4 scalar types are different from the data definition scalar schema types, which are use-definable and exist at execution/runtime by parsing one of the four above mentioned query language scalars.
