### ISSUE TITLE
Duplicated Fields in SelectionSet

### ISSUE THREAD

**Issue by fforw** [graphql-java/graphql-java#2303]
So we have a GraphQL library based on graphql-java and I was just updating that to graphql-java 16.2 and came on a strange bug

```java
final List<SelectedField> rowsField = env.getSelectionSet()
    .getFields("rows");

if (rowsField.size() == 0)
{
    return Collections.emptyList();
}

final Set<SelectedField> fields = new LinkedHashSet<>(
    rowsField.get(0)
        .getSelectionSet()
        .getFields()
);
```
This is the code that works now. The LinkedHashSet is a quick solution to the fact that the list I get from the final getFields() has all fields duplicated. Every field exists twice in that list with identical field objects.

I can't see why that ever should be the case.

---
Not really sure how to reduce it to a minimal test case, but lots of reproducible follow-up errors are in [this branch](https://github.com/quinscape/automaton/tree/bug-dupfields)

A bunch of SQL mocking tests fail, e.g. https://github.com/quinscape/automaton/blob/bug-dupfields/src/test/java/de/quinscape/automaton/runtime/data/InteractiveQueryConditionTest.java

See last commit on that branch for the location.

**Comment by josephlbarnett** [comment]
can use `getImmediateFields()` instead of `getFields()` per #2275

**Comment by fforw** [comment]
I don't just want the immediate fields. I want all of them below "rows", including the object fields. This way I'm also getting them  relative to "rows" which is convenient for my purpose.

**Comment by bbakerman** [comment]
Because of type resolvers, the actual fields that are present can be

See https://www.graphql-java.com/blog/deep-dive-merged-fields/

```
interface Pet {
   name : String
}

type Dog implements Pet {
   name : String
}

type Cat implements Pet {
   name : String
}
```

```
query {
    pets {
       ...on Dog {
         name
       }
      ... on Cat {
        name
      }
    }
}
```

in 16 and above we actually have a selection set with `Dog.name` and `Cat.name` possible.

I am going to close this issue because we are pretty sure its the expected results (surprising but expected) and also because we are pretty sure we have this right after a LOT of work in this area.

BUT if it still is a bug, feel free to re-open this issue BUT with lots more issue setup (schema + test) to show a bug

**Comment by bbakerman** [comment]
This has been fixed.  Sorry for thinking it wasnt really a problem - we got it wrong in that regard
