### ISSUE TITLE
Line comment ignored if block comment is ahead of line comment

### ISSUE THREAD

**Issue by linux-china** [graphql-java/graphql-java#2390]
I want to add both line comment and block comment for type.  If block comment is ahead of line comment, and line comment will be ignored and `definition.getComments()` will return null. Code as following: 

```graphql
""" Project type """
# @Table("s_projects")
type Project  {
}
```

But if line comment is ahead of block comment, and line comment will be kept, and following code is good. 

```graphql
# @Table("s_projects")
""" Project type """
type Project  {
}
```

Is it a bug or requirement from GraphQL specification?

**Comment by bbakerman** [comment]
So its a quirk rather than a bug

Early graphql specs never specified what a comment is versus a description on a field

So in the earliest days `# some text` was considered botha  comment and it could feed into a description

Laste spec versions defined what a description is - its  single or triple quoted string in front of element

```
"single string"
type X {
}

""""
  triple quoted
  multi line string
"""
type X {
}
```

So we have `element.getComments()` now and we also have 'element.getDescription`

but honestly now that `# comments` are not syntactically relevant any more we should have removed `.getComments` but we never did because if legacy.  Hence the confusion.

https://spec.graphql.org/June2018/#Comment

> Comments behave like white space and may appear after any token, or before a line terminator, and have no significance to the semantic meaning of a GraphQL Document


So we kinda of still capture comments because of legacy but they are no longer meant to be a thing
