### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by weebl2000** [graphql-java/graphql-java#24]
I really like using graphql, but I am really struggling with this implementation because there is so little javadoc. For example, how should I define my own types with coerce() and coerceLiteral() methods? I can only gather so much information from the code itself.

**Comment by andimarek** [comment]
I'm sorry to hear that so much is unclear.
But you're right: To really understand the details you have to read the source code.

I can't really promise anything when the documentation will be improved: I'm doing this is my free time and my resources are limited. 

But thanks for raising awareness.

Tip: This is a more or less direct port the graphql JavaScript Implementation. So nearly every concept and some documentation about it can be found in [here](https://github.com/graphql/graphql-js) and [here](http://facebook.github.io/graphql).

Again: I'm sorry that I can't give you a better answer at this time. Feel free to open a new Issue for specific questions.

Best regards,
Andi

**Comment by andimarek** [comment]
I will let this Issue be open, as long as the documentation isnt't improved.

**Comment by danielkwinsor** [comment]
Would you accept pull requests of javadoc that others write?  I might want to write some javadoc myself, to aid my learning and perhaps any developers using this.

**Comment by andimarek** [comment]
Yes, of course. Thanks for your help.

**Comment by andimarek** [comment]
@danielkwinsor about your last comment in #89:  
My personal philosophy for source code comments is very puristic: I add rarely javadoc comments. For example I don't think adding author infos is useful (use git for getting the history of the file)
Instead I try to make the source code as readable as possible plus adding tests, which also document whats going on.

I also differentiate between public classed and private implementation details: I think the javadoc for public classes should be improved (e.g. the `GraphQL` or `Relay` class). On the other hand implementation details should not be documented in the same way. Because they are subject to change and if you really want to know whats going on you should read the source-code.

**Comment by danielkwinsor** [comment]
I won't add author fields.  How about version?

When I develop something, I want to use my IDE to use context-assist and to read the javadoc, thereby figuring out from the API what is possible.  That workflow doesn't work here, instead I go to the Readme.md and to tests.
One feedback I have is that, for a given feature, it can be hard to look for example usage in the tests when the schema and groovy test are split among differently named files.  I do understand the background here of Garfield and Star Wars, I'm just saying.
The readme.md does a decent job, and is probably up-to-date except for missing 2 scalar types.  But to dive deep into the things that DataFetchingEnvironment provides, and what env.getSource means and how that is different from env.getParentType and what happens when I call env.getArgument on something that doesn't exist... all those things I have to now dive into the code for.
Let me put it a different way.  Everyone knows what an Enum and an Interface is, no matter what language, and you just have to learn the syntax.  In GraphQL it should be straightforward to write unit tests around my code using these constructs, but in graphql-java I cannot find these things and I find myself reverse engineering this from readme, tests, and code, which is a very slow process.

**Comment by andimarek** [comment]
@danielkwinsor Thanks for your feedback. 

I agree that some things are currently hard to understand and also that the documentation should be improved.
The current state of the documentation is simply the result of this being a private project, where I invest my free time. 
This means I depend on others to improve the current situation:

So maybe you could create a PR to extend the README to answer exactly the questions which were hard to answer for yourself? That would be totally awesome.

Thanks!

**Comment by danielkwinsor** [comment]
@andimarek Yes, I would like to help with that, as I get free time myself.

**Comment by yrashk** [comment]
Considering that not all the javadoc is done yet, can we split this issue to specific issues that cover *specific* missing javadoc coverage?

**Comment by aschrijver** [comment]
@yrashk That is not needed, I think. This is a common library public API methods should have JavaDoc documentation. For most of these this will be very minimal, as it corresponds one-to-one to the GraphQL spec that people can RTFM. So one-liners like `Gets the name of the field definition.` would suffice.

Examples where JavaDoc comments are vital are in the `Object` parameters of `DataFetchingEnvironment` and other locations where it is unclear which types you can expect in the parameter.

I might have a stab at creating a PR for this, but I have to find the time as well. Will let you know beforehand.
If creating additional issues, a TravisCI task for generating Github Pages output and adding to `gh-pages` branch and that is reference from the README would be nice. I'll create that issue.

**Comment by andimarek** [comment]
we improved the overall documentation including javadoc quite a bit since this issue was created. 
Therefore I am closing it for now.

Please feel free to open specifc Issues for missing or unclear documentation.

Thanks
