### ISSUE TITLE
NodeVisitorWithTypeTracking#visitValue broken for default variables of type list.

### ISSUE THREAD

**Issue by ishita-sharma** [graphql-java/graphql-java#2401]
The current implementation of NodeVisitorWithTypeTracking#visitValue is unable to parse a default argument of type list and throws a NullPointerException at NodeVisitorWithTypeTracking.java:245.

Trying to traverse a query with default variables as a list thus leads to an exception. 
query ($name: [String!] = ["Bauman"]") {...}

**Comment by bbakerman** [comment]
This needs to be confirmed and fixed

**Comment by dondonz** [comment]
Hi @ishita-sharma, thanks for reporting the issue.

A recent PR fixed default variables as a list. Could you please have a look at these 2 test cases and let me know if they are similar to your issue? https://github.com/graphql-java/graphql-java/pull/2337/files#diff-fc26bb89d079dba9e6b4c224c816ba38e54b4b764da7dcc9f77dacc023a93f31 

If this reflects your issue, then the fix is in the latest master and will be included in v17.0.

**Comment by ishita-sharma** [comment]
Hi @dondonz, 
I looked at the test cases and they do cover the issue I reported. 
Thank you for the fix.
