### ISSUE TITLE
Setting code registry's default data fetcher breaks schema introspection.

### ISSUE THREAD

**Issue by aklish** [graphql-java/graphql-java#2493]
**Describe the bug**
This is using GraphQL v16.2:

Introspection.java defines all of the data fetchers for the schema introspection types.  Unfortunately, it doesn't define a data fetcher for "__Field.type" which defaults to using the PropertyDataFetcher (as the default).

If you set the default data fetcher in the code registry, schema introspection will resolve "__Field.type" with the new default fetcher.

**To Reproduce**
A query like:
```
__type(name: "Author") {
  name
  fields {
    name
    type { // <-- This has no introspection fetcher defined and will leverage the default fetcher.
      name
    }
  }
}
```

Will fail if you configure the default data fetcher:

```java
       GraphQLSchema schema = GraphQLSchema.newSchema()
           ...
          .codeRegistry(GraphQLCodeRegistry.newCodeRegistry().defaultDataFetcher((unused) -> dataFetcher)
          .build();
```

**Comment by aklish** [comment]
Also, attempting to work around this by setting the data fetcher for "__Field.type" using `codeRegistry.systemDataFetcher(coordinates("__Field", "type"), dataFetcher))` does not work.

**Comment by bbakerman** [comment]
> If you set the default data fetcher in the code registry, schema introspection will resolve "__Field.type" with the new default fetcher.

Sorry but its working as designed - the default data fetcher is the DataFecther of last resort.

If you chose to put in a default data fetcher then it MUST emulate the behavior of the PropertyDataFetcher(which is the defaulted default)

That is it must do most of the POJO getter magic etc..  In fact it's more complicated than people think, because PropertyDataFetcher caches class methods and other tricks.  Have a look at the code.

Every field in a  schema MUST have a DataFectcher - and PropertyDataFecher is a great default.

Out of interest, why do you want to have your own default data fetcher - what behaviors do you want?

Can you not "delegate" to a PropertyDataFetcher?

**Comment by aklish** [comment]
A few thoughts:  

- First off - great & useful project.  Thank you for building this.
- I'm not sure how new the code registry is (I'm upgrading from v6) but it could use more documentation for how to use a custom fetcher.  I found it less intuitive than simply setting the data fetcher for every field in v6.
- I would expect data fetching for metadata (likely static information) and data (dynamic and much more likely to require customization) to be a bit more compartmentalized.   The codeRegistry interface gives that impression (with dataFetcher and systemDataFetcher methods).  Maybe there should be separate default fetchers.
- My use case is that I need to override the fetcher for every field excluding the schema.  Default seemed like a good way to do that.  I wasn't expecting the resulting  behavior for schemas to break (thankfully caught by some tests).  I had to workaround by setting the fetcher for every field explicitly.

To answer your question, our data fetcher is plugging into an existing system with its own model driven API for fetching each and every field.  A single custom fetcher is what we use to accomplish this.

Thanks!
