### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by khat33b** [graphql-java/graphql-java#2502]
**Describe the bug**
The documentation is outdated and it cannot be used to write learn the library and write code with it.

**To Reproduce**
For example, 
here: https://www.graphql-java.com/documentation/v17/getting-started/ , this line in Hellow World throws error:
```
RuntimeWiring runtimeWiring = newRuntimeWiring()
                .type("Query", builder -> builder.dataFetcher("hello", new StaticDataFetcher("world")))
                .build();
```

And this https://github.com/graphql-java/graphql-java/blob/master/src/test/java/HelloWorld.java hasn't been updated in 4 years.

**Comment by bbakerman** [comment]
graphql-java is an open source library, not a commercial enterprise

No one works full time on this, even thought 100s of hours are dedicated to it.

We rely on the good will will our users to improve things.  

Feel free to make PRs to https://github.com/graphql-java/graphql-java-page to improve the documentation.

In the meantime 1000s of others seem to be able to get started, despite the less than perfect documentation.

**Comment by khat33b** [comment]
@bbakerman True but you should at least update the Hello World program and other basic stuff otherwise how will someone who has never used your library even get started on using it?

**Comment by bbakerman** [comment]
Honestly I am not sure of your problem.

The HelloWorld in our tests compiles, works and prints `{hello=world}`

It hasn't changed in 4 years because this library started in 2015 and has been remarkably stable and successful.

>  True but you should at least update the Hello World program and other basic stuff

Your tone here has remarkable levels of entitlement to it.  You are dismissing our efforts as if we haven't even bothered to produce a decent code base.

Like I said, all contributions to this library are voluntary and 1000s of hours have been put into it so others can benefit.  That is what open source projects often involve.

I do get disappointed by the tone of some of the worlds consumers, and this is one of those cases.  So be it, there are 1000s of others how appreciate this work.

**Comment by khat33b** [comment]
I managed to fix the error so I am closing this issue.

I never claimed you didn't produce a decent codebase. You are reading things into my comment which do not exist. It was simply a rebuttal of you telling me, a beginner to the library, to write the documentation myself which was very dismissive. Documentation writing can only be done by the developers and people who have used the code for a long time.
