### ISSUE TITLE
graphql.schema.DataFetchingEnvironment can be an interface

### ISSUE THREAD

**Issue by Jimexist** [graphql-java/graphql-java#260]
So that it is easier for mocking.

Glad to provide a PR if needed.

**Comment by dminkovsky** [comment]
That sounds good to me. Thank you!

**Comment by bbakerman** [comment]
Can I make another suggestion... it should generic as well.

        public DataFetcher exampleFetcher() {
        return environment -> {
            GraphContext context = (GraphContext) environment.getContext();
            return supplierMethodCall(context);
        };
    }

With no generics we have the above.  The ACTUAL return type is Object so its hard to maintain.  But the shape of fetched objects are really important.

Where as

    public DataFetcher<FooObject> exampleFetcher() {
        return environment -> {
            GraphContext context = (GraphContext) environment.getContext();
            return supplierMethodCall(context);
        };
    }

Tells a maintainer what they need to know.  It must return a FooObject and hence so must the method call etc..

In fact this could be applied to a number of places in GraphQL Java.  I think I may raise another issue to cover this specifically rather than hijack this isssue

**Comment by Jimexist** [comment]
@bbakerman i agree with you but i would go ahead and make my PR smaller - maybe your idea is better implemented in another PR.

**Comment by dminkovsky** [comment]
Fixed in #301. Thank you @Jimexist!
