### ISSUE TITLE
Weird versions in java central make it impossible to find the correct version to upgrade to

### ISSUE THREAD

**Issue by haster** [graphql-java/graphql-java#2628]
If you have a general question or seeking advice how to use something please create a new topic in our GitHub discussions forum: https://github.com/graphql-java/graphql-java/discussions. Thanks.

The exact same issue as #2427 

In that issue you seem to imply you are deploying snapshot versions to maven central with this 0.0.0 version number to work around some other tool's auto-update checker.

However, those versions break maven's own version parsing and are reported as _newer_ than existing versions. 

For example, this is what 
```
mvn versions:display-dependency-updates
```

shows for a pom with dependencies on graphql-java:17.2 and java-dataloader:3.1.0

```
[INFO]   com.graphql-java:graphql-java ............ 17.2 -> 230521-nf-execution
[INFO]   com.graphql-java:java-dataloader ...
[INFO]                                     3.1.0 -> 2021-10-29T01-57-17-4253050
```

As you can see, that makes it unworkable. 

And checking maven central manually is also unworkable due to the massive number of snapshot versions there. These versions are namely also not detected as snapshot versions by maven central, so not merged but kept as separate releases.

Could you switch to a x.y.z-SNAPSHOT scheme for snapshot versions, and deploy them to maven central as snapshots so maven can filter those out automatically?

Preferably you would deploy those snapshots to some internal maven repo server so the rest of the world doesn't have to sort through those snapshots, but I don't know if that is possible for you.

**Comment by MeanManMachineMan** [comment]
I'm facing the same issue as well. I'm trying to get a poc for graphql with java done and this is honestly blocking me.

**Comment by bbakerman** [comment]
We came to this version naming strategy after a number of goes to help
accommodate various groups and also ensure we are making available via
maven the latest code.

> These versions are namely also not detected as snapshot versions by maven
central, so not merged but kept as separate releases.

That's intentional.

> Preferably you would deploy those snapshots to some internal maven repo
server so the rest of the world doesn't have to sort through those
snapshots, but I don't know if that is possible for you.

This is the opposite of what we are trying to achieve, which is to say that
each merge to master has a maven central available build.


> this is honestly blocking me

How so in concrete terms?  I  can see that it may annoy you for auto
updates., say but actually blocking you?

**Comment by andimarek** [comment]
FYI: we maintain the authoritative list of releases as Github releases: https://github.com/graphql-java/graphql-java/releases

This includes also breaking changes etc. Imho you should never just upgrade based on maven central available artifacts, but always look up the release notes. We had maven artifacts being broken for example.

We also don't release so often: maybe 2-3 times per year major versions and maybe some minor updates.

**Comment by haster** [comment]
@bbakerman 
> > this is honestly blocking me
> How so in concrete terms? I can see that it may annoy you for auto updates., say but actually blocking you?

It's blocking us from moving to a newer version if it's too much work to find out what the newer version is. 

There's a reason we use the mvn versions plugin to manage the list of available updates: we have a ton of dependencies and we don't want to spend too much time on each dependency. Having to spend too much time on a dependency can lead to us not updating or moving to another dependency that fulfills the same need.

@andimarek 
> FYI: we maintain the authoritative list of releases as Github releases: https://github.com/graphql-java/graphql-java/releases
> 
> This includes also breaking changes etc. Imho you should never just upgrade based on maven central available artifacts, but always look up the release notes. We had maven artifacts being broken for example.

This sounds like you're saying you don't do semver and any release could contain breaking changes. Which would not be what we expect.

We don't just upgrade to the latest major version, since that could realistically include breaking changes, but we do see an upgrade to the latest patch version (within a set major.minor) as safe, and an upgrade to the latest minor version (within a set major version) as reasonably safe. 

Does that not apply to graphql-java?

**Comment by bbakerman** [comment]
> This sounds like you're saying you don't do semver and any release could contain breaking changes. Which would not be what we expect.

We don't do semver.  We mostly release major versions only and breaking changes (while minimised) happen as they happen.

It is unfortunate that our "master" release naming does not work for you but we will be continuing with it so I am going to close this issue.

**Comment by Ekryd** [comment]
Sorry for posting in an old issue, but I have recently started to use Renovate to keep track of dependency updates.
Most updates for plugins and Maven dependencies have been fine, but the update for graphql-java want me to update to version `230521-nf-execution`, which is not a stable release (right?). 
I believe that your choice to not use the standard `-SNAPSHOT` scheme makes it harder for us that is using your library.

**Comment by dondonz** [comment]
Hello @Ekryd, regarding `230521-nf-execution`, that version shouldn't have been released with that name but unfortunately it is not possible to remove versions from Maven. I tried to delete it, but it's part of their policy to not delete any versions after they have been published for stability reasons.

We don't use the snapshot scheme because we do have users who want to use the latest build versions in production. For example at work in my team we usually use the latest master build version. Our master build versions are always prefaced with `0.0.0`, hopefully you are able to create a rule in Renovate to ignore the build versions.

**Comment by Ekryd** [comment]
Hi @dondonz!
A release with a bad name can happen to anyone (I have done it myself, as well). Perhaps there is some central way of indicating that a release was less-than-perfect?

I do not agree on you decision of not using snapshot scheme. Organizations, companies and individuals are using Dependabot and similar software to manage dependency updates, and requiring each and every user of your framework to make special solutions is not the way forward. You are using Dependabot yourselves in this repo, and I assume that you wouldn't want to make special configurations or decisions for each dependency that you are using. Even more so if each dependency developer had their own scheme which they thought would be best for a select group of users.
I kindly ask that you standardise your non-stable versions according to Maven best practices.

You mentioned that you are using the latest build in production and I think that is perfectly fine, but in that case you should make a configuration in that project so that it allows you to use a snapshot version. Because that decision is taken in your team that you want to use non-stable builds, it should not affect this framework.

I don't mean to be rude in any way and I'm glad that you put in continuous effort in graphql-java. I think that you are doing a tremendous work by maintaining this library.

**Comment by bbakerman** [comment]
We are against `<vernum>-SNAPSHOT` for the simple reason that they are not stable.

 `graphql-java:21-SNAPSHOT` is a moving target.  Today `graphql-java:21-SNAPSHOT` could be some code, tomorrow `graphql-java:21-SNAPSHOT` can be different code, sometimes very different.

We want to have a continuous release stream of master builds that can be addressed by teams if they so choose - We use this extensively in Atlassian as a consumer of graphql-java latest versions.

Now I will grant you that tooling like Renovate is becoming table stakes in software development and we moved to the `0.0.0-{date}-{githash}` version numbering to try and get out of the way of these tools based on other peoples feedback. eg `0.0.0-2021-05-04T21-12-03-d3ac10b0`

I wonder if we adopted a numbering like `0.0.0-2021-05-04T21-12-03-d3ac10b0-SNAPSHOT` would such tooling just ignore it?

On the one hand if its fixed tooling hiccups in something like Renovate - then great - only the other hand it MIGHT appear to signal that `0.0.0-2021-05-04T21-12-03-d3ac10b0-SNAPHOT` is a snapshot version that can change - BUT it is not - its a specific release.

So we might fix one issue with tooling and send a poor signal on these continuous releases.

**Comment by dondonz** [comment]
@Ekryd and no worries, I didn't take it to be rude, you're simply putting forward your issue.

If you think of some other way we can help Renovate identify master builds, we're open to ideas.

**Comment by Ekryd** [comment]
🤔 You are right that SNAPSHOT means two things: both that it is a non-stable version and that it can actually return different code given that same version number.
For the fun of it, I went to Maven central (central.sonatype.com) and did a search for `graphql-java`. You had 83 pages * 12 entries of versions, which is unfortunate for those that try to find the correct version to use. Version `21.0` vas on page 45.

I would ask the question: Is it really super important that your master builds are always code-stable? (returning the same code)
I would put the version handling priority something like this:
1. Keep fewer stable versions released in Maven Central.
Focus on newcomers that will have an easier job finding correct newest version.
Focus on corporate usage that want to find a stable version quickly (for instance, in our company it is discouraged to use non-stable builds).
Use the three number version number in order to facilitating minor upgrades (such as upgrading dependencies for security reasons). Do not make a new minor release just for each dependency update, but group then together over a period in that case.
Skip any kind of date in your versioning schema, as the the date can be found out from other sources.

2. Make the master build a snapshot version with the standard three number naming scheme.
Upside is that the number of versions is reduced, thus providing clearer overview of what you can select from.
Downside is that code functionality is not guaranteed if you use snapshot versions. Code stability is good, but do anyone really care about a non-stable build after 9 months?

OR

2. (alt b) Publish you master build versions in a separate maven repository and expose that repo externally.
Upside is that the number of official versions is reduced, thus providing clearer overview of what you can select from.
Downside is maintenance cost, but perhaps that can be shared among the organisations that need this functionality

This will lead to two things. Projects that rely on snapshot versions will sometimes have their code break (which sucks, I know), but a new snapshot version can be quickly created to un-break the code. This will probably occur more often during a period when you are developing new major functionality which is not completely done yet.
You will likely have a few more minor version updates due to dependency updates, but that is ok.

The biggest problem with this are all the versions that you have accumulated over the years. I would suggest a brutal solution; change the framework name (appending a number or something similar `graphql-java2`).
As you said before, the version `230521-nf-execution` will otherwise always haunt you. I personally would be a bit sad if users discard your framework, just because they are using the wrong version.

**Comment by Ekryd** [comment]
An whatever you do, please do not put a year or date into the new name 😄
