### ISSUE TITLE
Able to use non input type as input type when wrapped in GraphQLList

### ISSUE THREAD

**Issue by CNAChino** [graphql-java/graphql-java#2656]
**Describe the bug**
The issue occurs when using `GraphQLArgument` builder with type as GraphQLList(an instance of GraphQLInputType) and wraps a non-input type like GraphQLObjectType.

Was also able to build a schema as shown in the following code.

**To Reproduce**
```
GraphQLObjectType graphQLObjectType = GraphQLObjectType.newObject().name("ObjectTypeA").build();

    GraphQLArgument argument = GraphQLArgument.newArgument()
        .name("testArg")
        .type(GraphQLList.list(graphQLObjectType))
        .build();

    GraphQLObjectType queryObject = GraphQLObjectType.newObject()
        .name("Query")
        .field(GraphQLFieldDefinition.newFieldDefinition()
            .name("testField")
            .argument(argument)
            .type(graphQLObjectType)
            .build())
        .build();

    GraphQLSchema schema = GraphQLSchema.newSchema()
        .query(queryObject)
        .additionalTypes(Collections.emptySet())
        .additionalDirectives(Collections.emptySet())
        .build();
```

**Comment by bbakerman** [comment]
Thanks for report - yup I can see this can be a bug because a list is both an input type and output type and its not until you put it into a context (argument or field) that you know if its incorrect or not.

Type references could also create this problem.

We could write an extra schema validation rule to catch this - that is once the schema is finalised - we would unwrap every argument / field and make sure the wrapped types are valid for the context.

**Comment by bbakerman** [comment]
The linked PR has addressed this
