### ISSUE TITLE
Would it be possible to create a MaxNodesInstrumentation and add it to graphql-java?

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-java#2682]
GitHub has a nice Nodes limit restriction per query as documented here:
https://docs.github.com/en/graphql/overview/resource-limitations

I wonder if it is possible to create such an instrumentation in `graphql-java` and if could be interesting to add it to this project alongside the max query and max depth instrumentations?

**Comment by bbakerman** [comment]
The challenge with such a thing is what to do with it when you exceed the nodes - blow up?

Also if you using the GitHub limits as inspiration, they require interpretation of `first / last` of Connection pattern and the graphql-java raw engine is not suited this application specific convention.

I think it WOULD be possible to write such an instrumentation but depending on how it was done - it needs to be very generic otherwise it would not get included in the main lib.  We have already have internal debates on whether  max query and max depth instrumentations should be in the base lib and not in some other "extend-intrumentations" lib
