### ISSUE TITLE
Null assertion error when a  null Locale is set into Validation code

### ISSUE THREAD

**Issue by softprops** [graphql-java/graphql-java#2907]
**Describe the bug**

I'm writing this down as a note but will fill in more information has it comes.

I've just upgraded from 18.2 to 19.0 and am not experiencing a number of errors that look like I'm getting a ton of errors of the form 

```
    => graphql.AssertException: Object required to be not null
       graphql.Assert.assertNotNull(Assert.java:31)
       graphql.i18n.I18n.<init>(I18n.java:37)
       graphql.i18n.I18n.i18n(I18n.java:46)
       graphql.validation.Validator.validateDocument(Validator.java:68)
       graphql.ParseAndValidate.validate(ParseAndValidate.java:111)
       graphql.GraphQL.validate(GraphQL.java:628)
       graphql.GraphQL.parseAndValidate(GraphQL.java:591)
       graphql.GraphQL.lambda$parseValidateAndExecute$10(GraphQL.java:555)
       graphql.execution.preparsed.NoOpPreparsedDocumentProvider.getDocument(NoOpPreparsedDocumentProvider.java:15)
       graphql.execution.preparsed.PreparsedDocumentProvider.getDocumentAsync(PreparsedDocumentProvider.java:4
```

looking through the changelog this most likely relates to https://github.com/graphql-java/graphql-java/pull/2878

it looks like this is failing on a null locale -- https://github.com/graphql-java/graphql-java/blob/35ff68db1e1d567428539d74f2169ca7799ee2a3/src/main/java/graphql/i18n/I18n.java#L37

**To Reproduce**

Please provide a code example or even better a test to reproduce the bug.

**Comment by softprops** [comment]
I think the problem lie here with `executionInput.getLocale()` which may be null

https://github.com/graphql-java/graphql-java/blob/35ff68db1e1d567428539d74f2169ca7799ee2a3/src/main/java/graphql/GraphQL.java#L628

**Comment by bbakerman** [comment]
Yeah the problem here is the locale is indeed nul..

`ExecutionInput` was indeed changed to default it during its builder `private Locale locale = Locale.getDefault();` but its possible for a caller to have set it to null (perhaps through calling some other method like `customCode.getLocale()` returning null.

We need to default this at the call site.

As a work around until this gets fixed, people seeing this should ensure that a non null `Locale` is set into their `ExecutionInput`
