### ISSUE TITLE
Introspection on default value for input object is not following GraphQL spec

### ISSUE THREAD

**Issue by rayngwf** [graphql-java/graphql-java#296]
I defined an input object with a `HashMap` as default value. Introspection on the default value gives the `toString()` value of the `HashMap` (see `graphql.introspection#__InputValue`). However, [GraphQL specification](http://facebook.github.io/graphql/#sec-The-__InputValue-Type) requires the string to be encoded using GraphQL language.

As a result, GraphiQL would fail because of the incorrect introspection result.

**Comment by dminkovsky** [comment]
Thank you for the report! 

Here's a failing test: https://github.com/graphql-java/graphql-java/pull/297/files#diff-79600ba7380fb4f5a886ef11a5cc3aba

**Comment by bbakerman** [comment]
Can you leave a code snippet to help with verification and unit testing any fix please

**Comment by dminkovsky** [comment]
Hi. Please check out #297.

чт, 12 янв. 2017 г. в 19:58, bbakerman <notifications@github.com>:

**Comment by bbakerman** [comment]
I looked into this further.  It does today do the wrong thing but the expected result linked here is not correct I don't think

The spec says is should be a field called "defautValue" and a graphql language encoded "String representation".

Looking at the reference implementation they do this

https://github.com/graphql/graphql-js/blob/master/src/type/introspection.js

     resolve: inputVal => isInvalid(inputVal.defaultValue) ?
        null :
        print(astFromValue(inputVal.defaultValue, inputVal.type))

This takes the input default value object and the logical graphql type and reverse runs it back though AST and then an AST printer.

We dont yet have an AST printer

There is a PR : https://github.com/graphql-java/graphql-java/pull/386 that provides a runtime type printer.  But not a printer of AST values

The AST vales in graphql-java are represented by classes such as graphql.language.IntValue and graphql.language.StringValue etc..

In order to fix this to spec we would have to write a AST printer and then reimplement the astFromValue method mentioned above.

I will see if I can get this done
