### ISSUE TITLE
[Feature Request] Get missing/incorrect field names for validation errors

### ISSUE THREAD

**Issue by christianrowlands** [graphql-java/graphql-java#2964]
I originally created an issue [here](https://github.com/spring-projects/spring-graphql/issues/487), but was directed to this project. The linked issue contains a lot of details surrounding this feature request, but I will provide an overview here:

I am looking to return a custom error message when a field is missing from a request. Right now, I am seeing something like the following returned when the `name` field is missing:

```json
{
    "errors": [
        {
            "message": "Variable 'myVariable' has an invalid value: Field 'name' has coerced Null value for NonNull type 'String!'",
            "locations": [
                {
                    "line": 1,
                    "column": 21
                }
            ],
            "extensions": {
                "classification": "ValidationError"
            }
        }
    ]
}
```

This does provide the relevant information for someone experienced with GraphQL because it mentioned the field `name` is a `String!`. However, I would like to return a simplified message such as "The `name` field is required in the `MyInputObject` when making the mutation someMutationCall", or something like that.

I found that the source of this error message is `graphql.execution.NonNullableValueCoercedAsNullException`, and I can intercept this error as mentioned in the linked ticket. However, once I intercept the error the only way to get the field name is the parse the `getMessage()` String and extract the field name. This is not ideal and I am hoping get the missing/invalid field name from the `GraphQLError` object.

Let me know if there are any questions.

**Comment by bbakerman** [comment]
This is tricky one to fix.  Because the code involved does not always know the path to the offending field.

Sometimes it does know the path to it but there are other cases where it does not.

We can perhaps fix it for the good path.

Each `GraphqlError` has a path attribute - which is meant to be the path to the field in the query `foo/bar`

However in this case (via the ValueResolver coercion code) its always set to emptyList().  We would need to pass through the field path context into these methods.  And thats the tricky part.
