### ISSUE TITLE
GraphQLContext class can not be extends

### ISSUE THREAD

**Issue by aihua5** [graphql-java/graphql-java#2970]
**Describe the bug**
When I try to upgrade the graphql-java lib from 16.2 to 19.1, I find that we need to extends GraphQLContext, but the class constructor is private which cannot be extended.

**To Reproduce**
Now we must use deprecated method ExecutionInput.context()

Could you change the GraphQLContext constructor to public to let the client can extend it? Thanks

**Comment by bbakerman** [comment]
The class is designed to be not extendable.  Its a glorified map by design.

You should move from a `is a` interitence model to a `has a` composition model.

So take the behaviors and properties you wanted in a derived class and create your own `CustomContextState` class and then put that into the GraphqlContext via a class key.

```
ExecutionInput.newExecutionInput().graphQLContext( builder -> builder.put(CustomContextState.class, new CustomContextState(...))
```

**Comment by aihua5** [comment]
thanks. It makes sense, I will follow your instructions.
