### ISSUE TITLE
Consider moving to Java 11 and support java.util.concurrent.Flow APIs

### ISSUE THREAD

**Issue by jponge** [graphql-java/graphql-java#3043]
This is a feature request to move to Java 11 as a baseline instead of Java 8 (2014), and support ` java.util.concurrent.Flow` APIs.

 ` java.util.concurrent.Flow` was introduced in Java 9 (2017) as a modern _Reactive Streams_ API, but this project still uses the legacy `org.reactivestreams` APIs.

Note that while the `org.reactivestreams` APIs are still compiled for Java 6 (2006), a new major release of `graphql-java` could easily support both `org.reactivestreams` and ` java.util.concurrent.Flow` APIs in a transition period.

Thank you

**Comment by jponge** [comment]
`org.reactivestreams` types did make sense in a pre-Java 9 world, but since they are now built-in the JDK it's one less dependency to carry around.

See https://www.reactive-streams.org/ and https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck-flow for why `Flow` types shall be where the ecosystem goes.

**Comment by softprops** [comment]
I’d prefer leaning towards the std library for interface types. It means I can use grapghql java without a compile time dependency on an external library when the std library would do just fine

**Comment by bbakerman** [comment]
The latest master is now based on Java 11

https://www.graphql-java.com/blog/java-11-required

As for Flow - we will NOT be getting rid of Reactive Streams `Publisher` and have `Flow` only - we cant - it would break every one out there who already rely on a `Publisher` being the "input" to a stream of subscriptions.

We do aim to have near zero dependencies in graphql-java but we can't get rid of the reactive streams dependency because it breaks people for low value.

So we would need to accept `Flow` and `Publisher`.

We had feedback from the Spring team that they would also prefer this approach - all their code is based on `Publisher` and not `Flow`

Honestly from a personal point of view, I never see `Flow` referenced in any code I encounter - maybe I am just not working in the right places - but `Flow` strikes me as dead on arrival.  Great idea in theory but practically how useful is it.

However we could do work to accept it as an input.

We do put a wrapper on the `Publisher` today for sub selection - that is the base `Publisher` gets accepted and a sub selection ``Publisher` wraps it and that is what is given out in the `ExecutionResult`

If we had `Flow` support, we would need to do the same.

**Comment by bbakerman** [comment]
Closing this 

We are moving to Java 11 but we wont be using Flow

**Comment by bbakerman** [comment]
BTW the latest graphql-java supports Flow in query / mutation data fetcher returned objects.  

And while subscriptions still need to return a reactive-streams `Publisher` a Flow based system can use `org.reactivestreams.FlowAdapters#toPublisher` to turn a Flow event stream into a reactive one very easily

**Comment by hantsy** [comment]
> Honestly from a personal point of view, I never see Flow referenced in any code I encounter - maybe I am just not working in the right places - but Flow strikes me as dead on arrival. Great idea in theory but practically how useful is it.

[Smallyrye Munity](https://smallrye.io/smallrye-mutiny/latest/) used Jdk Flow, then Quakrus reactive stack will use it.

**Comment by bbakerman** [comment]
> Honestly from a personal point of view, I never see Flow referenced in any code I encounter - maybe I am just not working in the right places - but Flow strikes me as dead on arrival. Great idea in theory but practically how useful is it.

I am coloured by the fact that reactive-streams is 11 years old and rxjava is even older.  So for much of that time - Flow was a good idea but no one was really using it.  Its great that Smallrye is now using it - which started in 2019.

But Flow is not dominant nor has it taken over the reactive world.

As I said we do now accept a `Flow` publisher back from a DataFecther and with some work we could auto convert them for subscriptions if we got one back.

But we would continue to present a reactive-streams API based on the fact

* we cany break compatibility
* reactive-streams (via reactor) still seems to be the most widely used
* and there is adaptors for Flow from reactive-streams anyway

**Comment by hantsy** [comment]
> I am coloured by the fact that reactive-streams is 11 years old and rxjava is even older.

The early RxJava 1 does not support Reactvie Streams standard, RxJava2(partially, not sure now, not used it for years) and RxJava3 supports Reactive streams, Reactor also implemented Reactive Streams in v3, it was just earlier one or two years than SmallyRye Mutiny (before SmalleRye project was born, RedHat started a WildFly Swarm project, Smallrye is the successor). 

Of course, the early RxJava/Reactor affects the progress of standardizing Reactive Streams.

> As I said we do now accept a Flow publisher back from a DataFecther and with some work we could auto convert them for subscriptions if we got one back.

Spring WebFlux depends on Reactor, but internally it uses [ReactiveAdapterRegistry](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/ReactiveAdapterRegistry.html) to support `RxJava2/RxJava3`, `Smallrye Mutiny`, `Kotlin Coroutines`, etc. As the end users/developers we can use any of these freely in a Spring WebFlux application. If none of these exist in class path, Spring WebFlux also supports Flow as fallback.

RxJava3/Reactor adopts reactive using reactivestreams before it is part of JDK 9, it is reasonable. I wish GraphQl Java consider Flow because it is already in JDK for a long time (the newest JDK is JDK 24). 


> But Flow is not dominant nor has it taken over the reactive world.

I do not know the use cases from other Java developers, from my view Flow/Smallrye Mutiny almost covers 50% use cases. Furthermore, I rarely use RxJava 3 now. Besides Micronaut/Spring WebFlux, I have not used Reactor in projects. For other cases, such as Microprofile (and Jakarta EE spec also try to integrate Flow tightly, the new Concurrency spec supports managed Flow Subscriber/Processor), Quarkus, Resteasy Reactive, Hibernate Reactive, etc. they are all related to Flow/Smallerye Mutiny.

For the projects new to adopt reactive, accepting Flow is the trend.

**Comment by hantsy** [comment]
@bclozel I just share my personal opinions. I am sorry if it makes you feel uncomfortable. I just don’t agree with some opinions, such as： 

> Flow was a good idea but no one was really using it. Its great that Smallrye is now using > it - which started in 2019.
> But Flow is not dominant nor has it taken over the reactive world.

Spring is great, but I think Quarkus(which uses Smallrye Mutiny, finally uses Flow) is equally good. And Quarkus has a large user base as I know. "no one was really using it" is really not the truth.

**Comment by jponge** [comment]
The support of `Flow.Publisher` is indeed a step in the good direction 👍 

The fact that `Publisher` is still the returned reactive type is easily mitigated by using (~no-cost) adapters.

Hopefully one day people will realize that dropping the legacy reactive streams API is not that difficult (we did it with almost no impact on end users). Happy to discuss it somewhere else.

**Comment by hantsy** [comment]
I would like to reverse the position of ReactiveSteams and Flow, and use Flow API to replace the current Reactive streams API. And then make reactivestrams-java optional. Of course, the current codes are acceptable.

**Comment by bbakerman** [comment]
https://github.com/graphql-java/graphql-java/pull/3910

This allows you to return a Flow.Publisher in the inside subscription data fetcher.

However for all the reasons stated above, the ExecutionResult `Publisher` returned will be a reactive streams one.
