### ISSUE TITLE
Directives support?

### ISSUE THREAD

**Issue by scf37** [graphql-java/graphql-java#307]
Official spec is pretty vague but I believe current implementation is incorrect:
```
 graphQL.execute("@skipme{hello}") //InvalidSyntaxError
 graphQL.execute("@skipme(){hello}") //InvalidSyntaxError
 graphQL.execute("{@skipme hello}") //InvalidSyntaxError
 graphQL.execute("{@skipme() hello}") //InvalidSyntaxError
 graphQL.execute("{hello @skipme}") //ValidationError, UnknownDirective
 graphQL.execute("{hello @skipme()}") //InvalidSyntaxError
 graphQL.execute("{hello}@skipme") //OK, result returned w/o errors
 graphQL.execute("{hello}@skipme()") //OK, result returned w/o errors
```

Motivation: create custom directive to return all "non-lazy" fields on an object

**Comment by dminkovsky** [comment]
What is the official spec pretty vague about?

**Comment by dllx** [comment]
Line 1 should not be a syntax error, it is allowed according to the spec.
Lines 2, 4, 6, 8 are syntax errors because argument lists, when given, must contain at least one argument.
Line 3 is a syntax error: directives must come after the field name
Line 5 is allowed according to the spec (no syntax error)
Line 7 should be a syntax error, no directives allowed after the top level selection set.

I did not check, but if your observations are correct, then the reactions in cases 1, 7, and 8 of graphql-java are wrong.

**Comment by bbakerman** [comment]
So looking at this the spec says directives can be on a number of different objects but that this is driven by the server implementation

Directives are always AFTER a named thing.

The grammar in graphql-java (as well as the reference js implementation) has it defined as being allowed on operations
 
    query Root @directive(name : "value")

Note implicit query operations without the name on them cant have directives according to the spec grammar eg:

    { @directive(name : "value") hello }

is not allowed

Directives are allowed also on fields, fragmentSpreads and inlineFragments

    {
       hello @directive( name : "value")
    }

A directive is defined as

    directive :'@' name arguments?;

    arguments : '(' argument+ ')';

    argument : name ':' valueWithVariable;


hence mandatory name and optional arguments but once there is brackets there MUST be arguments

So from above

     graphQL.execute("@skipme{hello}") // CORRECT InvalidSyntaxError - not allowed here
     graphQL.execute("@skipme(){hello}") // CORRECT InvalidSyntaxError - brackets need arguments
     graphQL.execute("{@skipme hello}") //CORRECT InvalidSyntaxError - wrong side of the name
     graphQL.execute("{@skipme() hello}") //CORRECT InvalidSyntaxError - wrong side of the name
     graphQL.execute("{hello @skipme}")  ??
     graphQL.execute("{hello @skipme()}") //CORRECT InvalidSyntaxError - brackets need arguments
    graphQL.execute("{hello}@skipme") ??
    graphQL.execute("{hello}@skipme()") ??

So this leaves:

    graphQL.execute("{hello @skipme}") //ValidationError, UnknownDirective

Thijs would be expected since the runtime does not know about @skipme.  It knows skip and include but not skipme.  Unfortunately the runtime does not allow you to add custom directives into it yet.  But thats another issue

    graphQL.execute("{hello}@skipme") //OK, result returned w/o errors
    graphQL.execute("{hello}@skipme()") //OK, result returned w/o errors

This I am not 100% sure of.  I think its invalid but it might be being ignored because its out in space.  The second is definitely invalid because brackets require arguments.

I didnt run the last 2 per say to assert they do succeed.  If they do I thinks it because they are dangling in the syntax tree and no code cares.  It should be an error I think

**Comment by dllx** [comment]
Yeah, I was wrong above for Line 1. It is not allowed according to the spec. It would be allowed if the operation type (query/mutation) was added, like
```graphql
query @skipme{hello}
```

Regarding
```graphql
graphQL.execute("{hello}@skipme")
```
What is normative on this? Is it the spec? Then the grammar is buggy if it accepts it. If the grammar is normative, then the spec is buggy. But for this corner case, it is probably not important, as only the implementation defines the directives' semantics anyway.

**Comment by bbakerman** [comment]
I recently changed the grammer parsing to throw and error if there are dangling tokens beyond what  is acceptable.  This will catch this last case
