### ISSUE TITLE
ChainedInstrumentation is quite expensive performance-wise

### ISSUE THREAD

**Issue by rrva** [graphql-java/graphql-java#3090]
**Describe the bug**

When profiling, we found that ChainedInstrumentation is quite expensive performance-wise.
Creating a single instrumentation class where we manually combine our instrumentations
gave a 30% performance boost in max requests per seconds in a particular system.

Maybe a more light-weight alternative to ChainedInstrumentation could be included
for users that want to chain instrumentations together that do not mutate the 
instrumentation state and where the return value of beginFieldFetch could be ignored? 

We had three instrumentations, A B and C

A needs to run on beginExecution and beginFieldFetch
B needs to run only on beginFieldFetch
C needs to run only on instrumentExecutionResult

Neither of them make use of `InstrumentationState`, and when manually combining them
we even dropped the return value from each of the instrumentations since
in our particular case it was not needed.

**To Reproduce**

1. Have three instrumentations which inherit from SimpleInstrumentation and override beginFieldFetch. What they actually do could be no-ops.
2. Add them using ChainedInstrumentation
3. Run load tests

ChainedInstrumentation itself actually turns up in the profiling.

**Comment by rrva** [comment]
For reference, this is how the rewritten single instrumentation that we replaced ChainedInstrumentation with looks like:

```kotlin
/**
 * ChainedInstrumentation is slow, so we use this class to more manually combine multiple instrumentations into one.
 */
class GraphQLInstrumentations(
    private val recordQueryStatistics: RecordQueryStatistics,
    private val searchQueryCacheTTLInstrumentation: SearchQueryCacheTTLInstrumentation,
    private val queryTimeLimit: QueryTimeLimit?
) : Instrumentation {

    override fun beginExecution(
        parameters: InstrumentationExecutionParameters?,
        state: InstrumentationState?
    ): InstrumentationContext<ExecutionResult>? {
        parameters?.graphQLContext?.get<QueryContext>("queryContext")?.let { queryTimeLimit?.recordQueryStart(it) }
        return super.beginExecution(parameters, state)
    }

    override fun beginFieldFetch(
        parameters: InstrumentationFieldFetchParameters?,
        state: InstrumentationState?
    ): InstrumentationContext<Any>? {

        parameters?.environment?.let {
            recordQueryStatistics.recordStats(it)
        }
        val queryContext = parameters?.environment?.queryContext()
        if (queryContext != null && parameters.executionContext != null) {
            queryTimeLimit?.validateQueryTimeLimit(parameters.executionContext, queryContext)
        }
        return super.beginFieldFetch(parameters, state)
    }

    override fun instrumentExecutionResult(
        executionResult: ExecutionResult?,
        parameters: InstrumentationExecutionParameters?,
        state: InstrumentationState?
    ): CompletableFuture<ExecutionResult> {
        val queryContext = parameters?.graphQLContext?.get<QueryContext>("queryContext")
        if (queryContext != null && executionResult != null) {
            val result = searchQueryCacheTTLInstrumentation.addCacheTTLForShortSearchQueries(queryContext, executionResult)
            if (result != null) {
                return result
            }
        }
        return super.instrumentExecutionResult(executionResult, parameters, state)
    }

}
```

**Comment by bbakerman** [comment]
Thanks for the feedback.  We have two challenges with ChainedInstrumentation - one of throughput and one of memory usage.

In v19 we improved things in this area.  The first fix was that Instrumentation state is passed direct and hence does requires a memory allocation to make one per "chained" instrumentation callback.  This should relieve memory pressure and nominally avoid allocation work as well.

A new based class was introduced (`graphql.execution.instrumentation.SimplePerformantInstrumentation`) that is a better default for methods that are not overridden.  We had to introduce a new class because the older `SimpleInstrumentation` had implicit behaviours that we had to preserve.  It is however deprecated so use `SimplePerformantInstrumentation` on going.


There is also a special `graphql.execution.instrumentation.NoContextChainedInstrumentation` that always returns null for `graphql.execution.instrumentation.InstrumentationContext` again to avoid allocation (which can move objects from stack to longer term gc generations).  This should also result in faster apps.

That said if you are after the absolutely fastest throughput then your approach above of "hand coding" you own custom chaining is the right way.

The base library has to make a balancing act between an API that's easy to use in a general sense (many people do not push their servers to the edge in performance terms) and high performance.   `ChainedInstrumentation` is an example of that balance

Can you please tell us what version of graphql-java you tested this performance on and if you can can you share performance profiling details on what parts took the longest.

**Comment by rrva** [comment]
This was on 19.2. 

I'll maybe attach a scrubbed recording or zoomable flame graph later but this is how the part of a flamegraph containing ChainedInstrumentation stacks looks like. So with ExecutionStrategy.resolveFieldWithInfo as a starting point we saw quite a lot of ChainedInstrumentation traces:


<img width="1467" alt="Screenshot 2023-02-12 at 21 00 14" src="https://user-images.githubusercontent.com/887132/218335368-15d6c0a9-4530-4557-8ad2-d9e107d68d91.png">


Some of the ChainedInstrumentation traces zoomed in:

<img width="1476" alt="Screenshot 2023-02-12 at 21 02 43" src="https://user-images.githubusercontent.com/887132/218336242-d88e2cf6-46fc-4164-a436-6af19648e2f8.png">

<img width="1484" alt="Screenshot 2023-02-12 at 21 06 50" src="https://user-images.githubusercontent.com/887132/218336268-e6e23823-e759-4071-94d8-88d2eadee51c.png">

**Comment by rrva** [comment]
This is not accounting for allocations caused which you mentioned, probably that also contributed to the improvement we got
