### ISSUE TITLE
Scalars.GraphQLID#serialize should support serialization of Long 

### ISSUE THREAD

**Issue by mindas** [graphql-java/graphql-java#313]
My underlying object which I am exposing via graphql-java has identifier of type Long.
The object is loaded correctly but when the results are returned, id is omitted.
This happens because of the following lines in Scalars.java:171-178

```
if (input instanceof String) {
   return input;
}
if (input instanceof Integer) {
   return String.valueOf(input);
}

return null;
```

Would it not make sense to add handling for Long type here? Thank you!

**Comment by bbakerman** [comment]
I agree - I think it might be better as something like

            if (input != null) {
                return String.valueof(input);
            }
            return null;

The toString() of an object is a valid identifier in the absence of any other "interface" to say otherwise

**Comment by bbakerman** [comment]
The spec is ambiguous about this

http://facebook.github.io/graphql/#sec-ID

As in its the graphql "server" implementations choice.  However it does say that errors should be raised if an input is not acceptable rather than null being generated.

I think graphql-java should be more lenient on ID types in this case

**Comment by andimarek** [comment]
That we produce an Error instead of null is fixed with #455 (and further modified with  #487 )

**Comment by bbakerman** [comment]
A PR for this has been merged

**Comment by bbakerman** [comment]
https://github.com/graphql-java/graphql-java/pull/511
