### ISSUE TITLE
Implement @oneOf directive

### ISSUE THREAD

**Issue by dondonz** [graphql-java/graphql-java#3266]
Hot off the press! A new built-in directive is about to get merged into the spec https://github.com/graphql/graphql-spec/pull/825

JS implementation: https://github.com/graphql/graphql-js/pull/3513

**Comment by bbakerman** [comment]
Some notes I have made after reading the spec.

> It's not. Well, not really - its an internal property of the type that's exposed through introspection - much in the same way that deprecation is.

We might want to consider doing this - that is have a property on `GraphQLInputObjectType` like we do for deprecation.  Looking at the JS code I am pretty sure that what they do as well

> OneOf Input Objects are a special variant of Input Objects where the type system
asserts that exactly one of the fields must be set and non-null, all others
being omitted.

One option is to have  `GraphQLInputObjectType` here as a new type.  But...... it feels like to much of a stretch

> In schema introspection, the `__Type.isOneOf` field will return {true} for OneOf
Input Objects, and {false} for all other Input Objects.

This backs up the idea that is a variant of `GraphQLInputObjectType` and not a new class.

>  If the value of the single entry in the coerced unordered map is {null} an
  error must be thrown.
  
This is incongruous  in some regards - that they are all nullable but at runtime they are not.  But it's the nature of this situation - we must make sure we cater for this at validation times and perhaps at coercing time.

A design question is - should we co-erce to a null value say and then allow validation to catch this bad input data?  If we do this then paths like ENF that coerce but DONT run validation will not catch this situation.  This is something to consider when testing coverage.

> If the Input Object is a OneOf Input Object then:
>      1. The type of the input field must be nullable.
>      2. The input field must not have a default value.


default values is something to watch out for here in testing.

> - `isOneOf` must return {true} when representing a OneOf Input Object, {false}
  otherwise.
  
The Introspection code needs to be updated to handle this.  This is yet more conformation that oneOf is a propery of `GraphQLInputObjectType` and not a new type.
