### ISSUE TITLE
Can InstrumentationContext.onCompleted be added to the Future chain?

### ISSUE THREAD

**Issue by blabla-yy** [graphql-java/graphql-java#3291]
At present, the InstrumentationContext.onCompleted method is completely asynchronously triggered in functions such as fieldComplete and resolveFieldWithInfo. Whether it is executed or not has nothing to do with GraphQL execution.
for example:
```
// resolveFieldWithInfo function
CompletableFuture<ExecutionResult> executionResultFuture = result.thenCompose(FieldValueInfo::getFieldValue);

fieldCtx.onDispatched(executionResultFuture);
executionResultFuture.whenComplete(fieldCtx::onCompleted); // Future here is ignored
return result;
```

In some functions, onCompleted will affect the process, such as in fetchField:
```
return fetchedValue
                 .handle((result, exception) -> {
                     fetchCtx.onCompleted(result, exception); // Subsequent Futures rely on the onCompleted method to run.
                     if (exception != null) {
                         return handleFetchingException(dataFetchingEnvironment. get(), exception);
                     } else {
                         return fetchedValue;
                     }
                 })
                 .thenCompose(Function. identity())
                 .thenApply(result -> unboxPossibleDataFetcherResult(executionContext, parameters, result));
```

This inconsistent behavior, which caused me several problems:
1. If an exception occurs in the onCompleted function, some of the different events will affect the GraphQL result, and some will not. And the neglected Future has no exception handling, that is, I need to do exception handling separately, and pay attention to whether it will affect the execution of GraphQL.
2. The execution timing of the onCompleted function is uncertain because the Future is ignored. There will be a situation where GraphQL has been executed and exited, but the onCompleted function in events such as fieldComplete has not yet been executed. If it is a custom Executor or other situations, the task may be discarded (because GraphQL has completed, the process can exit).

I made some extended functions in Instrumentaion to ensure that onCompleted must be executed before exiting, but I think this function should be perfected in GraphQL-Java.

I expect that all InstrumentationContext.onCompleted behaviors are consistent, and whether to execute asynchronously or in parallel should be better for the user to choose.
for example
```
executionResultFuture. whenComplete(fieldCtx::onCompleted);
return result;
```
Change to:
```
return executionResultFuture.whenComplete(fieldCtx::onCompleted)
                 .thenCompose(ignored -> result);
```

The above is a machine translation, if it is not clear, you can point it out.

**Comment by bbakerman** [comment]
As you asking specifically about the `fetchCtx.onCompleted(result, exception);` that happens inside `graphql.execution.ExecutionStrategy#fetchField` say?

or other places

There are some places where this is not applicable since there is already a dependency -eg `graphql.execution.ExecutionStrategy#resolveFieldWithInfo`

```
        CompletableFuture<FieldValueInfo> result = fetchFieldFuture.thenApply((fetchedValue) ->
                completeField(executionContext, parameters, fetchedValue));

        CompletableFuture<ExecutionResult> executionResultFuture = result.thenCompose(FieldValueInfo::getFieldValue);

        fieldCtx.onDispatched(executionResultFuture);
        //        executionResultFuture.whenComplete(fieldCtx::onCompleted);
        //        return result;
        //
        return executionResultFuture.whenComplete(fieldCtx::onCompleted).thenCompose(ignore -> result);
```

The above hangs because the `executionResultFuture` is a started from a `result.thenCompose` but if we then `.whenCompose` on it and return the `result` it hangs the processing.

Can we get more specific on the place you would like to see fixed and what Instrumentation results you are talking about

In general `Instrumentation` callbacks should run independently of the main engine CFs 

What is it you are doing in `graphql.execution.instrumentation.Instrumentation#beginFieldFetch(graphql.execution.instrumentation.parameters.InstrumentationFieldFetchParameters, graphql.execution.instrumentation.InstrumentationState)` callback that is needed for future instrumentations

**Comment by blabla-yy** [comment]
Yes, it hangs the processing. But if there is a time-consuming operation in onCompleted, I can use the thread pool or create a CF task to solve it asynchronously, so the adjustment is also very simple.
My expectation is that when the GraphQL query is finished, all onCompleted has been called.

There are two use cases for me.
The first one is that each GraphQL has its own Executor to execute, and Executor will not create threads (not thread pool implementation, to avoid parallel problems and save thread resources). Executor is destroyed after GraphQL execution is completed, and at this moment there may be onCompleted function that has not been executed. whenCompleted is just pushed into the Executor task queue. While this can be solved using a workaround, it's a bit counterintuitive to me. GraphQL execution is complete, but there are still tasks to be executed.
Whether asynchronous or multi-threaded is required, I think it should be resolved by my own judgment inside onCompleted. When the Future returned by Execution#execute() completes, all related functions should have been called.

The second is a special requirement that requires me to do data modification in onCompleted (requires GraphQL context and ExecutionResult), although this may not conform to the GraphQL specification. In the current situation, onCompleted may be executed after GraphQL ends (or parallel modification occurs).

**Comment by bbakerman** [comment]
> When the Future returned by Execution#execute() completes, all related functions should have been called.

yeah so this is an a challenging requirement - because I am sure this makes sense for some use cases such as yours.

but imagine another - imagine say an observability use case where an `Instrumentation` observes things as they fly past and then "asynchronously" reports them to a observability platform.  It would have the opposite requirement - it would want to main data flow processing to happen as fast as possible and it can report its observability data at its leisure.

eg its CF is a fire and forget - there is no "happens before" relationship between it running and graphql processing ending

I can't say we deliberately designed it like this - part of our processing maybe the way it is by both design and accident.

But thinking more on it -  `Instrumentation` is in the whole a side effect driven system and hence async side effects mostly should just happen without preconditions mostly.

(That said we do have side effect driven callbacks in `Instrumentation` that are relied on by the engine.  `graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation` is the main one.  It absolute relies on `graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation#beginFieldFetch` completing before  it does it work and hence it will hold up the engine until it dispatches the dataloader.

but this is one way - the engine is not aware is held up (via uncompleted dataLoader.load() CFs) and just waits for field CFs to complete (which only happens because the DataLoaderDispatcherInstrumentation gets called).

**Comment by blabla-yy** [comment]
I can understand another requirement you mentioned. The current design is to make Instrumentation independent of the GraphQL processing flow as much as possible.
But why not modify graphql.execution.ExecutionStrategy#fetchField to make the design consistent.
```
fetchedValue. whenComplete(fetchCtx::onCompleted);
return fetchedValue
                  .handle((result, exception) -> {
                      if (exception != null) {
                          return handleFetchingException(dataFetchingEnvironment. get(), exception);
                      } else {
                          return fetchedValue;
                      }
                  })
                  .thenCompose(Function. identity())
                  .thenApply(result -> unboxPossibleDataFetcherResult(executionContext, parameters, result));
```

The main reason I suggest adding to the Future Chain is that while this modification meets the needs of both, users can still submit asynchronous tasks very simply. But the current implementation is very difficult to meet my requirement.


The current operation does depend on Instrumentation. I have implemented two DataLoaderDispatchers, and there are many Instrumentations for GraphQL monitoring. If my suggestion is acceptable to everyone, I think it will be helpful to improve the Instrumentation design.

Speaking of dataloader.dispatch, there seems to be no perfect solution at present. How about giving more options? If someone can accept single-threaded asynchronous (refers to GraphQL Fetcher in the same thread, not DataLoader) and CF specifies Executor (may need to know how to use CF), my Dispatcher can be shared. It supports a chain call of DataLoader in Fetcher, which will not cause GraphQL to be unable to execute all the time, does not need to use Instrumentation, and is lighter than DataLoaderDispatcherInstrumentation.

**Comment by bbakerman** [comment]
> But why not modify graphql.execution.ExecutionStrategy#fetchField to make the design consistent.

```
CompletableFuture<Object> fetchedValue = invokeDataFetcher(executionContext, parameters, fieldDef, dataFetchingEnvironment, dataFetcher);

fetchedValue. whenComplete(fetchCtx::onCompleted);
return fetchedValue
                  .handle((result, exception) -> {
                      if (exception != null) {
                          return handleFetchingException(dataFetchingEnvironment. get(), exception);
                      } else {
                          return fetchedValue;
                      }
                  })
                  .thenCompose(Function. identity())
                  .thenApply(result -> unboxPossibleDataFetcherResult(executionContext, parameters, result));
```

Sorry how does this change the situation.  The `fetchedValue` is a promise to a fetched value.  If we compose it into a `whenComplete(fetchCtx::onCompleted)` then when it completes it will make the instrumentation callback.

However the current code makes the instrumentation callback during a `.handle()` which really is just another "when this is completed" callback.  

Maybe I am missing something here but how does your suggestion above materially change the behavior?

**Comment by blabla-yy** [comment]
The difference between the two is:
whenComplete: conforms to the style of calling onCompeleted in all other places, and isolates the execution of onCompeleted from the execution process of GraphQL.
handle: Since the subsequent GraphQL execution process depends on this CF, it also depends on the operation of onCompeleted. An exception in onCompeleted will also affect the execution of GraphQL.

For example:
```
@Override
public void onCompleted(ExecutionResult result, Throwable t) {
          throw new NullPointerException();
}
```
If it runs in beginField, it will not affect GraphQL execution, and if it is a multi-threaded environment, it will not affect GraphQL execution. In beginFieldFetch, GraphQL execution will fail, and time-consuming tasks will also affect execution.

What I mean is like the onCompeleted function with the same name, it hopes to be consistent in different places. It would be better if they are all similar to calls in the handle, because the subsequent execution depends on this CF, and it is up to the user to handle whether it is asynchronous or multi-threaded.
