### ISSUE TITLE
Preparsed queries

### ISSUE THREAD

**Issue by mattesja** [graphql-java/graphql-java#335]
I want to have my graqhql queries stored on the server like they do: https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5#.hey6w4mi3

To enhance performance it would be nice, to have the ability to execute a query with a **preparsed query document** (like prepared statements in sql).
So this method should be added to the API:

`public ExecutionResult execute(Document document, String operationName, Object context, Map<String, Object> arguments) {  ...`

My code will look like this:

```
 // initializing phase
 Document document = parser.parseDocument(preparedQuery);

 // execution phase
 graphQL.execute(document, context, arguments)
```

1. Would you support such a pull request?
2. I expect that the graphql.language.Document object will not be modified in an execution, so that it can be reused in multiple threads. Is that correct?

**Comment by bbakerman** [comment]
The project would accept such pull request.  

If you can serialise such as Document without changing Document itself then perfect.  

Out of interest are you planning to serialize the Documents to some persistent storage or rather pre-parse them on system startup say and keep them in memory?

If they go to persistent storage (eg database) then you will want to make sure the read / reconstitution of the Document tree is much faster than a query parse otherwise you wont be buying much

**Comment by mattesja** [comment]
I just want to preparse the queries on system startup and keep them in memory.

I don't think, that a persistent storage of parsed query Documents has a big benefit on performance.

**Comment by dminkovsky** [comment]
Thanks for posting. Yes, this would be cool.

Yeah is there some reason these would need to be persisted beyond RAM?


вт, 28 февр. 2017 г. в 12:29, mattesja <notifications@github.com>:

**Comment by bmsantos** [comment]
One reason that crossed my mind is that with this one can start having Apollo style of persisted queries where queries can be identified by ID (see [here](https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5#.8x56efkiz)). If you have a large schema or just wish to provide many different queries, then one might want to store them in a fast clustered cache such as Couchbase.

**Comment by bbakerman** [comment]
Yeah it makes sense to have them persisted from a "blessed query" point of view.  For example you could be draconian in your system and say "only approved queries that we have tested and stored server side"    That way you guard against runaway queries... since there can be none... they are all build time created.

**Comment by bbakerman** [comment]
This has been added in 4.x.  At least the ability to make your own cache

**Comment by raderio** [comment]
@bbakerman is this documented somewhere?

**Comment by raderio** [comment]
No documentation?

**Comment by bbakerman** [comment]
http://graphql-java.readthedocs.io/en/v4/execution.html#query-caching

**Comment by benmccann** [comment]
New documentation location: https://www.graphql-java.com/documentation/v14/execution/

**Comment by damiangreen** [comment]
That last url 404s. and the one previously, im not sure if i coudl use Apollo FE's persisted queries to talk to graphql-java?
