### ISSUE TITLE
Ability to override scalar descriptions

### ISSUE THREAD

**Issue by genroelgvozo** [graphql-java/graphql-java#3396]
I want to generate documentation in other language. And i describe own types in this language, but builtin scalars description in English. Now scalars are final static fields with final fiels inside, maybe description make not final and get setter for it?

**Comment by dondonz** [comment]
Hello @genroelgvozo, thanks for the suggestion. It is surprisingly quite hard to make the description for scalars flexible, because we do need one representation of each scalar and initialising the scalars happens early on in the process.

Sorry about that, I am usually a fan of multi-language support but in this case it would be quite a challenge.
