### ISSUE TITLE
Threading agnostic model could lead to block threads

### ISSUE THREAD

**Issue by samuelAndalon** [graphql-java/graphql-java#3423]
The main entrypoint to graphql-java [executeAsync](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L415), returns a CompletableFuture, which is fine, however, during GraphQL execution there are 2 CPU blocking operations:

1. Parse
2. Validation

For obvious reasons these 2 steps of the execution are blocking, so i was wondering if we could:

1. Create new instrumentations for parsing and validation to be able to override the behavior (similar to [instrumentDataFetcher](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/Instrumentation.java#L508)), then in those instrumentations we could use specific thread abstractions to execute that blocking job in a dedicated dispatcher, scheduler, etc.
2. Expose the [parseAndValidate](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L485) method so we could separately do parse, validate and execution.

**Comment by bbakerman** [comment]
> For obvious reasons these 2 steps of the execution are blocking, 

They are indeed CPU bound but I kinda disagree with the term blocking - usually that word is reserved for code that makes some IO style calls and blocks the thread from running - this code is not that - it is very much CPU bound.

Lets breaking them down here

Parsing/Validation is CPU bound but actually the ANLTR is really quite fast - do you have evidence of it being very slow?

One way to alleviate this is to use `graphql.execution.preparsed.PreparsedDocumentProvider` which has a async method - `CompletableFuture<PreparsedDocumentEntry> getDocumentAsync(ExecutionInput executionInput, Function<ExecutionInput, PreparsedDocumentEntry> parseAndValidateFunction)`

We use this in Atlassian to have a document cache that is backed by Caffeine - if we have seen the document before and parsed it and validated it, we can re-use it without needing to parse and validate

```
    private PreparsedDocumentEntry getFromCache(RequestContext requestContext, ExecutionInput executionInput, Function<ExecutionInput, PreparsedDocumentEntry> parseAndValidateFunction) {
        try {
            CacheKey cacheKey = new CacheKey(executionInput.getQuery(), executionInput.getOperationName());
            return parsedDocumentCache.get(cacheKey, (query) -> {
                return parseAndValidateFunction.apply(executionInput);
            });
        } catch (Exception e) {
            requestContext.apilog(log).warn("Unable to get document out of cache", e);
            return parseAndValidateFunction.apply(executionInput);
        }
    }
```

This led to a dramatic reduction in parse time (because e get the same queries over and over) but its a saving of many times a small amount - parsing / validation was never really slow.

You will notice that this is a async operation.  So in theory could use this to "offload" the parsing and validation work onto another thread pool even without a document cache.  So in reality you can do what you have asked for today

**Comment by bbakerman** [comment]
I am closing this as working as expected - its not blocking as described.  There is an async mechanism for as well if some one was truly doing IO in the parse / validate steps
