### ISSUE TITLE
Some CPU overhead from ChainedInstrumentation

### ISSUE THREAD

**Issue by DanielThomas** [graphql-java/graphql-java#3436]
**Describe the bug**

We register more than one instrumentation as part of our DGS framework, which leads to `ChainedInstrumentation` being used. This class shows as a hotspot for field instrumentation in particular. In the case of the application I was looking at, I'd estimate it's 5-8% of the CPU overhead while satisfying queries:

<img width="1174" alt="Screenshot 2024-02-05 at 8 53 12 pm" src="https://github.com/graphql-java/graphql-java/assets/1479220/d58f245b-6e40-4392-8722-572e7606a0cb">

Data fetching for this service is all GRPC/Netty/EVCache, so `graphql-java` hotspots become more visible that they might otherwise be; this is very likely the worst case for this class.

**To Reproduce**

Note the overhead of field instrumentation when using chained instrumentations, due to the frequency of `beginField` calls for any non-trivial query.

**Comment by bbakerman** [comment]
> This class shows as a hotspot for field instrumentation in particular.

> Note the overhead of field instrumentation when using chained instrumentations, due to the frequency of beginField calls for any non-trivial query.

So in many ways this is expected.  The profiling above shows 

```
private InstrumentationState getState(Instrumentation instrumentation) {
            return instrumentationToStates.get(instrumentation);
}
```

which is a hashmap of states in the chain.  A map look up should not be slow but it is being called often.

The same is true of beginField - if you query has lots of fields - the instrumentation is going to get a callback  for each field.

You mention that you have a couple of instrumentations - what are they ?

Ideally they would directive from `graphql.execution.instrumentation.SimplePerformantInstrumentation` which is newish and a smidge more performant.

The optimization that @rrva has will be faster because its very specific.  The graphql java code needs to be able to generically run any instrumentation.  Where as @rrva runs specific bits of code that he is aware of - which is a faster way to run things but its not generic - its highly coupled to specific code

That said the next version of graphql-java is trying to reduce the default data loader instrumentation that always gets added.  Instead if will be implemented in the engine itself.  This MAY save some time but we havent yet done the perf tests for that.

**Comment by DanielThomas** [comment]
We have 6 instrumentations, more if a service adds application specific ones - so at least 6 `getState` calls for every field.

I've fixed this here:

https://github.com/graphql-java/graphql-java/pull/3459

**Comment by bbakerman** [comment]
Closing as fixed in v22
