### ISSUE TITLE
Question: Retrieving locale

### ISSUE THREAD

**Issue by jameskleeh** [graphql-java/graphql-java#461]
In a typical rest api, it is quite easy to get the locale straight from the request. Does this API provide some means of having the locale available in a data fetcher for example ?

**Comment by andimarek** [comment]
do you mean something like a  `Accept-Language` header?

**Comment by jameskleeh** [comment]
Right, so my question is how would I get the value of that header?

**Comment by andimarek** [comment]
ok .. I understand.

The answer is: `graphql-java` doesn't give you access to the header, because it is outside of the scope of this library: it has nothing todo with HTTP or how your transport protocol looks like.

If you need access to some environment/query specific info, `graphql-java` gives you the `context` argument when executing a Query:  https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L178

This means you could read the `Accept-Header` before executing the query and provide this info via `context`. `context` is then available to each `DataFetcher`.

I hope this helps.

**Comment by jameskleeh** [comment]
@andimarek That is exactly what I was looking for. Thanks!
