### ISSUE TITLE
Error while using IDL

### ISSUE THREAD

**Issue by ajmalsha** [graphql-java/graphql-java#477]
hi,
I'm using the following idl code snippet.
```
SchemaParser schemaParser = new SchemaParser();
SchemaGenerator schemaGenerator = new SchemaGenerator();

File schemaFile = loadSchema("starWarsSchema.graphqls");

TypeDefinitionRegistry typeRegistry = schemaParser.parse(schemaFile);
RuntimeWiring wiring = buildRuntimeWiring();
GraphQLSchema graphQLSchema = schemaGenerator.makeExecutableSchema(typeRegistry, wiring);
```

In this the `loadSchema("starWarsSchema.graphqls");` and `buildRuntimeWiring()` these two are not working .
It  show error like `The method loadSchema(String) is undefined for the type GraphQLSchemaBuilder`

Can you please help me?

**Comment by andimarek** [comment]
As mentioned before: these are not fully working examples. It is just a code snippet. You have to implement the missing parts yourself.

Just a general note, because you posted a few questions lately: it seems that a lot of your problems are not `graphql-java` related, but are general Java questions.

We can't help with you that, I am sorry. We can only help with `graphql-java` here. I hope you understand. Thanks!
