### ISSUE TITLE
How can I generate custom errors during resolve

### ISSUE THREAD

**Issue by raderio** [graphql-java/graphql-java#661]
Example: I want to throw exception based on certain business rules OR based on some generic validation. Simple example would be to have an incoming ID of type GraphQLNonNull, however, if someone passes it empty ( "" ) then I want to generate error as Parameter "xyz" must be provided. This error should appear under the errors section on graphql response.

**Comment by bbakerman** [comment]
"" in java is considered non null which is why I think this example passed basic validation.

In order to do full business rule validation you need to do this in the DataFetcher for that input.

```
DataFetcher inputDF = environment -> {
     String id = environment.getArgument("id");
     if (! isValid(id)) {   // your logic here
       throw new ValidationException("No happy with this input");
     }
    return lookUpObject(id);

}
```

Any runtime exception thrown inside a DataFetcher will be captured as an graphql error and added to the ExecutionResult error list

**Comment by bbakerman** [comment]
See http://graphql-java.readthedocs.io/en/v4/execution.html#exceptions-while-fetching-data

**Comment by zhewang2** [comment]
Return DataFetcherResult type should be good.

Take a look at DataFetcherResult class and return it as the final type of result with errors.

    public DataFetcherResult(T data, List<GraphQLError> errors) {
        this.data = data;
        this.errors = Collections.unmodifiableList((List)Assert.assertNotNull(errors));
    }
