### ISSUE TITLE
Issues using `TypeResolver`, `BatchedExecutionStrategy` and `CompletableFuture` together

### ISSUE THREAD

**Issue by drewolson** [graphql-java/graphql-java#672]
It seems that if you're using the `BatchedExecutionStrategy` and a `DataFetcher` that provides an interface type returns a `CompletableFuture`, the `CompletableFuture` rather than the raw value is passed to the `TypeResolver` for the interface.

[Here](https://github.com/drewolson/graphql_npe_example/blob/b9cccb4ef84a888783fb1c1312e1cf77a8bda195/src/test/java/AsyncTypeResolverTest.java) is a test that demonstrates the issue.

**Comment by vincentDAO** [comment]
I also got same issue when using BatchedExecutionStrategy and DataFetcher<CompletableFuture<?>> together.

**Comment by bbakerman** [comment]
I have had a look at this more and its tricky one to fix (easily) because of the internal structure of the  BatchExecutionStrategy

the root cause is that the BacthedES expects the return value to always be a Iterable<Object> but what we need up is producing a Iterable<CompleteableFuture> that is a list with a CF inside it

We wrap that list in a CF in the code but its a CF pointing to a List<CF>. 

These objects get passed into as handled as actual objects and not CFS
      handleResult ...

            List<Object> values = result;
            List<FetchedValue> retVal = new ArrayList<>();
            for (int i = 0; i < parentResults.size(); i++) {
                Object value = unboxPossibleOptional(values.get(i));
                retVal.add(new FetchedValue(parentResults.get(i), value));
            }
            return retVal;

eg the object placed into FetchedValue is in fact treated as completed - when in fact it is not completed yet.

Later those fetched results are sent to handlePrimitive and so on a they get treated as coerced objects etc...

I think the FetchedValue idea needs to be come a  FetchedValue of CF promises and not objects

**Comment by bbakerman** [comment]
also the mutation of the parent structure makes this super tough

     private void handlePrimitives(List<FetchedValue> fetchedValues, String fieldName,
                                  GraphQLType type) {
        for (FetchedValue value : fetchedValues) {
            Object coercedValue = coerce(type, value.getValue());
            //6.6.1 http://facebook.github.io/graphql/#sec-Field-entries
            if (coercedValue instanceof Double && ((Double) coercedValue).isNaN()) {
                coercedValue = null;
            }
            value.getParentResult().putOrAdd(fieldName, coercedValue);
        }
     }

This is pushing state up into the parent which also assumes the value is resolved.  Hmmmm

**Comment by bbakerman** [comment]
I take it back its easy to fix.  As I described the problem it told me the answer

List<CF<Object>> needs to become CF<List<Object>

And CF.allOf() allows this

        CompletableFuture[] cfs = results.toArray(new CompletableFuture[results.size()]);
        return CompletableFuture.allOf(cfs)
                .thenApply(v -> results.stream()
                        .map(CompletableFuture::join)
                        .collect(Collectors.toList()));

**Comment by arlampin** [comment]
@bbakerman there's already an open PR that fixes this

**Comment by drewolson** [comment]
I have confirmed this is fixed for me on master. It would be really great to get this into a `4.1.x` or a `4.2` release along with the introspection fixes. Thanks!

**Comment by andimarek** [comment]
yes, we will do `4.2`.

**Comment by drewolson** [comment]
Great, thanks!

**Comment by vincentDAO** [comment]
Great! We're waiting to upgrade our app to 4.2.
