### ISSUE TITLE
Add support for file upload

### ISSUE THREAD

**Issue by ieugen** [graphql-java/graphql-java#692]
Hello guys, 

It would be great to have file upload support from graphql-java or at least some instructions on how to do it. 
This is very common scenario in applications - logo upload, etc and I believe doable. 

I did some research and found one way to do it [1]. 

> Uploading files is simple. All you need to do is attach the file to a multipart/form-data request and point to it using the blobFieldName attribute in the Blob implemented type’s input object.

p.s. When implementing this feature please be aware that there are HTTP implementations not based on `javax.servlet` . vertx is such an implementation. Please do not depend on the servlet API for mult part parsing / file upload. 

[1] https://scaphold.io/docs/#uploading-files

**Comment by andimarek** [comment]
Hi @ieugen, 
I am sorry, but `graphql-java` will not implement file upload (or anything similar) because anything dealing with HTTP (or JSON) is out of scope for this library. `graphql-java` only provides a way to execute graphql queries, nothing more.

See also: https://github.com/graphql-java/graphql-java/issues/652

**Comment by loganvolkers** [comment]
If someone is looking to implement this, here is a proposed spec that uses multipart upload: https://github.com/jaydenseric/graphql-multipart-request-spec
