### ISSUE TITLE
Add statistics support for data loader activity

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#724]
The upcoming version of java-dataloader has statistics about what is being hit and how effectively.

The graphql-java instrumentation should use this and add it to extensions

**Comment by jhaber** [comment]
It seems like the choice to include statistics must be made globally (or least per-`GraphQL` instance), do you think it would make sense to allow this choice at per-execution granularity? For example, we normally don't want to return statistics because it bloats the response, but for debugging we want people to be able to opt-in to seeing the statistics (we're also considering including statistics by default if the query is coming from GraphiQL, etc.).

If you agree this is useful, maybe it should be an option on `ExecutionInput` similar to `DataLoaderRegistry`?
