### ISSUE TITLE
Arguments passed via variables are not validated

### ISSUE THREAD

**Issue by drewolson** [graphql-java/graphql-java#739]
I wrote a [test](https://github.com/drewolson/graphql_npe_example/blob/5fe5e8d1b8d4f913483375ed6f2cdb4b5da06339/src/test/java/VariableValidationTest.java) to demonstrate the issue.

Passing the same, invalid, argument via variables causes it to not be validated before executing the data fetcher.

**Comment by bbakerman** [comment]
OK I started to look into this problem.

First off it seems to be doing the right thing MOSTLY.  That is a variable `$input` will not be validated early since the query validation can only know about co-ercing and validating AST literals.

See http://facebook.github.io/graphql/October2016/#sec-Validation.Variables and how it does not talk about validating variable "values" but only literals.

So its correct that it returns no errors.

Ok that leads us to execution and how to co-erce input values.

`graphql.execution.ValuesResolver#coerceValue` is the method that does this.  The code of interest is here

        } else if (graphQLType instanceof GraphQLInputObjectType && value instanceof Map) {
            //noinspection unchecked
            return coerceValueForInputObjectType(variableDefinition, (GraphQLInputObjectType) graphQLType, (Map<String, Object>) value);
        } else if (graphQLType instanceof GraphQLInputObjectType) {
            return value;
        } else {

So it will take "InputObject" types and Maps and co-erce them.  The spec says as much

http://facebook.github.io/graphql/October2016/#sec-Input-Objects

> Input Coercion

>The value for an input object should be an input object literal or an unordered map, otherwise an error should be thrown. This unordered map should not contain any entries with names not defined by a field of this input object type, otherwise an error should be thrown.

So this is where graphql-java differs.  It does NOT throw an exception on a non map but it just returns the value as is.  

This is wrong I think, certainly according to spec.  The problem with any object is what strategy do you use for pulling part and object?  JavaBean getters?  Field access?  Now all of a sudden you need a "input object co-ercer" so it can be object specific say??

I think we should throw an exception as per spec if the input object is NOT a map.

@andimarek  thoughts on this?

**Comment by bbakerman** [comment]
It looks like the original code followed spec and then this commit was made

https://github.com/graphql-java/graphql-java/commit/1414bc0701677e0d0e1a89b311f9b8d2e64ef33f

>Problem: passing input object as a resolved class doesn't work  ValueResolver makes an assumption that an object passed through is always going to be a map.  However, when using graphql-java with graphql-java-annotations and graphql-java-servlet (GraphQLVariables), the inputs passed through are already resolved.  Solution: this patch allows to pass such objects through the resolver unmodified, without throwing an exception.

So I think this is a sensible compromise.  That is if the inside can understand the object then all is good.

I think in drews case he was not expecting it to make it passed validation (which it always would have) so its not quite the same thing.

So the real question here is - does graphql-java want to follow spec or do they want to allow a more loose construct in the objects that enter data fetchers as arguments.

I think it should do the latter.  Its easy in graphql-js to say EVERYTHING must be a map,  because everything is!  But in java (and other languages) we have stronger types and hence more object concerns.

**Comment by drewolson** [comment]
@bbakerman I disagree with the conclusion here. I strongly believe that coercion should throw an error if an unexpected (non-coercible) value is found in the provided variables.

The primary reason for this is that, as a user of GraphQL, I should be able to have the expectation that all the arguments to my fields will be type-checked against the provided GraphQL schema. This is, of course, one of the primary benefits of using GraphQL in the first place. If I want to provide my users the ability to use variables (I do) and graphql-java chooses to not validate the values within the variables, this means that I must assume that _any_ argument to my data fetchers may be invalid at the time the data fetcher is invoked. To me, this removes a primary benefit of using GraphQL -- the idea that the domain logic in my application can assume valid input and that this is guaranteed by the GraphQL implementation.

All other major implementations behave in the way my test was expecting. [Here](https://github.com/drewolson/graphql_mutation_example_ruby/blob/3861be8a503848768fae85be00c663161a23a60e/spec/example_spec.rb) is an example of the same issue in the graphql-ruby library. It correctly (in my opinion) fails with invalid input values provided via variables (both in simple and more complex cases). I'd be happy to also build examples in elixir and javascript.

Perhaps I'm misunderstanding your proposed solution and, if so, I apologize. I think it is vitally important that a data fetcher can trust both the structure and type of values that are provided as arguments, regardless of passing these values as literals or variables.

**Comment by drewolson** [comment]
Here's the specific section of the spec I believe this behavior is at conflict with: http://facebook.github.io/graphql/October2016/#sec-Coercing-Variable-Values

The line that is most relevant to this discussion is:

> Otherwise, if value cannot be coerced according to the input coercion rules of variableType, throw a query error.

If the goal is to allow other libraries the ability to turn a set of resolved variables into a POJO, that's fine, but it should happen after the raw variables are coerced into a Map. In my application, I do this manually using Jackson with something like `objectMapper.convertValue(env.getArgument("input"), MyClass.class)` in my data fetcher.

**Comment by bbakerman** [comment]
Just on the idea of graphql error versus a runtime exception, the spec says

> Otherwise, if value cannot be coerced according to the input coercion rules of variableType, throw a query error.

eg it says you should throw an error.

The ruby example above does not throw an exception but rather adds error messages.  

I can see an argument for doing it that way since the literal validation results in an error in the result list but variable map validation does not.

**Comment by drewolson** [comment]
@bbakerman I think you're right that throwing an error would also be in the spirit of the spec. It might be slightly more inconvenient for implementers but I think it's definitely usable.

Here's the line that convinced me that some kind of error (thrown or added to `errors`) is correct:

> If a query error is encountered during input coercion of variable values, then the operation fails 
without execution. [1]

I think the `without execution` phrasing is very relevant to this discussion.

Thanks for the conversation so far, looking forward to how you decide to handle it.

[1] - From: http://facebook.github.io/graphql/October2016/#sec-Coercing-Variable-Values

**Comment by bbakerman** [comment]
We discussed this in the maintainers room and have decided to follow spec.  5.0 will revert the previous hack that allow any object to come in as GraphQLInputObjectType input variable.

It will not throw an exception as per the spec (not a graphql error).

The linked PR now has that fix
