### ISSUE TITLE
Empty List of String scalars results into list with one null element

### ISSUE THREAD

**Issue by kristofdepypere** [graphql-java/graphql-java#74]
When doing a mutation requests the relay way with an input object type with the following schema:

```
{
          "kind": "INPUT_OBJECT",
          "name": "AddFriendRequest",
          "description": null,
          "fields": null,
          "inputFields": [
            {
              "name": "clientMutationId",
              "description": null,
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": null
            },
            {
              "name": "hobbies",
              "description": null,
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "defaultValue": null
            }
          ],
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        }
```

If you do a mutation without any hobbies, on the java side you'll get a ArrayList with one null element. This is highly inconvenient, I would expect the ArrayList to simply be null in this case.

**Comment by danielkwinsor** [comment]
Do you have a test case?  I ask because I'd also like to see this test with your type being [String] and [String!]

According to the coercion rules, we'll attempt to coerce `null` to *type*, where *type* here happens to be List of String.  Check out http://facebook.github.io/graphql/#sec-List-Value
Also, this section on [List Input Coercion](http://facebook.github.io/graphql/#sec-Lists) puts it better than I can.
>If the value passed as an input to a list type is not a list, it should be coerced as though the input was a list of size one, where the value passed is the only item in the list. This is to allow inputs that accept a “var args” to declare their input type as a list; if only one argument is passed (a common case), the client can just pass that value rather than constructing the list.

So we are conforming to spec by providing a list of size 1, with null as the only element.  I fully admit that it doesn't seem the most obvious, from a java dev's point of view.  But there's an RFC on Null Values https://github.com/facebook/graphql/pull/83 that might change things, so let me consider and perhaps make some suggestions.

**Comment by andimarek** [comment]
probably related to #427

**Comment by andimarek** [comment]
Closing this issue, because this is changed/fixed in the upcoming release:

- omitting hobbies completely results in a map without a key `hobbies`
- `hobbies: null` results in a map containing a value `null` for `hobbies`
- `hobbies: [null]` results in a map containing a List with one value null for `hobbies`
