### ISSUE TITLE
Execution time limits

### ISSUE THREAD

**Issue by Macroz** [graphql-java/graphql-java#75]
Hi!

We are developing a next generation journey planner platform and expose our data through GraphQL APIs. We use OpenTripPlanner as our backend, into which we have implemented a GraphQL API using graphql-java.

Now, we would like to impose some limits to how our public API can be used. For example, it would be nice to be able to say that each query may take no longer than a set time, e.g. two seconds. It's quite possible that our 3rd party API users can accidentally ask for too much information, and that would degrade the quality of service for the other users. OTP also does not at its current state survive from out of memory situations, and the way the GraphQL API is implemented does not contain any other resource guards either.

After investigating the situation, I think one way to implement this would be to have the ExecutionContext contain information about the time when the query resolution began, and when spawning new (parallel) futures, i.e. resolving fields, you could check to see if the time limit was exceeded and stop there.

Have you had any thoughts about implementing such querying limitations? And / or do you have interest in developing them? Maybe we can also fit an implementation into our next sprint. Do you think it would be a useful feature for other users as well? Do you have other ideas about this?

Here is some more information, our project is completely open source & open data.
- Here our running "alpha" SPA application http://matka.hsl.fi/
- Source code for the SPA https://github.com/HSLdevcom/digitransit-ui
- And here is our fork of the OpenTripPlanner https://github.com/HSLdevcom/OpenTripPlanner

Thanks!

**Comment by andimarek** [comment]
Hi,

I could imagine that a time limit or a time tracking mechanism could be useful, but probably only for some small use-cases. And to be honest I will not have the time to implement it. 

But I would be happy to give you feedback if you want to develop it youself.

Thanks.

**Comment by Macroz** [comment]
OK I'll see what I come up with regards to the execution limits at least. As far as I can see, when you start exposing your API as GraphQL to 3rd parties, you will want to be able to limit the resources those queries use. Like a typical REST microservice put behind an API gateway.

**Comment by hannesj** [comment]
We implemented this as a [new ExecutionStrategy](https://github.com/HSLdevcom/OpenTripPlanner/blob/eeb58b022a01e16abd7507cd1de095ee71a13375/src/main/java/org/opentripplanner/index/TimedExecutorServiceExecutionStrategy.java). Java provides a nice [ExecutorService#invokeAll](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html#invokeAll(java.util.Collection,%20long,%20java.util.concurrent.TimeUnit)) method allowing us to limit the execution times of the futures. This approach is quite similar to the existing [ExecutorServiceExecutionStrategy](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java). Would you be willing to accept a PR that refactors the current implementation to use the (non-time-limited version of) invokeAll instead of starting the execution of the futures individually, so that we could even offer the time limited version in the default ExecutorServiceExecutionStrategy?

**Comment by dminkovsky** [comment]
Hi @hannesj. Thanks for the suggestion. A question:

> Would you be willing to accept a PR that refactors the current implementation to use the (non-time-limited version of) invokeAll instead of starting the execution of the futures individually, so that we could even offer the time limited version in the default ExecutorServiceExecutionStrategy?

If the current executor service strategy is modified to use the non-timed `#invokeAll()`, the result will be equivalent to what we currently have, right? How, then, will a timed version be provided?

**Comment by Macroz** [comment]
Hi,

I have further improved the `ExecutionStrategy` to limit the number of resolves that are done. This is to impose some memory constraints in addition to the time tracking done by @hannesj changes. 

Here is an [example use]( https://github.com/HSLdevcom/OpenTripPlanner/blob/DT-1410-node-limiting/src/main/java/org/opentripplanner/index/ResourceConstrainedExecutorServiceExecutionStrategy.java) which throws if the limit is exceeded. 

This requires adding support to the strategy like implemented in [this commit](https://github.com/graphql-java/graphql-java/commit/954eaa7aa95d3b87b4c2b09ce259725978698072).

What do you think of these changes? Are you interested in merging them if I do a pull request? And if so, do you see the counting being a useful addition or should the extension point look like something else? Are these changes something that would be useful to others so the `ResourceConstrainedExecutorServiceExecutionStrategy` would be included in `graphql-java` itself?

**Comment by bbakerman** [comment]
The new CompletableFuture support means that is possible to more easily implement this these days

That each data fetcher can be implemented asynchronously by submitting it to a Executor with a timeout out.

The CancellationException that will occur on time out will be captured as graphql errors.

I dont think there really is anything here for the graphql-java engine to do any more and hence I am going to close this issue

**Comment by mudlee** [comment]
Hi. @bbakerman may I ask how would you solve this with timeout? If I fork the `ExecutorServiceExecutionStrategy` or the `AbstractAsyncExecutionStrategy,` and extend the CompletableFutures with a `orTimeout(1,TimeUnit.SECONDS)`, that stops the future after 1 sec, but it does not propagate the `TimeoutException` up, so it won't be a`CancellationException`, and it won't appear in the errors field in the response. Instead, it will be an InternalServerException (with using spring).

Any (more specific) idea, how to handle it correctly?

**Comment by kaqqao** [comment]
Can't you simply complete the future exceptionally after a timeout? No need to touch the execution strategy or anything. The default `AsyncExecutionStrategy` will do the job just fine.

In your fetcher, you can just do `loader.load(key).orTimeout(1, TimeUnit.Seconds)` (standard API since Java 9). Or have a timeout in the `BatchLoader` itself.

That way, you get a future completed with `TimeoutException`, and the normal error handling kicks in.

**Comment by bbakerman** [comment]
Yup if you want to write a system that can timeout ANY call (and you dont have access to all the data fetcher code and hence submit the code with timeout) then use a Instrumentation that wraps each data fetcher with your own.

You would create a wrapping CompletableFuture as @kaqqao said and maintain a list.  In a separate thread you would check if the completed inside your timeout period and complete them exceptionally if they dont.

However I would try to attack this inside your "service layer" and not inside the graphql wiring.  I would have a series of "service calls" that give back a CF that has the above attributes if you can.
