### ISSUE TITLE
Documentation - How to wire DataFetchingEnvironment to InputTypes

### ISSUE THREAD

**Issue by SignalDancer** [graphql-java/graphql-java#777]
Documentation issue I feel, but also a question I have yet to solve despite digging a while. Originally i was using graphql-java-tools before realizing that for various reasons, my use case does not always match, and it would be best to understand the underlying framework first.

The problem I am currently stuck on is I can follow the examples (sort of, they're rarely complete and not always clear which thing applies to which approach programmatic vs idl), but there is no documentation or examples on how to handle custom input types. 

Right now all i get is a generic DataFetchingEnvironment that contains a hashmap - and if one input type refers to another input type (nested), I get another hashmap instead of any of the input types I have specified.

So how do I hook up an input type i have in my schema, have a pojo for, and have declared to be used for a query, but it isn't used or autowired, and i have no idea how to get it wired in so it's passed along properly as the input type i want, not just "Hash map". 

Specifically this is for queries, that have input types, not mutations. Although, if using the IDL specification instead of building a mutation i'm not sure how the arguments would wire in either.

**Comment by bbakerman** [comment]
The graphql spec mandates that input objects that come in via variables MUST be maps.

http://facebook.github.io/graphql/October2016/#sec-Input-Objects

> The value for an input object should be an input object literal or an unordered map, otherwise an error should be thrown. 

Recently graphql-java was changed (in 5.0) so that it enforces this spec behavior.

So we do not support the idea of having POJO classes as inputs.

However your map of maps can be turned into a POJO via something like Jackson say if you are desperate to have a POJO inside your data fetcher.

That would involve a Map objs --> JSON --> POJO which is inefficient but allows what you want.

Whether you use IDL or object type definitions the rules are exactly the same in this regard

**Comment by SignalDancer** [comment]
@bbakerman  if that's true, then, this example in the documentation is outdated correct? There's no way to get a ReviewInput or Episode object back, only a further LinkedHashMap? Or am I misunderstanding?

private DataFetcher mutationDataFetcher() {
    return new DataFetcher() {
        @Override
        public Review get(DataFetchingEnvironment environment) {
            Episode episode = environment.getArgument("episode");
            ReviewInput review = environment.getArgument("review");

            // make a call to your store to mutate your database
            Review updatedReview = reviewStore().update(episode, review);

            // this returns a new view of the data
            return updatedReview;
        }
    };
}

**Comment by bbakerman** [comment]
Yes that is correct.  We will have to update the docs
