### ISSUE TITLE
Pagination with Relay connection

### ISSUE THREAD

**Issue by yarinvak** [graphql-java/graphql-java#794]
Hey,
I am wondering how pagination with relay connection should be used with some efficiency regarding fetching the db.

I want to fetch the exact amount of entities for the specific page, each time the client creates a graphql query of a connection list.
For example, if the client asks for the first 3 entities, I would like to fetch only the first 3 entities from the db (and using the relay connection provided in graphql-java).
And of course I would like to be able to know if there is a next page/previous page as relay specifies, 
but how can I do it if I fetch only the desired entities?

How can I do this correctly? I have searched for some docs regarding this issue but was unsuccessfull.

Thanks!

**Comment by bbakerman** [comment]
Your dont specify the database you are using so I will assume a relational one (with ordering)

In order to paginate any database you need some sort of ordering.

So lets assume you have a table of SALES ordered by sales dat

To get the first three items you need a LIMIT

    select * from SALES  order by SALES.ORDER_DATE limit 3 

Ok that gets 3 out at a time.  You simply then reflect that in the Relay pageInfo that you use.

Relay has the concept of cursors which is an encoded (typcially base64) string that contains instructions of the server.  The client says "get 3 records after this cursor"

You can encode the ordering key (sales.order-date above) into this.

So the query becomes

    select * from SALES  where SALES.ORDER_DATE > cursorDecodedDate order by SALES.ORDER_DATE limit 3 


You need to encode  / decode the ordering key into the "cursor" and sql query

To know if there is "nextPage" or not simply select +1 on the desired limit.  So select4 if you want 3 records.  If you get 4 there is more.  If you get 3 or less then there is no more.

**Comment by guy120494** [comment]
I was going through the code (unfortunately I didn't see any documentation of connection in readdocs) I stumbled across [SimpleListConnection](https://github.com/graphql-java/graphql-java/blob/2829e3665504dcc4c0f428a70f9ee60708548f95/src/main/java/graphql/relay/SimpleListConnection.java).
This class assumes that you fetched all the data before it starts building the connection object, so there is no connection in the DB level (I deduced that from the part where it uses the "after" and "first" arguments). Also, this class creates the cursors, so the datafetcher has no idea of the orders of the cursors, and hence cant use the "after" and "before" argument, and it cant know whether this is the last/first page.

Is this class meant to be used? or we have to implement our connectionBuilder class? if so, don't you think it is better to have a dedicated datafetcher for it? (one that can create a cursor per entity, and can be asked if there are any pages left)

**Comment by bbakerman** [comment]
The SimpleListConnection is pagination of an in memory list as you say.  Not that useful in production code.

Since pagination is very application specific, you often need build your own Connection implementation.  For example deciding on cursors is very application specific.

Recently I was playing with putting a graphql interface of an existing REST API which has page=N&size=Y type pagination.

I ended up with

https://github.com/bbakerman/graphql-java-examples/blob/master/src/main/java/com/graphql/example/proxy/relay/ForwardOnlyFixedPagedDataSet.java

https://github.com/bbakerman/graphql-java-examples/tree/master/src/main/java/com/graphql/example/proxy/relay

Your PR seems ok.  I left a specific comment on it there.

**Comment by bbakerman** [comment]
I am going to close this as more a question than a bug.  Thanks for the question however
