### ISSUE TITLE
Add a well know @fetch directive to graphql-java

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#914]
This would be a carrier for certain functionality such as

    type Query {
          someField : String @fetch(property="someName")
    }

This would cause the PropertyDataFetcher (or FieldDataFetcher) to use `someName` as the property name to fetch and not `someField` as it does today

We would also add other functionality over time if we wanted.  Perhaps

    type Query {
          someField : String @fetch(class="some.Java.Class")
     }

that might instantiate a Java class and use that as the data fetcher say?  I am not saying we do this one but it could be put behind the `@fetch` directive over time.

**Comment by jkjome** [comment]
I'm finding unintuitive/buggy behavior with built-in the `@fetch` directive that appears to have been implemented with issue 914.  It only works if the remapped property name happens to coincide with an existing property name.  In such case, using the `@fetch` directive, I can remap that name to the desired target source property of the bean.  For example, let's say I have a User bean....

```
public class User {
    private Role role;
    private String fullName;
    public Role getRole() { return role; }
    public String getRoleRef() { return role.getId(); }
    public String getFullName() { return fullName; }
}
```
For GraphQL purposes, I'd like to use the `role` property, but mapped to the stringified `roleRef` property.  Similarly, I'd also like remap the 'fullName' property as 'name'.  I would define the GraphQL type as below...

```
type User {
    role: String! @fetch(from:"roleRef")
    name: String! @fetch(from:"fullName")
}
```
Of the above, only the `role` remapping works because there happens to exist a `role` property that returns some value, which allows execution to continue forward and reach the `@fetch` directive to obtain the value of the target property `roleRef`.  However, because the `name` property does not, otherwise, exist in the bean, it causes a schemaParser error, so I can only get the schema to work by directly defining the `fullName` property in the GraphQL schema or changing my bean to include a `name` property (thus defeating the purpose of the `@fetch` directive).  The schemaParser error looks like...

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schemaParser' defined in class path resource [graphql/kickstart/tools/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.kickstart.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is graphql.kickstart.tools.resolver.FieldResolverError: No method or field found as defined in schema <unknown>:31 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  com.acme.model.User.name()
  com.acme.model.User.getName()
  com.acme.model.User.name
.....
```
I can't imagine this is the intended behavior, as it makes it nearly impossible to use for most use-cases (other than happy coincidences like above with the `role` property), with the only "workaround" being defining the desired GraphQL properties on the bean itself, defeating the purpose of `@fetch` in the first place.  Is this is a known issue or am I the first to point it out?  Thoughts?

**Comment by kwburnett** [comment]
First of all, thank you for writing this library. It is extremely helpful to me.

As @jkjome mentioned, I'm running into the same issue as well. I have a User class that looks like:
```
public class User {
    private int user_id;
    public getUser_ID() { return user_id; }
}
```
This class is auto-generated and I'd like to use it instead of extending it. But, when I write the following SDL:
```
type User {
  userId: String @fetch(from: "user_ID")
}
```
I get the same error  that the only methods/properties examined on the `User` class are `userId()`, `getUserId()`, and `userId`.
