### ISSUE TITLE
error handling in custom scalar type deserialization

### ISSUE THREAD

**Issue by trunkate** [graphql-java/graphql-java#927]
I'm reissuing this from @rolandkozma as I'm facing the very same problem and it's more related to this project:

[https://github.com/graphql-java/graphql-java-tools/issues/81](url)

> If an exception happens to be thrown while handling deserialization of a scalar type in:
> I parseValue(Object input); or I parseLiteral(Object input);
> methods from the Coercing<I, O> interface,
> it is not handled and the output of the query will be an empty String, as "".
> 
> Going on the flow I found that in graphql.GraphQL.executeAsync(ExecutionInput) there is a catch that catches AbortExecutionException so I made the exception that I throw at scalar deserialization to extend AbortExecutionException in order to be caught. With this fix, the exception will be passed in my custom GraphQLErrorHandler and something meaningful will be displayed.
> However there is no way to collect the path/name of the field that failed to be deserialized and it would be great to have one.
> I'm not sure, but I think that exceptions like CoercingParseValueException may be considered clientErrors and automatically handled by the framework. What do you think?
> 
> Thanks,
> Roland

**Comment by bbakerman** [comment]
I had a look into this via this unit test

```
    def badScalar = new GraphQLScalarType("BadScalar", "BadToTheBone", new Coercing() {
        @Override
        Object serialize(Object dataFetcherResult) {
            return null
        }

        @Override
        Object parseValue(Object input) {
            throw new CoercingParseValueException("BadToTheBone")
        }

        @Override
        Object parseLiteral(Object input) {
            return 1;
        }
    })

    def "scalar_coercion_reporting"() {
        def runtimeWiring = RuntimeWiring.newRuntimeWiring().scalar(badScalar).type(
                TypeRuntimeWiring.newTypeWiring("Query").dataFetcher("field", new StaticDataFetcher("hello")).build())
                .build()
        def schema = TestUtil.schema('''
            scalar BadScalar
            
            type Query {
                field(arg : BadScalar) : String
            }
        ''', runtimeWiring
        )

        def graphQL = GraphQL.newGraphQL(schema).build()

        def executionResult = graphQL.execute(ExecutionInput.newExecutionInput().query('''
            query X($var : BadScalar) {
                field(arg : $var) 
            }
        '''
        ).variables([var: 'x']).build())

        expect:
        !executionResult.errors.isEmpty()

    }
```

It ends up with the following error in the result

`graphql.schema.CoercingParseValueException: Variable 'var' has an invalid value. BadToTheBone`

The contract on scalar `Coercing` is that parseValue is to return CoercingParseValueException not a general RuntimeException.  We could make that more clear say.

    /**
     * Called to resolve a input from a query variable into a Java object acceptable for the scalar type.
     *
     * @param input is never null
     *
     * @return never null
     *
     * @throws graphql.schema.CoercingParseValueException if value input can't be parsed
     */
    I parseValue(Object input);

The parseValue method is meant to be resilient on its inputs and it should catch runtime exceptions say and translate them into `CoercingParseValueException` 

The `parseLiteral` is even more strict.  It needs to return no exceptions.

    /**
     * Called to convert an query input AST node into a Java object acceptable for the scalar type.  The input
     * object will be an instance of {@link graphql.language.Value}.
     *
     * @param input is never null
     *
     * @return A null value indicates that the literal is not valid. See {@link graphql.validation.ValidationUtil#isValidLiteralValue}
     */
    I parseLiteral(Object input);


It indicates invalid literals via returning null (not exceptions).  This is because the parse will handle the AST literals mostly in shape, but a Timestamp scalar that takes a StringValue AST literal MUST not throw exceptions on parseLiteral.

Rather than add new ways for runtime exceptions to be handled out of the `Coercing` I think I would rather update the JavaDoc about the contract involved

**Comment by bbakerman** [comment]
Thoughts @andimarek ?

**Comment by bbakerman** [comment]
Oh and one other thing

        try {
            coercedVariables = valuesResolver.coerceArgumentValues(graphQLSchema, variableDefinitions, inputVariables);
        } catch (RuntimeException rte) {
            if (rte instanceof GraphQLError) {
                return completedFuture(new ExecutionResultImpl((GraphQLError) rte));
            }
            throw rte;
        }


if the runtime exception is a GraphqlError, it will be transformed into the result.

**Comment by kaqqao** [comment]
If the proper mechanism is already in place, I'm definitely for documenting it clearly instead of adding more on top.

Am I understanding this clearly: CoercingParseValueException will not by itself end up in the response, but a custom subtype that is also a GraphQLError should be thrown to achieve that?

**Comment by bbakerman** [comment]
`CoercingParseValueException` is a graphl error and hence will turn up in the errors response.  But a runtime exception that is not will buble to the top.

**Comment by bbakerman** [comment]
I have updated the documentation and javadoc.  This issue is working as at runtime however

**Comment by ssyy0103** [comment]
Hi, I'm having a similar issue still where if I provide input to a request as a variable, I get this `CoercingParseValueException` as an error in the console rather than it resulting in an error in the GraphQL response body (I get a timeout error instead). This is blocking a lot of progress on my end and I'm not quite sure how to resolve this. Any ideas?

**Comment by ayushs-2k4** [comment]
@ssyy0103  How did you solved it?
